// Paires "L'Intrus" — chaque paire propose un mot principal et son intrus proche.
// Format : [mainWord, intrusWord]. La paire est tirée au sort à chaque manche.
// Les IDs sont calculés depuis la position globale pour rester stables.

export type IntrusPairCategory =
  | "food"
  | "internet"
  | "gaming"
  | "tech"
  | "brands"
  | "celebrities"
  | "movies_tv"
  | "music"
  | "social"
  | "places"
  | "objects"
  | "animals"
  | "sports"
  | "genz"
  | "beauf"
  | "school";

export interface IntrusPairCategoryMeta {
  id: IntrusPairCategory;
  label: string;
  emoji: string;
  description: string;
  adult: boolean;
}

export interface IntrusPair {
  id: number;
  category: IntrusPairCategory;
  mainWord: string;
  intrusWord: string;
}

export const INTRUS_PAIR_CATEGORIES: IntrusPairCategoryMeta[] = [
  { id: "food", label: "Bouffe", emoji: "🍔", description: "Fast-food, plats, snacks, boissons.", adult: false },
  { id: "internet", label: "Internet", emoji: "📱", description: "Apps, sites, drama numérique.", adult: false },
  { id: "gaming", label: "Gaming", emoji: "🎮", description: "Jeux, consoles, archétypes joueurs.", adult: false },
  { id: "tech", label: "Tech", emoji: "💻", description: "Hardware, logiciels, gadgets.", adult: false },
  { id: "brands", label: "Marques", emoji: "🛍️", description: "Enseignes et marques iconiques.", adult: false },
  { id: "celebrities", label: "Célébrités", emoji: "⭐", description: "Personnalités publiques.", adult: false },
  { id: "movies_tv", label: "Films & séries", emoji: "🎬", description: "Univers ciné, séries cultes.", adult: false },
  { id: "music", label: "Musique", emoji: "🎤", description: "Artistes, genres, sons.", adult: false },
  { id: "social", label: "Social", emoji: "💬", description: "Relations, soirées, situations.", adult: false },
  { id: "places", label: "Lieux", emoji: "🗺️", description: "Villes, pays, environnements.", adult: false },
  { id: "objects", label: "Objets", emoji: "🪑", description: "Objets quotidiens et déco.", adult: false },
  { id: "animals", label: "Animaux", emoji: "🐶", description: "Espèces et créatures.", adult: false },
  { id: "sports", label: "Sports", emoji: "⚽", description: "Sports, gestes, archétypes.", adult: false },
  { id: "genz", label: "Gen Z", emoji: "🧠", description: "Brainrot, TikTok, slang.", adult: false },
  { id: "beauf", label: "Beauf", emoji: "🍻", description: "France profonde et apéro.", adult: false },
  { id: "school", label: "École / Boulot", emoji: "📚", description: "Cours, métiers, vie pro.", adult: false },
];

const RAW: Record<IntrusPairCategory, Array<[string, string]>> = {
  food: [
    ["Pizza", "Burger"],
    ["McDonald's", "Burger King"],
    ["Kebab", "Tacos sauce blanche"],
    ["Sushi", "Maki"],
    ["Pasta carbonara", "Lasagnes"],
    ["Crêpe", "Galette"],
    ["Croissant", "Pain au chocolat"],
    ["Tiramisu", "Cheesecake"],
    ["Cookie", "Brownie"],
    ["Café", "Thé"],
    ["Coca", "Pepsi"],
    ["Bière", "Cidre"],
    ["Mojito", "Caïpirinha"],
    ["Vodka", "Tequila"],
    ["Whisky", "Rhum"],
    ["Pastis", "Ricard"],
    ["Champagne", "Crémant"],
    ["Frites", "Chips"],
    ["Ketchup", "Mayo"],
    ["Cornichon", "Olive"],
    ["Steak", "Entrecôte"],
    ["Poulet rôti", "Coq au vin"],
    ["Bo bun", "Pho"],
    ["Ramen", "Udon"],
    ["Pad thaï", "Riz cantonais"],
    ["Tartiflette", "Raclette"],
    ["Fondue savoyarde", "Fondue bourguignonne"],
    ["Cassoulet", "Choucroute"],
    ["Couscous", "Tajine"],
    ["Paella", "Risotto"],
    ["Hot dog", "Bagel"],
    ["Donut", "Beignet"],
    ["Glace vanille", "Glace pistache"],
    ["Yaourt nature", "Yaourt brassé"],
    ["Compote pomme", "Compote poire"],
    ["Smoothie", "Milkshake"],
    ["Matcha", "Chai latte"],
    ["Cappuccino", "Latte"],
    ["Eau plate", "Eau gazeuse"],
    ["Limonade", "Citronnade"],
    ["Bonbons", "Chocolats"],
    ["Carambar", "Malabar"],
    ["Haribo Dragibus", "Haribo Tagada"],
    ["Petit Lu", "Pim's"],
    ["Nutella", "Speculoos"],
    ["Curly", "Monster Munch"],
    ["Lasagnes", "Cannelloni"],
    ["Babybel", "Vache qui rit"],
    ["Comté", "Beaufort"],
    ["Camembert", "Brie"],
    ["Reblochon", "Munster"],
    ["Roquefort", "Bleu d'Auvergne"],
    ["Saucisson", "Chorizo"],
    ["Jambon blanc", "Jambon cru"],
    ["Hot dog américain", "Hot dog suédois"],
    ["Caviar", "Tarama"],
    ["Foie gras", "Rillettes"],
    ["Bûche de Noël", "Galette des rois"],
    ["Croque-monsieur", "Croque-madame"],
    ["Quiche lorraine", "Tarte tatin"],
    ["Macaron", "Cannelé"],
    ["Éclair café", "Éclair chocolat"],
    ["Mille-feuille", "Paris-Brest"],
    ["Tarte au citron", "Tarte aux fraises"],
  ],
  internet: [
    ["TikTok", "LinkedIn"],
    ["Instagram", "Snapchat"],
    ["Twitter", "Threads"],
    ["YouTube", "Twitch"],
    ["Reddit", "4chan"],
    ["Facebook", "Pinterest"],
    ["WhatsApp", "Telegram"],
    ["Discord", "Slack"],
    ["Tinder", "Hinge"],
    ["Bumble", "Fruitz"],
    ["BeReal", "VSCO"],
    ["Spotify", "Deezer"],
    ["Apple Music", "Tidal"],
    ["Netflix", "Disney+"],
    ["Prime Video", "Apple TV+"],
    ["Twitch", "Kick"],
    ["Chrome", "Safari"],
    ["Firefox", "Edge"],
    ["Google", "Bing"],
    ["Gmail", "Outlook"],
    ["Drive", "OneDrive"],
    ["Dropbox", "iCloud"],
    ["Zoom", "Teams"],
    ["Google Meet", "Webex"],
    ["GitHub", "GitLab"],
    ["VSCode", "JetBrains"],
    ["Notion", "Obsidian"],
    ["Figma", "Sketch"],
    ["ChatGPT", "Claude"],
    ["Gemini", "Mistral"],
    ["Midjourney", "DALL-E"],
    ["Stable Diffusion", "Runway"],
    ["Stack Overflow", "Quora"],
    ["Wikipedia", "Reddit"],
    ["IMDb", "Rotten Tomatoes"],
    ["Goodreads", "Letterboxd"],
    ["AliExpress", "Wish"],
    ["Amazon", "Vinted"],
    ["Leboncoin", "Marketplace"],
    ["PayPal", "Lydia"],
    ["Revolut", "N26"],
    ["Uber", "Bolt"],
    ["Deliveroo", "Uber Eats"],
    ["Airbnb", "Booking"],
    ["TripAdvisor", "Yelp"],
    ["Pinterest", "Tumblr"],
    ["Vinted", "Depop"],
    ["Wattpad", "Webtoon"],
    ["Duolingo", "Babbel"],
    ["Strava", "Nike Run Club"],
    ["Headspace", "Calm"],
    ["Shazam", "SoundHound"],
    ["Snapchat Map", "Find My iPhone"],
    ["Google Maps", "Apple Plans"],
    ["Waze", "Citymapper"],
    ["Citymapper", "Bonjour RATP"],
    ["TikTok Live", "Instagram Live"],
    ["Story Instagram", "Story Snapchat"],
    ["Reels", "TikTok"],
    ["Threads", "X"],
  ],
  gaming: [
    ["FIFA", "PES"],
    ["Call of Duty", "Battlefield"],
    ["Fortnite", "Apex Legends"],
    ["Valorant", "Counter-Strike"],
    ["League of Legends", "Dota 2"],
    ["Minecraft", "Roblox"],
    ["GTA", "Red Dead"],
    ["Zelda", "Mario"],
    ["Pokémon", "Digimon"],
    ["Tetris", "Candy Crush"],
    ["Super Smash Bros", "Multiversus"],
    ["Mario Kart", "Crash Team Racing"],
    ["Fall Guys", "Stumble Guys"],
    ["Among Us", "Goose Goose Duck"],
    ["Sims", "Animal Crossing"],
    ["Stardew Valley", "Harvest Moon"],
    ["Witcher 3", "Skyrim"],
    ["Elden Ring", "Dark Souls"],
    ["Sekiro", "Bloodborne"],
    ["Cyberpunk 2077", "Deus Ex"],
    ["Last of Us", "Days Gone"],
    ["God of War", "Devil May Cry"],
    ["Resident Evil", "Silent Hill"],
    ["Outlast", "Phasmophobia"],
    ["FIFA Ultimate Team", "FIFA Carrière"],
    ["NBA 2K", "WWE 2K"],
    ["Tony Hawk", "Skate"],
    ["Need for Speed", "Forza"],
    ["Gran Turismo", "Forza Motorsport"],
    ["Halo", "Destiny"],
    ["PlayStation", "Xbox"],
    ["PS5", "Xbox Series X"],
    ["Nintendo Switch", "Steam Deck"],
    ["Game Boy", "Game Gear"],
    ["DS", "PSP"],
    ["Wii", "PS3"],
    ["Twitch", "YouTube Gaming"],
    ["Streamer FPS", "Streamer JRPG"],
    ["Tryhard", "Casual"],
    ["Smurf", "Boosté"],
    ["AFK", "Troll"],
    ["Camper", "Rusher"],
    ["Cheater", "Smurf"],
    ["Speedrun", "100%"],
    ["Mortal Kombat", "Tekken"],
    ["Street Fighter", "Guilty Gear"],
    ["Diablo", "Path of Exile"],
    ["World of Warcraft", "Final Fantasy XIV"],
    ["Hearthstone", "Magic Arena"],
    ["Clash Royale", "Clash of Clans"],
    ["Brawl Stars", "Brawlhalla"],
    ["Subway Surfers", "Temple Run"],
    ["Pou", "Tamagotchi"],
    ["Fruit Ninja", "Cut the Rope"],
    ["Angry Birds", "Plants vs Zombies"],
    ["Candy Crush", "Bejeweled"],
    ["Wordle", "Quordle"],
    ["Geoguessr", "Worldle"],
    ["Connections", "Wordle"],
    ["Crossy Road", "Subway Surfers"],
  ],
  tech: [
    ["iPhone", "Samsung Galaxy"],
    ["MacBook", "ThinkPad"],
    ["iPad", "Galaxy Tab"],
    ["Apple Watch", "Garmin"],
    ["AirPods", "Beats"],
    ["Bose", "Sony WH"],
    ["Kindle", "iPad mini"],
    ["GoPro", "DJI Osmo"],
    ["DJI Drone", "Parrot Drone"],
    ["PS5 controller", "Xbox controller"],
    ["Logitech souris", "Razer souris"],
    ["Mac Mini", "Intel NUC"],
    ["Bluetooth", "Wi-Fi"],
    ["USB-C", "Lightning"],
    ["HDMI", "DisplayPort"],
    ["SSD", "HDD"],
    ["RAM", "VRAM"],
    ["Nvidia GeForce", "AMD Radeon"],
    ["AMD Ryzen", "Intel Core"],
    ["macOS", "Windows"],
    ["Linux", "Unix"],
    ["Ubuntu", "Fedora"],
    ["Android", "iOS"],
    ["Chrome OS", "ChromiumOS"],
    ["Tesla", "Polestar"],
    ["Tesla Model Y", "Rivian R1S"],
    ["EV", "Hybride"],
    ["Robot aspirateur", "Aspirateur balai"],
    ["Apple Vision Pro", "Meta Quest"],
    ["Quest 3", "PSVR 2"],
    ["Imprimante 3D", "Découpeuse laser"],
    ["Photovoltaïque", "Éolien"],
    ["Bitcoin", "Ethereum"],
    ["Solana", "Cardano"],
    ["NFT", "Token"],
    ["Cloud", "On-prem"],
    ["AWS", "GCP"],
    ["Azure", "DigitalOcean"],
    ["Docker", "Kubernetes"],
    ["GitHub Copilot", "Cursor"],
    ["VSCode", "Sublime Text"],
    ["Postman", "Insomnia"],
    ["Slack", "Microsoft Teams"],
    ["Notion AI", "ChatGPT"],
    ["Wireshark", "tcpdump"],
    ["Mac Studio", "Mac Pro"],
  ],
  brands: [
    ["Adidas", "Nike"],
    ["Puma", "Reebok"],
    ["New Balance", "Asics"],
    ["Lacoste", "Ralph Lauren"],
    ["Levi's", "Wrangler"],
    ["Diesel", "Replay"],
    ["Zara", "H&M"],
    ["Mango", "Bershka"],
    ["Uniqlo", "Muji"],
    ["Patagonia", "The North Face"],
    ["Carhartt", "Dickies"],
    ["Supreme", "Stüssy"],
    ["Off-White", "Balenciaga"],
    ["Louis Vuitton", "Gucci"],
    ["Chanel", "Dior"],
    ["Hermès", "Prada"],
    ["Rolex", "Audemars Piguet"],
    ["Cartier", "Bulgari"],
    ["Tiffany", "Boucheron"],
    ["Sephora", "Marionnaud"],
    ["Decathlon", "Intersport"],
    ["FNAC", "Cultura"],
    ["Auchan", "Carrefour"],
    ["Leclerc", "Intermarché"],
    ["Lidl", "Aldi"],
    ["Monoprix", "Franprix"],
    ["Picard", "Thiriet"],
    ["IKEA", "Maisons du Monde"],
    ["Conforama", "But"],
    ["Boulanger", "Darty"],
    ["Best Buy", "Currys"],
    ["Costco", "Sam's Club"],
    ["Apple Store", "Microsoft Store"],
    ["Starbucks", "Costa Coffee"],
    ["Subway", "Mr Sandwich"],
    ["Domino's", "Pizza Hut"],
    ["KFC", "Popeyes"],
    ["Five Guys", "Shake Shack"],
    ["Burger King", "Quick"],
    ["O'Tacos", "Mr Tacos"],
    ["Pomme de Pain", "Class'Croute"],
    ["Paul", "Brioche Dorée"],
    ["Häagen-Dazs", "Ben & Jerry's"],
    ["Magnum", "Cornetto"],
    ["Coca-Cola", "Pepsi"],
    ["Red Bull", "Monster"],
    ["Schweppes", "Fanta"],
    ["Évian", "Vittel"],
    ["Volvic", "Cristaline"],
    ["Heineken", "Carlsberg"],
    ["Kronenbourg", "1664"],
    ["Desperados", "Sol"],
    ["Disney", "Pixar"],
    ["Marvel", "DC"],
    ["Warner Bros", "Universal"],
    ["Netflix", "HBO"],
  ],
  celebrities: [
    ["Beyoncé", "Rihanna"],
    ["Drake", "The Weeknd"],
    ["Kanye West", "Jay-Z"],
    ["Taylor Swift", "Ariana Grande"],
    ["Billie Eilish", "Olivia Rodrigo"],
    ["Justin Bieber", "Shawn Mendes"],
    ["Bruno Mars", "Ed Sheeran"],
    ["Lady Gaga", "Madonna"],
    ["Adele", "Sam Smith"],
    ["Rosalia", "Aya Nakamura"],
    ["Jul", "Ninho"],
    ["PNL", "Damso"],
    ["Booba", "Kaaris"],
    ["Orelsan", "Lomepal"],
    ["Stromae", "Maître Gims"],
    ["Aya Nakamura", "Wejdene"],
    ["Soprano", "Black M"],
    ["Indila", "Louane"],
    ["Vianney", "Kendji Girac"],
    ["Calogero", "Florent Pagny"],
    ["Goldman", "Patrick Bruel"],
    ["Sardou", "Renaud"],
    ["Cristiano Ronaldo", "Lionel Messi"],
    ["Mbappé", "Haaland"],
    ["Neymar", "Vinicius Jr"],
    ["Pogba", "Griezmann"],
    ["Zidane", "Henry"],
    ["LeBron James", "Stephen Curry"],
    ["Kobe Bryant", "Michael Jordan"],
    ["Serena Williams", "Maria Sharapova"],
    ["Federer", "Nadal"],
    ["Djokovic", "Murray"],
    ["Lewis Hamilton", "Max Verstappen"],
    ["Valentino Rossi", "Marc Marquez"],
    ["Conor McGregor", "Khabib Nurmagomedov"],
    ["Mike Tyson", "Floyd Mayweather"],
    ["Will Smith", "Denzel Washington"],
    ["Leonardo DiCaprio", "Brad Pitt"],
    ["Tom Cruise", "Tom Hanks"],
    ["Ryan Gosling", "Ryan Reynolds"],
    ["Robert Downey Jr", "Chris Evans"],
    ["Chris Hemsworth", "Chris Pratt"],
    ["Margot Robbie", "Emma Stone"],
    ["Scarlett Johansson", "Anne Hathaway"],
    ["Zendaya", "Florence Pugh"],
    ["Timothée Chalamet", "Tom Holland"],
    ["Kim Kardashian", "Kylie Jenner"],
    ["Kendall Jenner", "Bella Hadid"],
    ["MrBeast", "Logan Paul"],
    ["Charli D'Amelio", "Addison Rae"],
    ["Squeezie", "Cyprien"],
    ["Norman", "Hugo Décrypte"],
    ["Mister V", "McFly et Carlito"],
    ["Léna Situations", "EnjoyPhoenix"],
    ["Inoxtag", "Squeezie"],
    ["Joey Starr", "Kool Shen"],
    ["Booba", "Rohff"],
    ["Vladimir Poutine", "Joe Biden"],
    ["Macron", "Sarkozy"],
    ["Donald Trump", "Joe Biden"],
    ["Elon Musk", "Mark Zuckerberg"],
    ["Jeff Bezos", "Bernard Arnault"],
    ["Steve Jobs", "Bill Gates"],
  ],
  movies_tv: [
    ["Stranger Things", "Dark"],
    ["Game of Thrones", "House of the Dragon"],
    ["Breaking Bad", "Better Call Saul"],
    ["The Walking Dead", "Last of Us"],
    ["Friends", "How I Met Your Mother"],
    ["The Office", "Parks and Recreation"],
    ["Brooklyn Nine-Nine", "Modern Family"],
    ["Big Bang Theory", "Young Sheldon"],
    ["Succession", "Industry"],
    ["Squid Game", "Alice in Borderland"],
    ["La Casa de Papel", "Élite"],
    ["Lupin", "Marseille"],
    ["Validé", "Plan B"],
    ["Drag Race", "Drag Race France"],
    ["Top Chef", "MasterChef"],
    ["Koh-Lanta", "Survivor"],
    ["The Voice", "Star Academy"],
    ["Pékin Express", "Le Convoi de l'extrême"],
    ["L'Amour est dans le pré", "Mariés au premier regard"],
    ["Les Marseillais", "Les Anges"],
    ["Touche pas à mon poste", "Quotidien"],
    ["Star Wars", "Star Trek"],
    ["Harry Potter", "Le Seigneur des Anneaux"],
    ["Marvel", "DC"],
    ["Avengers", "Justice League"],
    ["Iron Man", "Batman"],
    ["Spider-Man", "Superman"],
    ["Thor", "Aquaman"],
    ["Doctor Strange", "Wonder Woman"],
    ["Captain America", "Green Lantern"],
    ["Black Panther", "Black Widow"],
    ["Loki", "Joker"],
    ["Thanos", "Darkseid"],
    ["Naruto", "One Piece"],
    ["Dragon Ball", "Bleach"],
    ["My Hero Academia", "Jujutsu Kaisen"],
    ["Death Note", "Code Geass"],
    ["Attack on Titan", "Demon Slayer"],
    ["Hunter x Hunter", "Yu Yu Hakusho"],
    ["Tokyo Ghoul", "Black Clover"],
    ["Pokémon", "Digimon"],
    ["Disney", "Pixar"],
    ["Le Roi Lion", "Mufasa"],
    ["La Reine des Neiges", "Moana"],
    ["Toy Story", "Cars"],
    ["Cars", "Planes"],
    ["Up", "Là-haut"],
    ["Coco", "Vice-Versa"],
    ["Ratatouille", "Soul"],
    ["Le Petit Prince", "Le Petit Nicolas"],
    ["Astérix", "Tintin"],
    ["Inception", "Interstellar"],
    ["Tenet", "Dunkirk"],
    ["Matrix", "Matrix Reloaded"],
    ["Terminator", "RoboCop"],
    ["Alien", "Predator"],
    ["Jurassic Park", "King Kong"],
    ["Indiana Jones", "Tomb Raider"],
    ["James Bond", "Mission Impossible"],
    ["John Wick", "Equalizer"],
    ["Fast & Furious", "Gone in 60 Seconds"],
    ["Pirates des Caraïbes", "Master and Commander"],
    ["Mad Max", "Fury Road"],
    ["Saw", "Hostel"],
    ["Conjuring", "Insidious"],
    ["Scream", "Halloween"],
    ["Annabelle", "Chucky"],
    ["The Shining", "It"],
    ["Final Destination", "Wrong Turn"],
    ["Le Parrain", "Scarface"],
    ["Pulp Fiction", "Reservoir Dogs"],
    ["Forrest Gump", "Big Fish"],
    ["Titanic", "Pearl Harbor"],
  ],
  music: [
    ["Rock", "Métal"],
    ["Pop", "R&B"],
    ["Hip-hop", "Rap"],
    ["Trap", "Drill"],
    ["Reggae", "Dancehall"],
    ["Techno", "House"],
    ["EDM", "Dubstep"],
    ["K-pop", "J-pop"],
    ["Salsa", "Bachata"],
    ["Reggaeton", "Latino pop"],
    ["Jazz", "Blues"],
    ["Classique", "Opéra"],
    ["Country", "Folk"],
    ["Punk", "Hardcore"],
    ["Indie rock", "Indie pop"],
    ["Shoegaze", "Dream pop"],
    ["Lo-fi", "Chillhop"],
    ["Phonk", "Hyperpop"],
    ["Afrobeat", "Amapiano"],
    ["Variété française", "Chanson française"],
    ["Beatbox", "A cappella"],
    ["Karaoké", "Cover"],
    ["Concert", "Festival"],
    ["Coachella", "Lollapalooza"],
    ["Tomorrowland", "Burning Man"],
    ["Eurovision", "Festival de Cannes"],
    ["Hellfest", "Solidays"],
    ["Beats", "AirPods"],
    ["Vinyl", "Cassette"],
    ["CD", "MiniDisc"],
    ["Spotify", "Apple Music"],
    ["Deezer", "Tidal"],
    ["SoundCloud", "Bandcamp"],
    ["MTV", "VH1"],
    ["Top 50", "Hits FM"],
    ["NRJ", "Fun Radio"],
    ["Skyrock", "RFM"],
    ["Boy band", "Girl band"],
    ["One Direction", "BTS"],
    ["Backstreet Boys", "NSYNC"],
    ["Spice Girls", "Destiny's Child"],
    ["Black Eyed Peas", "Maroon 5"],
    ["Coldplay", "Imagine Dragons"],
    ["Arctic Monkeys", "The Strokes"],
    ["U2", "Radiohead"],
    ["Beatles", "Rolling Stones"],
    ["Nirvana", "Pearl Jam"],
    ["Metallica", "Iron Maiden"],
    ["Daft Punk", "Justice"],
    ["David Guetta", "Calvin Harris"],
    ["Avicii", "Tiësto"],
    ["Skrillex", "Diplo"],
    ["DJ Snake", "Martin Garrix"],
  ],
  social: [
    ["Anniversaire", "Crémaillère"],
    ["Mariage", "Pacs"],
    ["Apéro", "Brunch"],
    ["Soirée", "Afterwork"],
    ["Boîte", "Bar"],
    ["Karaoké", "Blind test"],
    ["Beer pong", "Flip cup"],
    ["Action vérité", "Je n'ai jamais"],
    ["Pictionary", "Time's Up"],
    ["Loups-Garous", "Mafia"],
    ["Cluedo", "Mystery box"],
    ["Monopoly", "Risk"],
    ["UNO", "7 Wonders"],
    ["Tinder swipe", "Hinge swipe"],
    ["Speed dating", "Blind date"],
    ["Couple goals", "Friend goals"],
    ["BFF", "Roommates"],
    ["Coloc", "Famille"],
    ["Beuverie", "Dégustation"],
    ["Bachelor", "Bachelorette"],
    ["EVG", "EVJF"],
    ["Anniversaire surprise", "Pot de départ"],
    ["Saint-Valentin", "Galentine's Day"],
    ["Halloween", "Carnaval"],
    ["Noël", "Hanoukka"],
    ["Pâques", "Pâque juive"],
    ["Nouvel An", "Réveillon"],
    ["Mariage civil", "Mariage religieux"],
    ["Baptême", "Communion"],
    ["Anniversaire surprise", "Pot pourri"],
    ["Mojito apéro", "Spritz apéro"],
    ["Rdv galant", "Rdv chez le coiffeur"],
    ["Ghosting", "Soft ghosting"],
    ["Stalker un ex", "Stalker un crush"],
    ["Crush sur Insta", "Crush IRL"],
    ["Tagged dans une story", "Untagged d'une story"],
    ["Pic à thé", "Pic à café"],
    ["Pause clope", "Pause clope électronique"],
    ["Bar à vin", "Bar à bières"],
    ["Bar à tapas", "Bar à sushi"],
    ["Speakeasy", "Rooftop"],
    ["Cabaret", "Burlesque"],
    ["Stand-up", "Improv"],
    ["Comedie club", "Café-théâtre"],
    ["Boîte techno", "Boîte commerciale"],
    ["Festival électro", "Rave"],
  ],
  places: [
    ["Paris", "Lyon"],
    ["Marseille", "Nice"],
    ["Bordeaux", "Toulouse"],
    ["Strasbourg", "Lille"],
    ["Nantes", "Rennes"],
    ["Montpellier", "Aix-en-Provence"],
    ["Cannes", "Saint-Tropez"],
    ["Biarritz", "La Rochelle"],
    ["Brest", "Saint-Malo"],
    ["Grenoble", "Annecy"],
    ["New York", "Los Angeles"],
    ["Tokyo", "Séoul"],
    ["Shanghai", "Pékin"],
    ["Bangkok", "Singapour"],
    ["Bali", "Phuket"],
    ["Maldives", "Seychelles"],
    ["Marrakech", "Casablanca"],
    ["Le Caire", "Dubaï"],
    ["Dubaï", "Abu Dhabi"],
    ["Las Vegas", "Reno"],
    ["Miami", "Cancún"],
    ["Toronto", "Montréal"],
    ["Sydney", "Melbourne"],
    ["Londres", "Manchester"],
    ["Édimbourg", "Glasgow"],
    ["Berlin", "Munich"],
    ["Madrid", "Barcelone"],
    ["Lisbonne", "Porto"],
    ["Rome", "Milan"],
    ["Florence", "Venise"],
    ["Athènes", "Mykonos"],
    ["Santorin", "Ibiza"],
    ["Amsterdam", "Bruxelles"],
    ["Vienne", "Prague"],
    ["Stockholm", "Copenhague"],
    ["Reykjavik", "Helsinki"],
    ["Moscou", "Saint-Pétersbourg"],
    ["Istanbul", "Ankara"],
    ["Mexico", "Bogota"],
    ["Rio", "São Paulo"],
    ["Buenos Aires", "Santiago"],
    ["Tour Eiffel", "Statue de la Liberté"],
    ["Big Ben", "Tour Pise"],
    ["Colisée", "Pyramides"],
    ["Sagrada Familia", "Tour de Pise"],
    ["Times Square", "Picadilly Circus"],
    ["Hollywood", "Bollywood"],
    ["Broadway", "West End"],
    ["Disneyland Paris", "Disneyland Tokyo"],
    ["Parc Astérix", "Futuroscope"],
  ],
  objects: [
    ["Téléphone", "Tablette"],
    ["Ordinateur", "Console"],
    ["Casque audio", "Écouteurs"],
    ["Lunettes", "Lentilles"],
    ["Montre", "Bracelet connecté"],
    ["Sac à dos", "Tote bag"],
    ["Valise", "Sac de voyage"],
    ["Portefeuille", "Porte-monnaie"],
    ["Clé", "Clé électronique"],
    ["Carte bancaire", "Carte cadeau"],
    ["Parapluie", "K-way"],
    ["Casquette", "Bob"],
    ["Bonnet", "Cagoule"],
    ["Écharpe", "Foulard"],
    ["Gants", "Moufles"],
    ["Chaussures", "Baskets"],
    ["Basket", "Sneakers"],
    ["Sandales", "Tongs"],
    ["Bottes", "Boots"],
    ["Lit", "Canapé-lit"],
    ["Canapé", "Fauteuil"],
    ["Table", "Bureau"],
    ["Chaise", "Tabouret"],
    ["Lampe", "Plafonnier"],
    ["Bougie", "Photophore"],
    ["Tasse", "Mug"],
    ["Verre", "Gobelet"],
    ["Bouteille", "Gourde"],
    ["Couteau", "Fourchette"],
    ["Casserole", "Poêle"],
    ["Four", "Micro-ondes"],
    ["Frigo", "Congélateur"],
    ["Lave-linge", "Sèche-linge"],
    ["Aspirateur", "Balai"],
    ["Brosse à dents", "Brosse à cheveux"],
    ["Dentifrice", "Bain de bouche"],
    ["Shampoing", "Après-shampoing"],
    ["Gel douche", "Savon"],
    ["Crème", "Lotion"],
    ["Parfum", "Eau de toilette"],
    ["Pinceau maquillage", "Éponge maquillage"],
    ["Rouge à lèvres", "Gloss"],
    ["Fond de teint", "BB crème"],
    ["Mascara", "Eyeliner"],
    ["Stylo", "Crayon"],
    ["Cahier", "Carnet"],
    ["Sac plastique", "Sac papier"],
    ["Drap", "Couette"],
    ["Oreiller", "Coussin"],
  ],
  animals: [
    ["Chien", "Chat"],
    ["Lapin", "Hamster"],
    ["Tortue", "Iguane"],
    ["Poisson rouge", "Poisson combattant"],
    ["Perroquet", "Canari"],
    ["Furet", "Chinchilla"],
    ["Lion", "Tigre"],
    ["Léopard", "Guépard"],
    ["Loup", "Renard"],
    ["Ours", "Panda"],
    ["Éléphant", "Hippopotame"],
    ["Girafe", "Zèbre"],
    ["Rhinocéros", "Buffle"],
    ["Crocodile", "Alligator"],
    ["Serpent", "Lézard"],
    ["Tortue", "Pangolin"],
    ["Hérisson", "Tatou"],
    ["Singe", "Gorille"],
    ["Chimpanzé", "Orang-outan"],
    ["Aigle", "Faucon"],
    ["Hibou", "Chouette"],
    ["Pingouin", "Manchot"],
    ["Pélican", "Mouette"],
    ["Dauphin", "Requin"],
    ["Baleine", "Orque"],
    ["Pieuvre", "Calamar"],
    ["Crabe", "Homard"],
    ["Étoile de mer", "Méduse"],
    ["Vache", "Buffle"],
    ["Cheval", "Âne"],
    ["Chèvre", "Mouton"],
    ["Cochon", "Sanglier"],
    ["Poule", "Canard"],
    ["Coq", "Dinde"],
    ["Lapin domestique", "Lapin sauvage"],
    ["Licorne", "Pégase"],
    ["Dragon", "Phénix"],
    ["Sirène", "Naïade"],
  ],
  sports: [
    ["Football", "Rugby"],
    ["Tennis", "Padel"],
    ["Basketball", "Handball"],
    ["Volleyball", "Beach volley"],
    ["Boxe", "MMA"],
    ["Karaté", "Judo"],
    ["Aïkido", "Kung Fu"],
    ["Natation", "Apnée"],
    ["Surf", "Bodyboard"],
    ["Kayak", "Paddle"],
    ["Voile", "Catamaran"],
    ["Marathon", "Trail"],
    ["Course à pied", "Sprint"],
    ["Cyclisme", "VTT"],
    ["BMX", "Skate"],
    ["Trottinette", "Skate"],
    ["Hockey", "Curling"],
    ["Ski", "Snowboard"],
    ["Patinage", "Patin à roulettes"],
    ["Escalade", "Bloc"],
    ["Yoga", "Pilates"],
    ["CrossFit", "Hyrox"],
    ["Musculation", "Fitness"],
    ["Zumba", "Aérobic"],
    ["Danse classique", "Danse moderne"],
    ["Hip hop danse", "Breakdance"],
    ["Salsa cubaine", "Bachata"],
    ["Tango", "Valse"],
    ["Pétanque", "Bowling"],
    ["Billard", "Snooker"],
    ["Fléchettes", "Pétanque"],
    ["Golf", "Mini-golf"],
    ["Polo", "Cricket"],
    ["Football américain", "Rugby"],
    ["Baseball", "Softball"],
    ["Esport", "Sport tradi"],
    ["JO", "Coupe du monde"],
    ["Ligue 1", "Premier League"],
    ["NBA", "Euroleague"],
    ["UFC", "Boxe pro"],
    ["F1", "MotoGP"],
    ["Tour de France", "Giro"],
    ["Roland-Garros", "Wimbledon"],
  ],
  genz: [
    ["Slay", "Iconic"],
    ["Sigma", "Alpha"],
    ["Rizz", "Aura"],
    ["Ohio", "Cursed"],
    ["Skibidi", "Hawk tuah"],
    ["NPC", "PNJ"],
    ["Main character", "Side character"],
    ["Villain era", "Healing era"],
    ["Soft launch", "Hard launch"],
    ["Hot girl walk", "Sad girl walk"],
    ["Pilates girl", "Crossfit girl"],
    ["Tradwife", "Girlboss"],
    ["E-girl", "E-boy"],
    ["Looksmaxxing", "Mewing"],
    ["Cottagecore", "Dark academia"],
    ["Y2K", "Indie sleaze"],
    ["Coquette", "Clean girl"],
    ["Brat summer", "Tomato girl summer"],
    ["Goblin mode", "Feral mode"],
    ["Doomscrolling", "Bedrotting"],
    ["Quiet luxury", "Quiet quitting"],
    ["Mid", "Bussin"],
    ["Bussin", "Slaps"],
    ["Cheugy", "Cringe"],
    ["Lowkey", "Highkey"],
    ["No cap", "Fr fr"],
    ["Bestie", "Bff"],
    ["Pookie", "Bae"],
    ["Cap", "Sus"],
    ["Vibe check", "Aura check"],
    ["Slay queen", "Yas king"],
    ["Touch grass", "Log off"],
    ["Iconic", "Legendary"],
    ["Iykyk", "Real ones know"],
    ["GRWM", "Get unready"],
    ["POV", "Day in my life"],
    ["Storytime", "Tea time"],
    ["Spill the tea", "Drop the lore"],
    ["Cancel culture", "Call out culture"],
    ["Hyperpop", "Brainrot music"],
    ["TikTok dance", "BeReal pose"],
    ["Soft launch reveal", "Hard launch reveal"],
    ["Bookrtok", "Booktwt"],
  ],
  beauf: [
    ["Pastis", "Ricard"],
    ["Rosé piscine", "Sangria"],
    ["Marcel", "Débardeur"],
    ["Survet PSG", "Survet OM"],
    ["Tongs", "Claquettes"],
    ["Chaussettes-claquettes", "Sandales socquettes"],
    ["BBQ saucisses", "BBQ merguez"],
    ["Pétanque", "Mölkky"],
    ["Cabanon", "Mobile-home"],
    ["Camping", "Glamping"],
    ["Camping en Bretagne", "Camping en Camargue"],
    ["Camping-car", "Caravane"],
    ["PMU", "Bistrot du coin"],
    ["Bar tabac", "Café du commerce"],
    ["Loto FDJ", "Tirage Euromillions"],
    ["Quine", "Bingo"],
    ["Karaoké Goldman", "Karaoké Pagny"],
    ["Madison", "Macarena"],
    ["Mariage en salle des fêtes", "Mariage en gite"],
    ["Tonton bourré", "Tata pompette"],
    ["Mamie bisous baveux", "Papy ronfleur"],
    ["BMW tunée", "208 tunée"],
    ["Voiture diesel", "Voiture essence"],
    ["Camping-car retraité", "Van aménagé"],
    ["Polo Lacoste", "Chemise hawaïenne"],
    ["Casquette NY", "Casquette Lacoste"],
    ["Pochette ceinture", "Banane LV"],
    ["Tatouage tribal", "Tatouage prénom"],
    ["Piscine gonflable", "Trampoline jardin"],
    ["Réveillon en famille", "Réveillon entre amis"],
    ["Apéro saucisson", "Apéro tapenade"],
    ["Cornichons aigres-doux", "Cornichons classiques"],
    ["Saucisson sec", "Rosette"],
    ["Magret de canard", "Cuisses de canard"],
    ["Choucroute alsacienne", "Choucroute de la mer"],
    ["Aligot", "Truffade"],
    ["Cassoulet de Toulouse", "Cassoulet de Castelnaudary"],
    ["Andouillette", "Tripes"],
    ["Bourride", "Bouillabaisse"],
    ["Pissaladière", "Pissalat"],
    ["Confit de canard", "Magret de canard"],
    ["Tarte flambée", "Pizza alsacienne"],
    ["Camping municipal", "Camping privé"],
  ],
  school: [
    ["Maths", "Physique"],
    ["Philo", "Histoire"],
    ["Français", "Anglais"],
    ["SVT", "Géologie"],
    ["Histoire-géo", "EMC"],
    ["EPS", "Sport au lycée"],
    ["Musique", "Arts plastiques"],
    ["Latin", "Grec ancien"],
    ["Espagnol", "Italien"],
    ["Allemand", "Néerlandais"],
    ["Chinois", "Japonais"],
    ["Brevet", "Bac"],
    ["Mention bien", "Mention très bien"],
    ["Bac S", "Bac ES"],
    ["Spé maths", "Spé NSI"],
    ["Prépa", "BTS"],
    ["BUT", "DUT"],
    ["Master", "Doctorat"],
    ["École d'ingé", "École de commerce"],
    ["HEC", "ESSEC"],
    ["Sciences Po", "Sciences Pô"],
    ["Polytechnique", "Centrale"],
    ["ENS", "EHESS"],
    ["Sorbonne", "Dauphine"],
    ["Erasmus", "Échange Crous"],
    ["Crous", "RU"],
    ["Stage", "Alternance"],
    ["Stagiaire", "Apprenti"],
    ["CDI", "CDD"],
    ["Intérim", "Freelance"],
    ["Open space", "Coworking"],
    ["Bureau partagé", "Bureau perso"],
    ["Réunion Teams", "Réunion Zoom"],
    ["Présentation PowerPoint", "Présentation Keynote"],
    ["Pause café", "Pause clope"],
    ["Mug entreprise", "Mug souvenir"],
    ["Goodies salon", "Tote bag salon"],
    ["Stand-up agile", "Daily scrum"],
    ["Sprint", "Mêlée"],
    ["Lundi matin", "Vendredi 17h"],
    ["Lundi reprise", "Vendredi férié"],
    ["Conf call", "Visio"],
    ["Mail Cdt", "Mail Bien à vous"],
    ["Slack", "Microsoft Teams"],
    ["Excel", "Google Sheets"],
    ["Word", "Pages"],
    ["PowerPoint", "Keynote"],
    ["Outlook", "Gmail Pro"],
    ["Café machine", "Café distributeur"],
    ["Cantine bureau", "Restaurant entreprise"],
    ["Open bar 17h", "Afterwork"],
    ["Séminaire", "Team building"],
    ["Pot de départ", "Pot d'arrivée"],
  ],
};

export const INTRUS_PAIRS: IntrusPair[] = (() => {
  const seenKey = new Set<string>();
  const out: IntrusPair[] = [];
  let nextId = 70001;
  for (const category of INTRUS_PAIR_CATEGORIES) {
    const pairs = RAW[category.id] ?? [];
    for (const [main, intrus] of pairs) {
      const key = normalize(`${main} | ${intrus}`);
      if (seenKey.has(key)) continue;
      seenKey.add(key);
      out.push({ id: nextId, category: category.id, mainWord: main, intrusWord: intrus });
      nextId += 1;
    }
  }
  return out;
})();

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[\s\p{P}]+/gu, " ")
    .trim();
}

export function findIntrusPairById(id: number): IntrusPair | undefined {
  return INTRUS_PAIRS.find((pair) => pair.id === id);
}

export function pickIntrusPair(
  selectedCategories: IntrusPairCategory[] | string[],
  usedPairIds: number[]
): IntrusPair | null {
  const allowed = new Set(selectedCategories.length ? selectedCategories : INTRUS_PAIR_CATEGORIES.map((c) => c.id));
  const used = new Set(usedPairIds);
  const pool = INTRUS_PAIRS.filter((pair) => allowed.has(pair.category) && !used.has(pair.id));
  if (!pool.length) {
    const fallback = INTRUS_PAIRS.filter((pair) => allowed.has(pair.category));
    if (!fallback.length) return null;
    return fallback[Math.floor(Math.random() * fallback.length)] ?? null;
  }
  return pool[Math.floor(Math.random() * pool.length)] ?? null;
}

export function getDefaultIntrusCategories(): IntrusPairCategory[] {
  return ["food", "internet", "gaming", "brands", "movies_tv", "social"];
}
