export type JaugeCategory =
  | "survie"
  | "relations"
  | "argent"
  | "chaos"
  | "soiree"
  | "horreur"
  | "cringe"
  | "gaming"
  | "etudes"
  | "internet"
  | "amitie"
  | "beauf"
  | "dark"
  | "random"
  | "hot"
  | "trash";

export interface JaugeCategoryMeta {
  id: JaugeCategory;
  label: string;
  emoji: string;
  description: string;
  adult?: boolean;
}

export interface JaugeQuestion {
  id: number;
  gameType: "jauge";
  category: JaugeCategory;
  text: string;
}

export const JAUGE_CATEGORIES: JaugeCategoryMeta[] = [
  { id: "survie", label: "Survie", emoji: "🧟", description: "Apocalypse, bunker et décisions douteuses." },
  { id: "relations", label: "Relations", emoji: "💘", description: "Couple, messages et red flags." },
  { id: "argent", label: "Argent", emoji: "💸", description: "Richesse, arnaques et mauvais achats." },
  { id: "chaos", label: "Chaos", emoji: "🧠", description: "Brainrot, memes et comportements en ligne." },
  { id: "soiree", label: "Soirée", emoji: "🍻", description: "After, karaoké et décisions du soir." },
  { id: "horreur", label: "Horreur", emoji: "🔦", description: "Maisons hantées et mauvais choix." },
  { id: "cringe", label: "Cringe", emoji: "😬", description: "Malaise social et stories regrettables." },
  { id: "gaming", label: "Gaming", emoji: "🎮", description: "Ragequit, skins et tryhard." },
  { id: "etudes", label: "Études", emoji: "📚", description: "Procrastination, exams et amphis." },
  { id: "internet", label: "Internet", emoji: "📱", description: "TikTok, dramas et réputation numérique." },
  { id: "amitie", label: "Amitié", emoji: "🤝", description: "Groupe, loyauté et dramas." },
  { id: "beauf", label: "Beauf", emoji: "🔥", description: "Apéro, camping et barbecue." },
  { id: "dark", label: "Absurd noir", emoji: "🕳️", description: "Catastrophes et décisions interdites.", adult: true },
  { id: "random", label: "WTF", emoji: "🌀", description: "Situations absurdes et idées impossibles." },
  { id: "hot", label: "Hot", emoji: "🌶️", description: "Tension, crush et after party.", adult: true },
  { id: "trash", label: "Trash", emoji: "💥", description: "Drama social et chaos assumé.", adult: true },
];

const RAW_JAUGE_QUESTIONS: Record<JaugeCategory, string[]> = {
  survie: [
    "À quel point cette personne survivrait dans une apocalypse zombie ?",
    "À quel point cette personne survivrait seule sur une île ?",
    "À quel point cette personne paniquerait pendant une catastrophe ?",
    "À quel point cette personne serait utile dans un bunker ?",
    "À quel point cette personne deviendrait folle sans internet ?",
    "À quel point cette personne trahirait le groupe pour survivre ?",
    "À quel point cette personne survivrait dans Hunger Games ?",
    "À quel point cette personne oublierait des ressources importantes ?",
    "À quel point cette personne mangerait des trucs douteux pour survivre ?",
    "À quel point cette personne serait un bon leader post-apocalyptique ?",
    "À quel point cette personne ferait confiance trop vite ?",
    "À quel point cette personne survivrait dans un film d’horreur ?",
    "À quel point cette personne réussirait à allumer un feu ?",
    "À quel point cette personne serait dangereuse avec une arme ?",
    "À quel point cette personne survivrait sans dormir ?",
    "À quel point cette personne craquerait psychologiquement ?",
    "À quel point cette personne serait capable de voler de la nourriture ?",
    "À quel point cette personne abandonnerait le groupe ?",
    "À quel point cette personne survivrait dans The Last of Us ?",
    "À quel point cette personne serait capable de dormir dehors ?",
    "À quel point cette personne planifierait un bug-out bag complet en avance ?",
    "À quel point cette personne paniquerait pendant une coupure de courant ?",
    "À quel point cette personne survivrait sans téléphone une semaine ?",
    "À quel point cette personne tiendrait une convention de survivors ?",
    "À quel point cette personne ferait une alliance trop tôt dans une apocalypse ?",
    "À quel point cette personne mangerait son chat pour survivre ?",
    "À quel point cette personne se ferait tuer en allant chercher du wifi ?",
    "À quel point cette personne ferait n'importe quoi pour un dernier café ?",
    "À quel point cette personne deviendrait un leader autoritaire post-apo ?",
    "À quel point cette personne réussirait à allumer un feu sans briquet ?",
    "À quel point cette personne lirait le mauvais panneau d'évacuation ?",
    "À quel point cette personne resterait dans une zone dangereuse par flemme ?",
    "À quel point cette personne donnerait son dernier vivre par culpabilité ?",
    "À quel point cette personne survivrait dans un Cube géant ?",
  ],
  relations: [
    "À quel point cette personne répond vite aux messages ?",
    "À quel point cette personne serait jalouse ?",
    "À quel point cette personne ghosterait quelqu’un ?",
    "À quel point cette personne tomberait amoureuse trop vite ?",
    "À quel point cette personne serait toxique en couple ?",
    "À quel point cette personne pardonnerait une tromperie ?",
    "À quel point cette personne stalkerait un ex ?",
    "À quel point cette personne cacherait ses sentiments ?",
    "À quel point cette personne ferait un bon partenaire ?",
    "À quel point cette personne serait possessive ?",
    "À quel point cette personne finirait dans un triangle amoureux ?",
    "À quel point cette personne ferait semblant d’aller bien ?",
    "À quel point cette personne retournerait avec son ex ?",
    "À quel point cette personne tomberait amoureuse d’un red flag ?",
    "À quel point cette personne serait romantique ?",
    "À quel point cette personne mentirait sur son “body count” ?",
    "À quel point cette personne serait fidèle ?",
    "À quel point cette personne ferait des scènes ?",
    "À quel point cette personne se remettrait vite d’une rupture ?",
    "À quel point cette personne enverrait un message bourré à son ex ?",
    "À quel point cette personne stalkerait son crush sur trois apps simultanément ?",
    "À quel point cette personne ferait un soft launch trop précipité ?",
    "À quel point cette personne ghosterait après un \"je t'aime\" trop rapide ?",
    "À quel point cette personne tomberait dans un situationship sans s'en rendre compte ?",
    "À quel point cette personne aurait des amis qui s'attendent à un drama ?",
    "À quel point cette personne serait capable de love bombing intense ?",
    "À quel point cette personne ferait une grande déclaration en plein bus ?",
    "À quel point cette personne enverrait une pique passive-agressive en story ?",
    "À quel point cette personne accepterait de revoir son ex \"pour parler\" ?",
    "À quel point cette personne tiendrait pas une longue distance ?",
    "À quel point cette personne ferait des plans de mariage seule à 3 dates ?",
    "À quel point cette personne se laisserait convaincre de retomber pour un mauvais arrangement ?",
    "À quel point cette personne pétendrait être sober pour impressionner son date ?",
  ],
  argent: [
    "À quel point cette personne deviendrait arrogante si elle était riche ?",
    "À quel point cette personne gaspillerait son argent ?",
    "À quel point cette personne deviendrait influenceur crypto ?",
    "À quel point cette personne ferait faillite rapidement ?",
    "À quel point cette personne serait radine ?",
    "À quel point cette personne achèterait des trucs inutiles ?",
    "À quel point cette personne deviendrait riche par accident ?",
    "À quel point cette personne ferait un achat à 3h du matin ?",
    "À quel point cette personne tomberait dans une arnaque internet ?",
    "À quel point cette personne prêterait de l’argent ?",
    "À quel point cette personne oublierait de rembourser ?",
    "À quel point cette personne deviendrait riche illégalement ?",
    "À quel point cette personne investirait dans un projet absurde ?",
    "À quel point cette personne achèterait une voiture inutile ?",
    "À quel point cette personne flexerait son argent ?",
    "À quel point cette personne perdrait tout au casino ?",
    "À quel point cette personne ouvrirait un business bizarre ?",
    "À quel point cette personne ferait des achats compulsifs ?",
    "À quel point cette personne deviendrait millionnaire ?",
    "À quel point cette personne serait ruinée après 1 mois de célébrité ?",
    "À quel point cette personne investirait dans un memecoin sans réfléchir ?",
    "À quel point cette personne signerait un crédit conso pour un week-end ?",
    "À quel point cette personne abuserait de cashback douteux ?",
    "À quel point cette personne accepterait un partenariat shady à 50 € ?",
    "À quel point cette personne paierait pour un coach \"abundance\" qui parle en majuscules ?",
    "À quel point cette personne ferait une cagnotte Leetchi pour son anniversaire ?",
    "À quel point cette personne refuserait un café gratuit pour le principe ?",
    "À quel point cette personne ferait un tableau Excel pour ses dépenses de tisanes ?",
    "À quel point cette personne céderait à un haul TikTok à 200 € ?",
    "À quel point cette personne tenterait de revendre ses cadeaux Vinted la semaine de Noël ?",
    "À quel point cette personne ouvrirait un restaurant après deux verres ?",
    "À quel point cette personne perdrait toute notion d'argent en vacances ?",
    "À quel point cette personne ferait croire qu'elle est radin par stratégie ?",
    "À quel point cette personne paierait un abonnement qu'elle n'utilise plus depuis 3 ans ?",
  ],
  chaos: [
    "À quel point cette personne est un PNJ ?",
    "À quel point cette personne serait “sigma” sans ironie ?",
    "À quel point cette personne regarderait des edits TikTok à 4h du matin ?",
    "À quel point cette personne serait influençable ?",
    "À quel point cette personne croirait une fake news ?",
    "À quel point cette personne deviendrait un meme ?",
    "À quel point cette personne posterait un TikTok gênant ?",
    "À quel point cette personne dirait “skibidi” sérieusement ?",
    "À quel point cette personne survivrait sans TikTok ?",
    "À quel point cette personne aurait une phase cringe ?",
    "À quel point cette personne enverrait un vocal de 5 minutes ?",
    "À quel point cette personne serait terminally online ?",
    "À quel point cette personne deviendrait complotiste ?",
    "À quel point cette personne utiliserait ChatGPT pour tout ?",
    "À quel point cette personne aurait des takes catastrophiques ?",
    "À quel point cette personne likerait des trucs gênants par erreur ?",
    "À quel point cette personne serait un “agent du chaos” ?",
    "À quel point cette personne spammerait des memes ?",
    "À quel point cette personne finirait cancel ?",
    "À quel point cette personne perdrait son cerveau après 2h sur TikTok ?",
    "À quel point cette personne lancerait une chaîne YouTube sur les théories du complot ?",
    "À quel point cette personne suivrait un trend bizarre sans comprendre ?",
    "À quel point cette personne reposterait des fake news par flemme de checker ?",
    "À quel point cette personne dirait \"erm acshually\" devant ses parents ?",
    "À quel point cette personne ferait un POV de sa vie au boulot ?",
    "À quel point cette personne parlerait à son chat comme à un FYP ?",
    "À quel point cette personne tomberait dans une rabbit hole Wikipedia à 3h ?",
    "À quel point cette personne croirait qu'un alignement astral va changer sa semaine ?",
    "À quel point cette personne enverrait \"slay\" dans un mail pro ?",
    "À quel point cette personne suivrait un challenge dangereux pour un like ?",
    "À quel point cette personne ferait un edit sad sur sa propre vie ?",
    "À quel point cette personne finirait noyée dans un débat brainrot ?",
    "À quel point cette personne ferait le combo \"sigma\" dans les pires contextes ?",
    "À quel point cette personne surconsommerait du contenu \"je quitte les réseaux\" ?",
  ],
  soiree: [
    "À quel point cette personne finit bourrée en soirée ?",
    "À quel point cette personne vomirait en soirée ?",
    "À quel point cette personne disparaîtrait pendant la soirée ?",
    "À quel point cette personne ferait des déclarations gênantes ?",
    "À quel point cette personne danserait sans honte ?",
    "À quel point cette personne casserait quelque chose ?",
    "À quel point cette personne dormirait sur le canapé ?",
    "À quel point cette personne mixerait tous les alcools ?",
    "À quel point cette personne ferait un blackout ?",
    "À quel point cette personne finirait au McDo à 4h ?",
    "À quel point cette personne ferait n’importe quoi avec l’AUX ?",
    "À quel point cette personne drague quand elle boit ?",
    "À quel point cette personne ferait une énorme gueule de bois ?",
    "À quel point cette personne serait le “parent” du groupe bourré ?",
    "À quel point cette personne ferait un karaoké catastrophique ?",
    "À quel point cette personne lancerait un jeu débile ?",
    "À quel point cette personne enverrait des messages regrettables ?",
    "À quel point cette personne dirait “je suis sobre” alors qu’elle ne l’est pas ?",
    "À quel point cette personne pleurerait bourrée ?",
    "À quel point cette personne volerait un panneau dans la rue ?",
    "À quel point cette personne prendrait l'AUX comme un DJ pro ?",
    "À quel point cette personne déclencherait un débat politique à 3h ?",
    "À quel point cette personne ferait des cookies à 5h pour calmer le groupe ?",
    "À quel point cette personne organiserait une bouffe surprise après la soirée ?",
    "À quel point cette personne ramènerait des gens random rencontrés au bar ?",
    "À quel point cette personne ferait un live Insta pour humilier ses amis ?",
    "À quel point cette personne romprait avec son mec via story ?",
    "À quel point cette personne irait au mauvais étage en boîte sans s'en rendre compte ?",
    "À quel point cette personne ferait un karaoké de Céline Dion sobre ?",
    "À quel point cette personne accepterait un \"after\" douteux avec inconnus ?",
    "À quel point cette personne perdrait son téléphone en boîte chaque sortie ?",
    "À quel point cette personne lancerait un \"Truth or Dare\" qui détruit la soirée ?",
    "À quel point cette personne s'auto-désignerait DJ contre l'avis général ?",
    "À quel point cette personne ferait une scène devant le videur ?",
  ],
  horreur: [
    "À quel point cette personne paniquerait dans une maison hantée ?",
    "À quel point cette personne survivrait à un film d’horreur ?",
    "À quel point cette personne irait voir un bruit bizarre ?",
    "À quel point cette personne regarderait derrière le rideau après un bruit ?",
    "À quel point cette personne dormirait avec la lumière ?",
    "À quel point cette personne croirait aux fantômes ?",
    "À quel point cette personne ferait demi-tour immédiatement ?",
    "À quel point cette personne regarderait un film d’horreur seule ?",
    "À quel point cette personne ferait le mauvais choix dans un film d’horreur ?",
    "À quel point cette personne crierait pendant un jumpscare ?",
    "À quel point cette personne survivrait à un escape game horreur ?",
    "À quel point cette personne serait le premier mort dans un slasher ?",
    "À quel point cette personne paniquerait dans le noir ?",
    "À quel point cette personne écouterait des creepypastas la nuit ?",
    "À quel point cette personne dormirait après un film d’horreur ?",
    "À quel point cette personne irait explorer une maison abandonnée ?",
    "À quel point cette personne deviendrait parano ?",
    "À quel point cette personne ferait semblant de ne pas avoir peur ?",
    "À quel point cette personne regarderait sous le lit ?",
    "À quel point cette personne survivrait à une nuit dans Silent Hill ?",
    "À quel point cette personne ferait un live à 3h dans une maison hantée ?",
    "À quel point cette personne demanderait un cierge à un fantôme ?",
    "À quel point cette personne crierait sur un trailer d'horreur en plein cinéma ?",
    "À quel point cette personne jouerait à un jeu paranormal seul à minuit ?",
    "À quel point cette personne irait dormir dans une grange isolée pour le challenge ?",
    "À quel point cette personne tomberait dans un piège évident d'un slasher ?",
    "À quel point cette personne abandonnerait son groupe en pleine forêt ?",
    "À quel point cette personne croirait qu'un bruit du frigo est un esprit ?",
    "À quel point cette personne ferait un appel vidéo à un cimetière pour la story ?",
    "À quel point cette personne accepterait un Ouija avec inconnus ?",
    "À quel point cette personne reviendrait sur ses pas dans un sous-sol éclairé d'une seule ampoule ?",
    "À quel point cette personne suivrait le bruit \"juste pour vérifier\" ?",
    "À quel point cette personne ferait un escape game à thème horreur en panic mode ?",
  ],
  cringe: [
    "À quel point cette personne ferait un post gênant ?",
    "À quel point cette personne ferait un discours gênant ?",
    "À quel point cette personne raconterait une histoire qui n’intéresse personne ?",
    "À quel point cette personne enverrait un message au mauvais groupe ?",
    "À quel point cette personne rirait au mauvais moment ?",
    "À quel point cette personne ferait semblant de connaître quelqu’un ?",
    "À quel point cette personne tomberait en public ?",
    "À quel point cette personne ferait un silence gênant ?",
    "À quel point cette personne ferait semblant d’être cool ?",
    "À quel point cette personne serait gênante avec un crush ?",
    "À quel point cette personne ferait une story regrettable ?",
    "À quel point cette personne oublierait un prénom ?",
    "À quel point cette personne ferait semblant de comprendre ?",
    "À quel point cette personne serait incapable de mentir ?",
    "À quel point cette personne ferait un fou rire déplacé ?",
    "À quel point cette personne ferait une blague qui flop ?",
    "À quel point cette personne serait awkward en date ?",
    "À quel point cette personne se ridiculiserait en soirée ?",
    "À quel point cette personne ferait un compliment bizarre ?",
    "À quel point cette personne deviendrait un meme du groupe ?",
    "À quel point cette personne ferait un \"oups\" en oubliant des sous-vêtements en visio ?",
    "À quel point cette personne danserait sur une chanson qu'elle ne connaît pas ?",
    "À quel point cette personne dirait quelque chose qu'elle pensait dans sa tête à voix haute ?",
    "À quel point cette personne tagguerait son boss par erreur dans un meme ?",
    "À quel point cette personne se prendrait pour Beyoncé sobre devant tout le monde ?",
    "À quel point cette personne saluerait quelqu'un en pensant le connaître ?",
    "À quel point cette personne pleurerait pendant un débat anodin ?",
    "À quel point cette personne ferait un concert improvisé en transports en commun ?",
    "À quel point cette personne se prendrait au sérieux dans un cosplay ?",
    "À quel point cette personne lirait à voix haute un message gênant par erreur ?",
    "À quel point cette personne tirerait une porte poussez ?",
  ],
  gaming: [
    "À quel point cette personne rage sur un jeu vidéo ?",
    "À quel point cette personne serait toxique en vocal ?",
    "À quel point cette personne dirait “c’est la faute du lag” ?",
    "À quel point cette personne deviendrait accro à un MMO ?",
    "À quel point cette personne achèterait des skins inutiles ?",
    "À quel point cette personne camperait dans un FPS ?",
    "À quel point cette personne ferait ragequit ?",
    "À quel point cette personne survivrait dans un battle royale ?",
    "À quel point cette personne tryhard un jeu casual ?",
    "À quel point cette personne casserait une manette ?",
    "À quel point cette personne regarderait des vidéos lore à 3h du matin ?",
    "À quel point cette personne deviendrait streamer ?",
    "À quel point cette personne oublierait de dormir à cause d’un jeu ?",
    "À quel point cette personne jouerait à Minecraft pendant 12h ?",
    "À quel point cette personne serait un boss final ?",
    "À quel point cette personne serait nulle malgré 2000h de jeu ?",
    "À quel point cette personne paierait un battle pass ?",
    "À quel point cette personne ferait une LAN apocalypse ?",
    "À quel point cette personne ferait “une dernière game” pendant 4h ?",
    "À quel point cette personne survivrait dans Dark Souls ?",
    "À quel point cette personne flame son équipe en silence dans le chat all ?",
    "À quel point cette personne ouvrirait un pack 200 €+ uniquement pour la story ?",
    "À quel point cette personne ferait un troll build ranked ?",
    "À quel point cette personne se ferait kicker d'un Discord ?",
    "À quel point cette personne deviendrait insupportable après une victoire ?",
    "À quel point cette personne expliquerait le lore d'un jeu obscur à un date ?",
    "À quel point cette personne grinderait un event juste pour un skin saisonnier ?",
    "À quel point cette personne se ferait carry sans assumer ?",
    "À quel point cette personne tomberait sur un cheat in-game et balancerait tout en chat ?",
    "À quel point cette personne deviendrait obsédée par une seule statistique ?",
    "À quel point cette personne perdrait son rang en plein season finale ?",
    "À quel point cette personne ferait \"juste une dernière partie\" qui dure 6h ?",
  ],
  etudes: [
    "À quel point cette personne procrastine ?",
    "À quel point cette personne révise la veille ?",
    "À quel point cette personne sèche les cours ?",
    "À quel point cette personne tricherait à un examen ?",
    "À quel point cette personne oublierait un rendu ?",
    "À quel point cette personne dormirait en amphi ?",
    "À quel point cette personne ferait semblant d’écouter ?",
    "À quel point cette personne copierait les devoirs ?",
    "À quel point cette personne serait perdue en groupe de travail ?",
    "À quel point cette personne survivrait à une nuit blanche avant partiel ?",
    "À quel point cette personne ferait des fiches magnifiques inutiles ?",
    "À quel point cette personne réussirait sans travailler ?",
    "À quel point cette personne paniquerait avant un oral ?",
    "À quel point cette personne oublierait sa carte étudiante ?",
    "À quel point cette personne serait le boulet du groupe ?",
    "À quel point cette personne ferait croire qu’elle a révisé ?",
    "À quel point cette personne aurait une crise existentielle pendant les exams ?",
    "À quel point cette personne arriverait en retard à un partiel ?",
    "À quel point cette personne survivrait avec 3h de sommeil ?",
    "À quel point cette personne finirait par changer de filière ?",
    "À quel point cette personne ferait un sujet entier sur Wikipedia la veille de l'oral ?",
    "À quel point cette personne créerait un Discord d'études inutile mais hyper esthétique ?",
    "À quel point cette personne dormirait pendant un partiel surveillé ?",
    "À quel point cette personne signerait absente pour un copain ?",
    "À quel point cette personne ouvrirait Tinder en plein cours ?",
    "À quel point cette personne prendrait des notes en faisant un POV ?",
    "À quel point cette personne dirait \"j'ai pas révisé\" puis aurait 15 ?",
    "À quel point cette personne paniquerait pour une note de 12 ?",
    "À quel point cette personne abandonnerait après une seule mauvaise note ?",
    "À quel point cette personne lancerait une thèse complotiste sur sa prof ?",
    "À quel point cette personne survivrait à un projet de groupe imposé ?",
    "À quel point cette personne ouvrirait un agenda magnifique laissé vide ?",
    "À quel point cette personne mentirait à ses parents sur ses notes ?",
  ],
  internet: [
    "À quel point cette personne scrolle TikTok sans s’arrêter ?",
    "À quel point cette personne posterait un truc gênant ?",
    "À quel point cette personne stalkerait quelqu’un ?",
    "À quel point cette personne oublierait pourquoi elle a ouvert son téléphone ?",
    "À quel point cette personne ferait un live gênant ?",
    "À quel point cette personne se ferait cancel ?",
    "À quel point cette personne lirait les commentaires pendant 2h ?",
    "À quel point cette personne deviendrait influenceur ?",
    "À quel point cette personne regarderait des vidéos inutiles toute la nuit ?",
    "À quel point cette personne enverrait des reels à tout le monde ?",
    "À quel point cette personne serait accro à Instagram ?",
    "À quel point cette personne posterait une story passive-agressive ?",
    "À quel point cette personne regarderait des dramas internet ?",
    "À quel point cette personne ferait un thread Twitter catastrophique ?",
    "À quel point cette personne tomberait dans des débats inutiles ?",
    "À quel point cette personne supprimerait un post par honte ?",
    "À quel point cette personne deviendrait célèbre par accident ?",
    "À quel point cette personne ferait une vidéo virale gênante ?",
    "À quel point cette personne aurait une réputation bizarre sur internet ?",
    "À quel point cette personne survivrait sans réseaux sociaux ?",
    "À quel point cette personne ouvrirait 200 onglets et n'en fermerait aucun ?",
    "À quel point cette personne tomberait dans un MLM Insta ?",
    "À quel point cette personne posterait un avis Google catastrophique ?",
    "À quel point cette personne enverrait un mail trop long pour rien ?",
    "À quel point cette personne mettrait une intelligence artificielle en bio ?",
    "À quel point cette personne parlerait à Siri comme à un thérapeute ?",
    "À quel point cette personne tomberait amoureuse d'un chatbot ?",
    "À quel point cette personne suivrait toutes les tendances en retard de 6 mois ?",
    "À quel point cette personne ferait un \"detox digital\" qui dure 2h ?",
    "À quel point cette personne ferait une story \"je quitte les réseaux\" cinq fois par an ?",
    "À quel point cette personne aurait une bio LinkedIn cringe ?",
    "À quel point cette personne ferait un BeReal raté chaque jour ?",
    "À quel point cette personne tomberait dans un piège phishing évident ?",
  ],
  amitie: [
    "À quel point cette personne est le parent du groupe ?",
    "À quel point cette personne est le chaos du groupe ?",
    "À quel point cette personne oublierait l’anniversaire d’un ami ?",
    "À quel point cette personne ferait un énorme drama ?",
    "À quel point cette personne serait toujours en retard ?",
    "À quel point cette personne serait capable de garder un secret ?",
    "À quel point cette personne jugerait silencieusement ?",
    "À quel point cette personne serait la plus loyale ?",
    "À quel point cette personne lancerait une idée catastrophique ?",
    "À quel point cette personne suivrait les autres sans réfléchir ?",
    "À quel point cette personne survivrait à une colocation ?",
    "À quel point cette personne ferait une blague de trop ?",
    "À quel point cette personne serait le clown du groupe ?",
    "À quel point cette personne disparaîtrait sans répondre pendant 3 jours ?",
    "À quel point cette personne spammerait le groupe WhatsApp ?",
    "À quel point cette personne masquerait sa galère devant ses potes ?",
    "À quel point cette personne ferait le médiateur ?",
    "À quel point cette personne créerait des tensions sans le vouloir ?",
    "À quel point cette personne annulerait au dernier moment ?",
    "À quel point cette personne serait capable de partir vivre à l’étranger demain ?",
    "À quel point cette personne aurait une private joke avec chacun de ses potes ?",
    "À quel point cette personne deviendrait l'organisateur principal du groupe ?",
    "À quel point cette personne créerait un fichier Excel des cadeaux à offrir ?",
    "À quel point cette personne nous oublierait dans une story de groupe ?",
    "À quel point cette personne deviendrait le coach moral de tous ?",
    "À quel point cette personne aurait du mal à dire non à un plan ?",
    "À quel point cette personne ferait du vent à un brunch sans prévenir ?",
    "À quel point cette personne deviendrait spectateur silencieux du chaos du groupe ?",
    "À quel point cette personne pleurerait en regardant les photos d'anniv ?",
    "À quel point cette personne ferait un discours d'anniversaire qui dure 25 min ?",
    "À quel point cette personne organiserait un week-end secret en cachette ?",
    "À quel point cette personne raconterait nos secrets sans s'en rendre compte ?",
  ],
  beauf: [
    "À quel point cette personne porterait des claquettes-chaussettes ?",
    "À quel point cette personne dirait “c’était mieux avant” ?",
    "À quel point cette personne écouterait Jul à fond en voiture ?",
    "À quel point cette personne ferait un barbecue sous la pluie ?",
    "À quel point cette personne finirait dans un PMU ?",
    "À quel point cette personne ferait des blagues de tonton ?",
    "À quel point cette personne serait dangereuse avec une perceuse ?",
    "À quel point cette personne aurait un meuble TV LED ?",
    "À quel point cette personne crierait devant le foot ?",
    "À quel point cette personne aurait une chemise flamme ou palmier ?",
    "À quel point cette personne dirait “chef” à tout le monde ?",
    "À quel point cette personne tunerait une voiture inutilement ?",
    "À quel point cette personne ferait une vidéo Facebook gênante ?",
    "À quel point cette personne boirait de la 8.6 chaude ?",
    "À quel point cette personne aurait une piscine gonflable dans le jardin ?",
    "À quel point cette personne se battrait pour une place de parking ?",
    "À quel point cette personne regarderait les Anges ?",
    "À quel point cette personne ferait des paris sportifs absurdes ?",
    "À quel point cette personne aurait une chaîne hi-fi énorme ?",
    "À quel point cette personne finirait animateur camping ?",
    "À quel point cette personne porterait un marcel sérieusement ?",
    "À quel point cette personne boirait une bière tiède sans problème ?",
    "À quel point cette personne achèterait un quad inutile ?",
    "À quel point cette personne serait capable de vivre en claquettes toute l’année ?",
    "À quel point cette personne ferait un concours de rots ?",
    "À quel point cette personne serait le roi du barbecue ?",
    "À quel point cette personne porterait une banane bien apparente ?",
    "À quel point cette personne mettrait un gilet de tonton à un mariage ?",
    "À quel point cette personne lancerait \"Allez les bleus\" un dimanche pluvieux ?",
    "À quel point cette personne ramènerait une glacière à un cocktail mondain ?",
    "À quel point cette personne taperait sur la table pour demander la chanson \"Allez Allez Allez\" ?",
    "À quel point cette personne ferait du karting bourrée ?",
    "À quel point cette personne adopterait un dogue argentin par fierté ?",
    "À quel point cette personne installerait des spots LED dans son salon ?",
    "À quel point cette personne ferait une compétition de pétanque trop sérieuse ?",
    "À quel point cette personne dirait \"on est des bêtes\" en mangeant un saucisson ?",
    "À quel point cette personne porterait un bob à carreaux en festival ?",
    "À quel point cette personne ferait un karaoké Goldman seule chez sa belle-mère ?",
    "À quel point cette personne aurait un autocollant \"Bébé à bord\" sans bébé ?",
  ],
  dark: [
    "À quel point cette personne survivrait 5 minutes dans un film catastrophe ?",
    "À quel point cette personne appuierait sur le mauvais bouton ?",
    "À quel point cette personne provoquerait accidentellement une apocalypse ?",
    "À quel point cette personne serait suspecte dans une enquête ?",
    "À quel point cette personne serait le premier mort dans une série Netflix ?",
    "À quel point cette personne cacherait un corps “mal” ?",
    "À quel point cette personne ferait confiance au mauvais personnage ?",
    "À quel point cette personne ouvrirait la porte interdite ?",
    "À quel point cette personne vendrait ses amis pour survivre ?",
    "À quel point cette personne exploserait un laboratoire ?",
    "À quel point cette personne déclencherait une alarme inutilement ?",
    "À quel point cette personne survivrait à Saw ?",
    "À quel point cette personne finirait dans une secte ?",
    "À quel point cette personne croirait un gourou TikTok ?",
    "À quel point cette personne serait capable de créer un culte ?",
    "À quel point cette personne testerait un produit expérimental ?",
    "À quel point cette personne lirait un livre maudit ?",
    "À quel point cette personne ferait confiance à une IA bizarre ?",
    "À quel point cette personne appellerait un démon “pour voir” ?",
    "À quel point cette personne serait capable de provoquer le chaos mondial ?",
    "À quel point cette personne ferait un pacte avec un PDG louche pour 1 million ?",
    "À quel point cette personne ferait une expérience sociale dangereuse pour la story ?",
    "À quel point cette personne ferait un prank trop loin sur un proche ?",
    "À quel point cette personne déclencherait un drama familial volontaire ?",
    "À quel point cette personne signerait un contrat sans lire ?",
    "À quel point cette personne ferait un test ADN qui révèle un secret ?",
    "À quel point cette personne fonderait un faux courant philosophique ?",
    "À quel point cette personne piquerait l'idée d'un proche pour la rendre virale ?",
    "À quel point cette personne deviendrait le bras droit d'un mégalomane ?",
    "À quel point cette personne s'allierait avec le \"méchant\" du film ?",
    "À quel point cette personne ferait un blackmail pour de mauvaises raisons ?",
    "À quel point cette personne ferait un montage trompeur en story ?",
  ],
  random: [
    "À quel point cette personne parlerait seule ?",
    "À quel point cette personne survivrait dans IKEA la nuit ?",
    "À quel point cette personne lècherait un objet pour 100€ ?",
    "À quel point cette personne deviendrait pirate ?",
    "À quel point cette personne ouvrirait un zoo illégal ?",
    "À quel point cette personne vivrait dans un van sans douche ?",
    "À quel point cette personne finirait dans un meme ?",
    "À quel point cette personne oublierait son propre mariage ?",
    "À quel point cette personne serait capable de devenir gourou ?",
    "À quel point cette personne achèterait une épée décorative ?",
    "À quel point cette personne créerait une théorie du complot ?",
    "À quel point cette personne porterait une cape sérieusement ?",
    "À quel point cette personne se perdrait dans un centre commercial ?",
    "À quel point cette personne deviendrait collectionneur bizarre ?",
    "À quel point cette personne survivrait dans une télé-réalité ?",
    "À quel point cette personne ferait une vidéo “excuses” sur YouTube ?",
    "À quel point cette personne construirait un bunker inutile ?",
    "À quel point cette personne ferait une émission de radio pirate ?",
    "À quel point cette personne ouvrirait un café à thème ours en peluche ?",
    "À quel point cette personne adopterait un poulpe ?",
    "À quel point cette personne se réveillerait dans un autre pays sans souvenir ?",
    "À quel point cette personne ferait passer un faux casting d'émission télé pour la blague ?",
    "À quel point cette personne croirait à 100 % à un faux concours ?",
    "À quel point cette personne fonderait un fan club Twitter pour un perso obscur ?",
    "À quel point cette personne lancerait un podcast sur ses ex ?",
    "À quel point cette personne organiserait un voyage sans destination claire ?",
    "À quel point cette personne signerait un livre sur sa vie sans rien avoir vécu ?",
    "À quel point cette personne ferait du wingsuit sans entraînement ?",
    "À quel point cette personne ouvrirait un compte Etsy pour des bougies bizarres ?",
    "À quel point cette personne ferait une fresque géante chez un voisin sans permission ?",
  ],
  hot: [
    "À quel point cette personne enverrait un message à son ex à 2h du matin ?",
    "À quel point cette personne tomberait amoureuse après une soirée ?",
    "À quel point cette personne ferait semblant d’être détachée ?",
    "À quel point cette personne aurait un “crush interdit” ?",
    "À quel point cette personne flirterait juste pour le fun ?",
    "À quel point cette personne serait dangereuse en date ?",
    "À quel point cette personne embrasserait quelqu’un en soirée ?",
    "À quel point cette personne ferait durer la tension volontairement ?",
    "À quel point cette personne regarderait quelqu’un avec insistance ?",
    "À quel point cette personne resterait obsédée par un crush qui ne répond pas ?",
    "À quel point cette personne tomberait dans une relation toxique ?",
    "À quel point cette personne ferait un move impulsif ?",
    "À quel point cette personne deviendrait jalouse sans raison ?",
    "À quel point cette personne lirait les anciens messages d’un ex ?",
    "À quel point cette personne tomberait pour un énorme red flag ?",
    "À quel point cette personne ghosterait quelqu’un après un date ?",
    "À quel point cette personne ferait croire qu’elle s’en fout ?",
    "À quel point cette personne aurait une double vie sentimentale ?",
    "À quel point cette personne enfermerait ses émotions au lieu d'en parler ?",
    "À quel point cette personne ferait une déclaration bourrée ?",
    "À quel point cette personne ferait un date catastrophique ?",
    "À quel point cette personne séduirait quelqu’un sans le vouloir ?",
    "À quel point cette personne serait impossible à comprendre sentimentalement ?",
    "À quel point cette personne serait un énorme flirt ambulant ?",
    "À quel point cette personne ferait une story destinée à UNE personne ?",
    "À quel point cette personne finirait dans un drama amoureux monumental ?",
    "À quel point cette personne tomberait pour un message vocal sensuel ?",
    "À quel point cette personne ferait un soft launch raté avec demi-visage ?",
    "À quel point cette personne accepterait un coup de soir sans demander un prénom ?",
    "À quel point cette personne ramènerait quelqu'un de Hinge à la maison sans prévenir la coloc ?",
    "À quel point cette personne resterait dans un situationship trois ans pour la vibes ?",
    "À quel point cette personne romantiserait un crush parasocial ?",
    "À quel point cette personne dragerait au bureau juste pour le sport ?",
    "À quel point cette personne ferait un duo karaoké chargé de tension avec son crush ?",
    "À quel point cette personne mélangerait amour et coup d'un soir sans assumer ?",
    "À quel point cette personne se ferait pieger par un compliment basique ?",
    "À quel point cette personne ressentirait une attraction immédiate pour un mauvais profil ?",
    "À quel point cette personne tenterait une opération séduction au sport ?",
  ],
  trash: [
    "À quel point cette personne lancerait une rumeur sans faire exprès ?",
    "À quel point cette personne créerait un drama en soirée ?",
    "À quel point cette personne mentirait pour éviter les problèmes ?",
    "À quel point cette personne ferait semblant d’être sobre ?",
    "À quel point cette personne oublierait ce qu’elle a fait la veille ?",
    "À quel point cette personne provoquerait une embrouille ?",
    "À quel point cette personne ferait un scandale en public ?",
    "À quel point cette personne volerait des nuggets à ses amis ?",
    "À quel point cette personne parlerait trop une fois bourrée ?",
    "À quel point cette personne finirait virale pour une mauvaise raison ?",
    "À quel point cette personne enverrait un screenshot au mauvais groupe ?",
    "À quel point cette personne ferait semblant d’être malade ?",
    "À quel point cette personne manipulerait une situation ?",
    "À quel point cette personne ferait un move extrêmement gênant ?",
    "À quel point cette personne serait capable de tout nier malgré les preuves ?",
    "À quel point cette personne finirait bannie d’un groupe ?",
    "À quel point cette personne ferait semblant de ne pas connaître quelqu’un ?",
    "À quel point cette personne déclencherait une catastrophe mineure ?",
    "À quel point cette personne ferait une scène dans un fast-food ?",
    "À quel point cette personne serait capable de disparaître 2 jours sans prévenir ?",
    "À quel point cette personne survivrait dans une télé-réalité trash ?",
    "À quel point cette personne créerait un faux compte pour stalker ?",
    "À quel point cette personne lancerait “un dernier verre” qui détruit la soirée ?",
    "À quel point cette personne se filmerait en direct au pire moment ?",
    "À quel point cette personne mentirait sur un détail inutile ?",
    "À quel point cette personne provoquerait le chaos sans le vouloir ?",
    "À quel point cette personne ferait une confession catastrophique ?",
    "À quel point cette personne ruinerait un secret en 10 secondes ?",
    "À quel point cette personne créerait un drama de couple ?",
    "À quel point cette personne serait “le problème” du groupe ?",
    "À quel point cette personne mettrait un screenshot de DM dans une story \"par erreur\" ?",
    "À quel point cette personne lancerait un \"qui sait\" en pleine soirée pour faire péter un secret ?",
    "À quel point cette personne ferait un live spontané chez son ex ?",
    "À quel point cette personne ferait passer un mensonge énorme pour faire avancer un drama ?",
    "À quel point cette personne tenterait un coup bas pour gagner un jeu de société ?",
    "À quel point cette personne se ferait clasher en story par un proche ?",
    "À quel point cette personne traînerait un drama jusqu'à un dîner pro ?",
    "À quel point cette personne se ferait pieger en relayant un cancan ?",
    "À quel point cette personne retournerait sa veste devant tout le groupe ?",
    "À quel point cette personne ferait un faux compte pour insulter quelqu'un anonymement ?",
    "À quel point cette personne casserait l'ambiance d'un mariage par jalousie ?",
    "À quel point cette personne deviendrait le sujet d'un thread Twitter haineux ?",
  ],
};

export const JAUGE_QUESTIONS: JaugeQuestion[] = Object.entries(RAW_JAUGE_QUESTIONS).flatMap(
  ([category, questions], categoryIndex) =>
    questions.map((text, questionIndex) => ({
      id: 50000 + categoryIndex * 1000 + questionIndex + 1,
      gameType: "jauge" as const,
      category: category as JaugeCategory,
      text,
    }))
);
