// Dataset issu de Majorité.md, partagé par les modes Majorité et Minorité.

export type MajorityCategory =
  | "food"
  | "internet"
  | "party"
  | "gaming"
  | "relationships"
  | "work"
  | "travel"
  | "opinions"
  | "chaos"
  | "rapid"
  | "spicy"
  | "beauf"
  | "genz";

export interface MajorityCategoryMeta {
  id: MajorityCategory;
  label: string;
  emoji: string;
  description: string;
  adult: boolean;
}

export interface MajorityQuestion {
  id: number;
  category: MajorityCategory;
  text: string;
  options: string[];
}

export const MAJORITY_CATEGORIES: MajorityCategoryMeta[] = [
  { id: "food", label: "Food", emoji: "🍟", adult: false, description: "Fast-food, snacks et débats de table." },
  { id: "internet", label: "Internet", emoji: "📱", adult: false, description: "Apps, mèmes et habitudes en ligne." },
  { id: "party", label: "Soirée", emoji: "🎉", adult: false, description: "Ambiance, invités et chaos collectif." },
  { id: "gaming", label: "Gaming", emoji: "🎮", adult: false, description: "Jeux, ragequit et multiplayer." },
  { id: "relationships", label: "Relations", emoji: "💬", adult: false, description: "Dates, messages et red flags." },
  { id: "work", label: "Études / travail", emoji: "📚", adult: false, description: "Profs, collègues et excuses éclatées." },
  { id: "travel", label: "Voyage", emoji: "✈️", adult: false, description: "Vacances, transports et galères." },
  { id: "opinions", label: "Opinions", emoji: "⚡", adult: false, description: "Petites polémiques du quotidien." },
  { id: "chaos", label: "Chaos", emoji: "🌀", adult: false, description: "Absurde, objets inutiles et pouvoirs nuls." },
  { id: "rapid", label: "Bonus rapides", emoji: "⏱️", adult: false, description: "Questions immédiates pour mode ultra rapide." },
  { id: "spicy", label: "Spicy", emoji: "🌶️", adult: true, description: "Tabous, dating apps et débats 18+." },
  { id: "beauf", label: "Beauf", emoji: "🍻", adult: false, description: "Apéro, BBQ et France profonde." },
  { id: "genz", label: "Gen Z", emoji: "🧠", adult: false, description: "Brainrot, slang et chaos digital." },
];

export const MAJORITY_QUESTIONS: MajorityQuestion[] = [
  { id: 20001, category: "food", text: "Le meilleur fast-food ?", options: ["McDo", "Burger King", "KFC", "Subway"] },
  { id: 20002, category: "food", text: "Le pire fast-food à 3h du matin ?", options: ["Taco Bell", "Kebab douteux", "Burger froid", "Sandwich triangle"] },
  { id: 20003, category: "food", text: "Le meilleur dessert ?", options: ["Tiramisu", "Fondant chocolat", "Cheesecake", "Crêpes"] },
  { id: 20004, category: "food", text: "Le pire légume ?", options: ["Choux de Bruxelles", "Endives", "Céleri", "Betterave"] },
  { id: 20005, category: "food", text: "Le meilleur snack devant un film ?", options: ["Pop-corn", "Chips", "Pizza", "Bonbons"] },
  { id: 20006, category: "food", text: "Le pire goût de chips ?", options: ["Vinaigre", "Pickles", "Ketchup", "Nature"] },
  { id: 20007, category: "food", text: "Le meilleur soda ?", options: ["Coca", "Ice Tea", "Fanta", "Sprite"] },
  { id: 20008, category: "food", text: "Le pire aliment à sentir ?", options: ["Maroilles", "Surströmming", "Thon chaud", "Œuf dur"] },
  { id: 20009, category: "food", text: "Le meilleur repas de lendemain de soirée ?", options: ["Kebab", "Burger", "Pâtes", "Pizza"] },
  { id: 20010, category: "food", text: "Ce qu'on commande le plus en livraison ?", options: ["Pizza", "Sushi", "Burger", "Tacos"] },
  { id: 20011, category: "food", text: "Le meilleur goût de glace ?", options: ["Vanille", "Chocolat", "Pistache", "Fraise"] },
  { id: 20012, category: "food", text: "Le pire mélange alimentaire ?", options: ["Pizza-ananas", "Frites-glace", "Lait-orange", "Mayo-pâtes"] },
  { id: 20013, category: "food", text: "Le meilleur petit-déjeuner ?", options: ["Viennoiseries", "Pancakes", "Céréales", "Œufs bacon"] },
  { id: 20014, category: "food", text: "Le pire plat de cantine ?", options: ["Poisson pané", "Purée grise", "Haricots mous", "Raviolis froids"] },
  { id: 20015, category: "food", text: "Le meilleur type de pâtes ?", options: ["Carbonara", "Bolognaise", "Pesto", "4 fromages"] },
  { id: 20016, category: "food", text: "Le pire bonbon ?", options: ["Réglisse", "Banane chimique", "Dragibus noir", "Menthe forte"] },
  { id: 20017, category: "food", text: "Ce qu'on pourrait manger tous les jours ?", options: ["Pizza", "Pâtes", "Sushi", "Tacos"] },
  { id: 20018, category: "food", text: "Le meilleur chocolat ?", options: ["Noir", "Lait", "Blanc", "Noisette"] },

  { id: 20101, category: "internet", text: "L'application la plus addictive ?", options: ["TikTok", "Instagram", "YouTube", "X/Twitter"] },
  { id: 20102, category: "internet", text: "Le pire réseau social ?", options: ["Facebook", "Snapchat", "TikTok", "LinkedIn"] },
  { id: 20103, category: "internet", text: "Le pire emoji ?", options: ["😂", "😭", "🤡", "👍"] },
  { id: 20104, category: "internet", text: "L'application la plus ouverte automatiquement ?", options: ["Instagram", "TikTok", "Messages", "YouTube"] },
  { id: 20105, category: "internet", text: "Le pire spam de groupe ?", options: ["?", "Vu", "Sticker random", "Vocal de 3 minutes"] },
  { id: 20106, category: "internet", text: "Le meilleur contenu YouTube ?", options: ["Documentaires", "Gaming", "Podcasts", "True crime"] },
  { id: 20107, category: "internet", text: "Le pire son TikTok ?", options: ["Remix accéléré", "Voix IA", "Techno saturée", "Oh no"] },
  { id: 20108, category: "internet", text: "Ce qu'on regarde tous sans assumer ?", options: ["Télé-réalité", "ASMR", "Drama TikTok", "Mukbang"] },
  { id: 20109, category: "internet", text: "Le réseau social le plus toxique ?", options: ["Twitter/X", "TikTok", "Reddit", "Facebook"] },
  { id: 20110, category: "internet", text: "Le meilleur type de meme ?", options: ["Absurde", "Dark humor", "Animaux", "Références gaming"] },
  { id: 20111, category: "internet", text: "Le pire commentaire internet ?", options: ["Premier", "Ratio", "Qui regarde en 2026 ?", "Fake"] },
  { id: 20112, category: "internet", text: "Ce qu'on fait tous sur internet ?", options: ["Stalker des profils", "Lire les commentaires", "Scroller 2h sans raison", "Oublier pourquoi on a ouvert l'app"] },

  { id: 20201, category: "party", text: "Le pire comportement en soirée ?", options: ["Casser l'ambiance", "Vomir partout", "Monopoliser l'enceinte", "Disparaître"] },
  { id: 20202, category: "party", text: "Le meilleur jeu de soirée ?", options: ["Beer pong", "Loups-garous", "Jungle Speed", "Action vérité"] },
  { id: 20203, category: "party", text: "Celui qui finit toujours trop alcoolisé ?", options: ["Le discret", "Le plus bruyant", "Celui qui mélange tout", "Celui qui boit vite"] },
  { id: 20204, category: "party", text: "Le pire son pour lancer une soirée ?", options: ["Techno agressive", "Musique triste", "Remix bizarre", "Hardstyle à fond"] },
  { id: 20205, category: "party", text: "Ce qui tue immédiatement l'ambiance ?", options: ["Coupure musique", "Dispute", "Police", "Téléphone aux parents"] },
  { id: 20206, category: "party", text: "Le meilleur snack de fin de soirée ?", options: ["Tacos", "Pizza froide", "Nouilles instantanées", "McDo"] },
  { id: 20207, category: "party", text: "Le pire voisin de soirée ?", options: ["Celui qui appelle les flics", "Celui qui regarde par la fenêtre", "Celui qui se plaint tout le temps", "Celui qui rejoint sans invitation"] },
  { id: 20208, category: "party", text: "Le meilleur duo alcool + soft ?", options: ["Vodka Red Bull", "Rhum Coca", "Gin tonic", "Whisky Coca"] },
  { id: 20209, category: "party", text: "Ce qu'on regrette le plus le lendemain ?", options: ["Les messages", "Les stories", "Les dépenses", "Les shots de trop"] },
  { id: 20210, category: "party", text: "Le pire invité ?", options: ["Celui qui juge tout", "Celui qui casse des trucs", "Celui qui dort sur place", "Celui qui drague tout le monde"] },

  { id: 20301, category: "gaming", text: "Le jeu le plus rageant ?", options: ["FIFA", "League of Legends", "Call of Duty", "Mario Kart"] },
  { id: 20302, category: "gaming", text: "Le meilleur jeu multijoueur ?", options: ["Minecraft", "GTA Online", "Fortnite", "Valorant"] },
  { id: 20303, category: "gaming", text: "Le pire teammate ?", options: ["AFK", "Rageux", "Micro ouvert", "Troll"] },
  { id: 20304, category: "gaming", text: "Le jeu qui détruit le plus les amitiés ?", options: ["Mario Party", "Monopoly", "UNO", "LoL"] },
  { id: 20305, category: "gaming", text: "Le meilleur jeu nostalgique ?", options: ["Minecraft", "Wii Sports", "Pokémon", "Mario Kart Wii"] },
  { id: 20306, category: "gaming", text: "Le pire ragequit ?", options: ["Débrancher la console", "Quitter Discord", "Insulter puis partir", "Éteindre le PC"] },
  { id: 20307, category: "gaming", text: "Le meilleur jeu à jouer bourré ?", options: ["Mario Kart", "Gang Beasts", "Fall Guys", "Among Us"] },
  { id: 20308, category: "gaming", text: "Le pire type de gamer ?", options: ["Tryhard toxique", "Smurf", "Camper", "Rageux"] },
  { id: 20309, category: "gaming", text: "Le jeu le plus chronophage ?", options: ["Minecraft", "LoL", "WoW", "GTA RP"] },
  { id: 20310, category: "gaming", text: "Le meilleur boss de jeu vidéo ?", options: ["Dark Souls", "Elden Ring", "Zelda", "God of War"] },

  { id: 20401, category: "relationships", text: "Le pire red flag ?", options: ["Jaloux excessif", "Contrôle le téléphone", "Ne répond jamais", "Ment souvent"] },
  { id: 20402, category: "relationships", text: "Le meilleur green flag ?", options: ["Communication", "Humour", "Gentillesse", "Confiance"] },
  { id: 20403, category: "relationships", text: "Le pire premier date ?", options: ["Malaise total", "Téléphone constant", "Retard énorme", "Silence gênant"] },
  { id: 20404, category: "relationships", text: "Le meilleur lieu pour un date ?", options: ["Restaurant", "Cinéma", "Café", "Balade"] },
  { id: 20405, category: "relationships", text: "Le pire message à recevoir ?", options: ["Faut qu'on parle", "Tu dors ? à 3h", "On reste amis ?", "Vu"] },
  { id: 20406, category: "relationships", text: "Le pire comportement après rupture ?", options: ["Stalker", "Poster des stories tristes", "Revenir bourré", "Supprimer puis rajouter"] },
  { id: 20407, category: "relationships", text: "Le pire profil Tinder ?", options: ["Photos floues", "Bio vide", "Je réponds jamais", "Citation gênante"] },
  { id: 20408, category: "relationships", text: "Le meilleur compliment ?", options: ["Drôle", "Beau/belle", "Intelligent", "Charismatique"] },
  { id: 20409, category: "relationships", text: "Ce qui détruit le plus un couple ?", options: ["Mensonge", "Routine", "Jalousie", "Mauvaise communication"] },
  { id: 20410, category: "relationships", text: "Le pire ghosting ?", options: ["Après plusieurs mois", "Après un date", "Après je t'aime", "Après avoir prévu des vacances"] },

  { id: 20501, category: "work", text: "Le pire prof ?", options: ["Celui qui lit le diapo", "Celui qui humilie", "Celui qui parle trop bas", "Celui qui donne trop de devoirs"] },
  { id: 20502, category: "work", text: "La pire excuse de retard ?", options: ["Réveil cassé", "Bus raté", "Chat malade", "J'ai oublié"] },
  { id: 20503, category: "work", text: "Le pire collègue ?", options: ["Faux sympa", "Bruyant", "Fainéant", "Donneur de leçons"] },
  { id: 20504, category: "work", text: "Le pire jour de la semaine ?", options: ["Lundi", "Mardi", "Jeudi", "Dimanche soir"] },
  { id: 20505, category: "work", text: "La pire matière scolaire ?", options: ["Maths", "Philo", "Histoire", "Physique"] },
  { id: 20506, category: "work", text: "Le meilleur métier de rêve ?", options: ["Streamer", "Entrepreneur", "Pilote", "Voyageur pro"] },
  { id: 20507, category: "work", text: "Ce qu'on oublie toujours avant un examen ?", options: ["Carte étudiante", "Stylo", "Calculatrice", "Réviser un chapitre"] },
  { id: 20508, category: "work", text: "Le pire open-space ?", options: ["Bruyant", "Sans fenêtres", "Trop lumineux", "Trop petit"] },

  { id: 20601, category: "travel", text: "Le pire siège dans un avion ?", options: ["Milieu", "Fond", "Devant toilettes", "Sans hublot"] },
  { id: 20602, category: "travel", text: "Le pire voisin de transport ?", options: ["Celui qui parle fort", "Celui qui mange fort", "Celui qui prend toute la place", "Celui qui sent mauvais"] },
  { id: 20603, category: "travel", text: "Le meilleur type de vacances ?", options: ["Plage", "Roadtrip", "Ville", "Montagne"] },
  { id: 20604, category: "travel", text: "Le pire Airbnb ?", options: ["Sale", "Minuscule", "Bruyant", "Pas conforme aux photos"] },
  { id: 20605, category: "travel", text: "Ce qu'on oublie le plus en voyage ?", options: ["Chargeur", "Brosse à dents", "Passeport", "Sous-vêtements"] },
  { id: 20606, category: "travel", text: "Le meilleur moyen de transport ?", options: ["Avion", "Train", "Voiture", "Van"] },
  { id: 20607, category: "travel", text: "Le pire touriste ?", options: ["Bruyant", "Impoli", "Influenceur", "Celui qui se plaint"] },
  { id: 20608, category: "travel", text: "Le meilleur pays pour manger ?", options: ["Italie", "Japon", "France", "Mexique"] },

  { id: 20701, category: "opinions", text: "L'ananas sur la pizza ?", options: ["Excellent", "Acceptable", "Crime", "Dépend du mood"] },
  { id: 20702, category: "opinions", text: "Dormir avec des chaussettes ?", options: ["Oui", "Non", "Seulement l'hiver", "Psychopathe"] },
  { id: 20703, category: "opinions", text: "Les gens qui applaudissent dans l'avion ?", options: ["Normaux", "Gênants", "Drôles", "Inutiles"] },
  { id: 20704, category: "opinions", text: "Pain au chocolat ou chocolatine ?", options: ["Pain au chocolat", "Chocolatine", "Les deux", "Peu importe"] },
  { id: 20705, category: "opinions", text: "Les vocaux de plus de 2 minutes ?", options: ["Acceptables", "Horribles", "Ça dépend", "Jamais"] },
  { id: 20706, category: "opinions", text: "Le téléphone à table ?", options: ["Normal", "Impoli", "Dépend du contexte", "Tout le monde le fait"] },
  { id: 20707, category: "opinions", text: "Dormir avec la télé ?", options: ["Relaxant", "Impossible", "Bruyant", "Dépend de la fatigue"] },
  { id: 20708, category: "opinions", text: "Les spoilers involontaires ?", options: ["Grave", "Pas si grave", "Drôle", "Impardonnable"] },
  { id: 20709, category: "opinions", text: "Regarder une série déjà vue ?", options: ["Réconfortant", "Perte de temps", "Dépend de la série", "Toujours oui"] },
  { id: 20710, category: "opinions", text: "Les gens qui marchent lentement ?", options: ["Insupportables", "Relax", "Normaux", "Stressants"] },

  { id: 20801, category: "chaos", text: "Le meilleur objet dans une apocalypse ?", options: ["Briquet", "Couteau", "Gourde", "Vélo"] },
  { id: 20802, category: "chaos", text: "Le pire super-pouvoir ?", options: ["Lire les pensées en permanence", "Être invisible mais nu", "Voler très lentement", "Parler aux poissons"] },
  { id: 20803, category: "chaos", text: "Le meilleur talent inutile ?", options: ["Imiter des sons", "Équilibrer des objets", "Siffler fort", "Faire tourner un stylo"] },
  { id: 20804, category: "chaos", text: "Le pire déguisement possible ?", options: ["Bébé géant", "Hot-dog", "Clown triste", "Dinosaure gonflable"] },
  { id: 20805, category: "chaos", text: "Le pire endroit pour rester bloqué ?", options: ["Ascenseur", "Toilettes publiques", "Téléphérique", "IKEA"] },
  { id: 20806, category: "chaos", text: "Le meilleur objet inutile ?", options: ["Mini ventilateur USB", "Lampe RGB", "Katana décoratif", "Casque LED"] },
  { id: 20807, category: "chaos", text: "Le pire pouvoir magique ?", options: ["Voir 5 secondes dans le futur", "Transformer l'eau en jus tiède", "Parler aux moustiques", "Faire pousser l'herbe plus vite"] },
  { id: 20808, category: "chaos", text: "Le pire achat impulsif ?", options: ["Crypto douteuse", "Épée décorative", "Machine à barbe à papa", "NFT"] },

  { id: 20901, category: "rapid", text: "Le meilleur type de météo ?", options: ["Soleil", "Orage", "Neige", "Pluie légère"] },
  { id: 20902, category: "rapid", text: "Le pire réveil du matin ?", options: ["Alarme agressive", "Appel", "Chantier", "Chien qui aboie"] },
  { id: 20903, category: "rapid", text: "Le meilleur animal domestique ?", options: ["Chien", "Chat", "Lapin", "Oiseau"] },
  { id: 20904, category: "rapid", text: "Le pire bruit ?", options: ["Craie tableau", "Bébé qui pleure", "Alarme incendie", "Moustique la nuit"] },
  { id: 20905, category: "rapid", text: "Le meilleur film à revoir ?", options: ["Harry Potter", "Interstellar", "Shrek", "Le Seigneur des Anneaux"] },
  { id: 20906, category: "rapid", text: "Le pire comportement au cinéma ?", options: ["Téléphone lumineux", "Parler fort", "Donner des spoilers", "Manger bruyamment"] },
  { id: 20907, category: "rapid", text: "Le meilleur type de soirée ?", options: ["Chill", "Grosse fête", "Jeux de société", "Bar"] },
  { id: 20908, category: "rapid", text: "Le pire achat inutile ?", options: ["Gadget TikTok", "Lampe RGB", "Objet AliExpress", "Abonnement oublié"] },
  { id: 20909, category: "rapid", text: "Le meilleur feeling ?", options: ["Fin des examens", "Douche après sport", "Lit propre", "Salaire reçu"] },
  { id: 20910, category: "rapid", text: "Le pire feeling ?", options: ["Message faut qu'on parle", "Réveil lundi matin", "Batterie à 1%", "Internet coupé"] },

  // Vague d'enrichissement 2026 — questions polarisantes pour majorité ET minorité.
  { id: 21001, category: "food", text: "Le sandwich qui sauve le plus une journée ?", options: ["Jambon-beurre", "Kebab", "Wrap poulet", "Bagel saumon"] },
  { id: 21002, category: "food", text: "La pire texture en bouche ?", options: ["Champignon visqueux", "Aspic gélatineux", "Banane trop mûre", "Yaourt nature glacé"] },
  { id: 21003, category: "food", text: "L'aliment qu'on commande mais qu'on aime jamais autant que la photo ?", options: ["Salade resto", "Bowl healthy", "Pizza luxe", "Burger gastronomique"] },
  { id: 21004, category: "food", text: "Le snack régressif numéro 1 ?", options: ["Curly", "Pims", "Mister Freeze", "Petit Lu"] },
  { id: 21005, category: "food", text: "Le plat impossible à finir seul ?", options: ["Plateau sushis 60", "Tacos 5 viandes XXL", "Plateau de fromage", "Pizza familiale"] },
  { id: 21006, category: "food", text: "Le pire condiment en quantité industrielle ?", options: ["Mayonnaise", "Ketchup", "Sauce algérienne", "Moutarde forte"] },
  { id: 21007, category: "food", text: "La meilleure street food à 4h du matin ?", options: ["Tacos sauce blanche", "Kebab", "Pizza part géante", "Hot dog station"] },
  { id: 21008, category: "food", text: "Le brunch qui vaut vraiment 28 € ?", options: ["Avocado toast", "Pancakes sirop", "Eggs benedict", "Granola bowl"] },
  { id: 21009, category: "food", text: "Le combo douteux que tu testerais ?", options: ["Frites + lait", "Œuf au plat sur kebab", "Glace vanille + soupe miso", "Chocolat blanc + pickles"] },
  { id: 21010, category: "food", text: "Le pire fail cantine encore traumatisant ?", options: ["Lasagnes liquides", "Pavé saumon vert", "Steak haché caoutchouteux", "Tartare au déjeuner"] },
  { id: 21011, category: "food", text: "Le café qui te garde en vie ?", options: ["Espresso double", "Iced latte", "Filtre américain", "Mocha sucré"] },
  { id: 21012, category: "food", text: "Le pire ajout à une raclette ?", options: ["Ananas", "Sauce piquante", "Poisson pané", "Sushis"] },
  { id: 21013, category: "food", text: "Le dessert qui calme un cœur brisé ?", options: ["Ben & Jerry's", "Fondant chocolat", "Tarte citron", "Cheesecake speculoos"] },
  { id: 21014, category: "food", text: "Le snack qu'on cache à ses potes ?", options: ["Bonbons gélifiés", "Carambar", "Curly grand format", "Chocolat Kinder"] },
  { id: 21015, category: "food", text: "La boisson qui révèle ta vraie personnalité ?", options: ["Matcha latte", "Coca zéro", "Bière artisanale", "Verre d'eau du robinet"] },
  { id: 21016, category: "food", text: "L'aliment surcôté de tous les temps ?", options: ["Avocat", "Kale", "Truffe", "Quinoa"] },
  { id: 21017, category: "food", text: "Le repas le plus efficace après une nuit blanche ?", options: ["Big Mac menu", "Bo bun", "Œufs brouillés bacon", "Croque-monsieur cantine"] },

  { id: 21101, category: "internet", text: "L'app qui mérite la fermeture publique ?", options: ["Twitter/X", "TikTok", "Reddit", "Snapchat"] },
  { id: 21102, category: "internet", text: "La pire fonctionnalité créée par les réseaux ?", options: ["Stories", "Coeurs sur Twitter", "BeReal notif", "Statut LinkedIn"] },
  { id: 21103, category: "internet", text: "L'app qu'on télécharge et qu'on ouvre jamais ?", options: ["LinkedIn", "Threads", "Goodreads", "Mastodon"] },
  { id: 21104, category: "internet", text: "Le contenu qu'on regarde en cachette ?", options: ["Drama TikTok", "Tea YouTube", "Reels couples cringe", "Fights Twitter"] },
  { id: 21105, category: "internet", text: "Le format qui pollue le plus une feed ?", options: ["AI slop", "Pubs forcées", "Self-promo", "Vidéos ASMR mukbang"] },
  { id: 21106, category: "internet", text: "Le pire emoji passif-agressif ?", options: ["🙂", "👍", "🤝", "🥲"] },
  { id: 21107, category: "internet", text: "L'app qui finira par mourir en premier ?", options: ["BeReal", "Threads", "X", "Snapchat"] },
  { id: 21108, category: "internet", text: "Le moment cringe d'internet qu'on aimerait oublier ?", options: ["Vine 2014", "Memes Facebook 2010", "TikTok 2020", "Reels couples 2023"] },
  { id: 21109, category: "internet", text: "L'algorithme qui te connaît le mieux ?", options: ["TikTok", "YouTube", "Spotify", "Insta"] },
  { id: 21110, category: "internet", text: "Le style de tweet le plus polluant ?", options: ["Threads à rallonge", "Tweet quote ironique", "Cours TED en 60 tweets", "Rage bait"] },
  { id: 21111, category: "internet", text: "Le réseau qu'on stalke en mode privé ?", options: ["Insta", "LinkedIn", "TikTok", "Spotify"] },
  { id: 21112, category: "internet", text: "Le contenu qui plombe ton For You ?", options: ["Trad masculinity", "Hyper féminité", "Crypto pumps", "Self-help bro"] },
  { id: 21113, category: "internet", text: "Le \"new feature\" qui ruine direct l'app ?", options: ["IG sans like", "TikTok long format", "Reels Spotify", "X paid checkmark"] },
  { id: 21114, category: "internet", text: "L'option dont on rêve dans les apps ?", options: ["Cacher ses likes", "Planifier ses messages", "Voir ses stalkers", "Désactiver la pub"] },
  { id: 21115, category: "internet", text: "Le type de pub qui te fait fermer l'app ?", options: ["AI slop", "Crypto bros", "Onlyfans détourné", "Chats qui dansent"] },
  { id: 21116, category: "internet", text: "L'app qu'on ouvre par réflexe quand on s'ennuie ?", options: ["Insta", "TikTok", "YouTube", "Reddit"] },
  { id: 21117, category: "internet", text: "Le lien le plus dangereux ?", options: ["DM d'un inconnu", "Promo \"vous avez gagné\"", "Mail SAV bizarre", "Pop-up streaming"] },

  { id: 21201, category: "party", text: "Le moment où tout part en vrille en soirée ?", options: ["Le shot de trop", "Le mauvais SMS envoyé", "Le voisin qui sonne", "Le karaoké forcé"] },
  { id: 21202, category: "party", text: "La pire ambiance d'after ?", options: ["Silence total", "Tristesse collective", "Disputes idéologiques", "Ex qui débarquent"] },
  { id: 21203, category: "party", text: "La meilleure entrée en soirée ?", options: ["Avec un pack inattendu", "Avec une story qui annonce", "En plein milieu, au calme", "Avec un musicien improvisé"] },
  { id: 21204, category: "party", text: "Le meilleur cocktail communautaire ?", options: ["Sangria", "Tropical bowl", "Spritz géant", "Punch maison"] },
  { id: 21205, category: "party", text: "Le pire après-soirée ?", options: ["Vomi cuvette", "Mal de crâne sec", "Anxiété morale", "Toilettes en panne"] },
  { id: 21206, category: "party", text: "La pire raison d'arrêter une soirée ?", options: ["Police", "Voisin furieux", "Plus de musique", "Plus d'alcool"] },
  { id: 21207, category: "party", text: "Le cocktail qui te trahit le plus ?", options: ["Mojito", "Tequila sunrise", "Rhum coca", "Espresso martini"] },
  { id: 21208, category: "party", text: "Le pire jeu de soirée raté ?", options: ["Action vérité", "Time's Up", "Beer pong", "Loups-garous"] },
  { id: 21209, category: "party", text: "L'invité qui sauve toujours la soirée ?", options: ["Le DJ improvisé", "Le bon dealer de boissons", "Le drôle qui détend", "Le couple stable"] },
  { id: 21210, category: "party", text: "Le pire moment d'une fête ?", options: ["Dispute couple en public", "Pleurs aux toilettes", "Bagarre entre potes", "Tatouage improvisé"] },
  { id: 21211, category: "party", text: "Ce qui détruit ton lendemain de soirée ?", options: ["Mélange spiritueux", "Manque de bouffe", "Coucher trop tard", "Stress morning"] },
  { id: 21212, category: "party", text: "La meilleure team de soirée ?", options: ["Bons buveurs", "Chefs cuistots", "DJs improvisés", "Calmes qui veillent"] },
  { id: 21213, category: "party", text: "Le pire mot de fin de soirée ?", options: ["\"Un dernier verre\"", "\"C'est offert\"", "\"On se rappelle demain\"", "\"On va manger\""] },
  { id: 21214, category: "party", text: "L'attribut indispensable de la soirée parfaite ?", options: ["Ambiance musicale", "Boissons à volonté", "Bons potes", "Endroit sans voisins"] },

  { id: 21301, category: "gaming", text: "L'archétype de joueur le plus toxique ?", options: ["Tryhard ranked", "Camper passif", "Chat troll", "Smurf en silver"] },
  { id: 21302, category: "gaming", text: "Le pire moment dans un game compétitif ?", options: ["Dico 0-12 en finale", "Lag spike final", "Teammate AFK", "Coupure de courant"] },
  { id: 21303, category: "gaming", text: "Le meilleur jeu pour reset ses amitiés ?", options: ["Mario Party", "UNO", "Monopoly", "Among Us"] },
  { id: 21304, category: "gaming", text: "Le pire DLC inutile ?", options: ["Skin payant", "Mini map", "Boost XP", "Costume saison"] },
  { id: 21305, category: "gaming", text: "Le meilleur boss de l'histoire ?", options: ["Malenia", "Sephiroth", "Nameless King", "Genichiro"] },
  { id: 21306, category: "gaming", text: "Le jeu le plus buggé jamais sorti ?", options: ["Cyberpunk lancement", "Fallout 76", "Battlefield 2042", "Anthem"] },
  { id: 21307, category: "gaming", text: "Le pire mode multijoueur ?", options: ["Battle royale lent", "Capture du drapeau random", "Casual ranked mix", "Mode mort permanente"] },
  { id: 21308, category: "gaming", text: "Le meilleur jeu pour bourrer un soir ?", options: ["Mario Kart", "Smash Bros", "FIFA", "Gang Beasts"] },
  { id: 21309, category: "gaming", text: "Le pire skip de cinématique ?", options: ["Final Fantasy", "MGS", "Witcher 3", "Mass Effect"] },
  { id: 21310, category: "gaming", text: "Le profil de teammate qui détruit la game ?", options: ["Le rage perma", "Le silencieux passif", "Le micro saturé", "Le boostant cringe"] },
  { id: 21311, category: "gaming", text: "Le meilleur jeu story ?", options: ["The Last of Us", "Red Dead 2", "God of War 2018", "Disco Elysium"] },
  { id: 21312, category: "gaming", text: "L'archétype d'opposant le plus chiant ?", options: ["Camper bushlock", "Sniper invisible", "Smurf chill", "One trick toxic"] },
  { id: 21313, category: "gaming", text: "L'erreur fatale d'un MOBA ?", options: ["Steal du dragon", "Flash sans cooldown", "Tilt après une mort", "Vendre les wards"] },
  { id: 21314, category: "gaming", text: "Le jeu nostalgique qui te ramène en 2008 ?", options: ["Pokémon Or", "Halo 3", "Crash Bandicoot", "Mario 64"] },
  { id: 21315, category: "gaming", text: "Le pire perso à jouer en pleine compé ?", options: ["Ranged squishy", "Healer mute", "Tank stat", "Assassin no positioning"] },

  { id: 21401, category: "relationships", text: "Le red flag invisible numéro 1 ?", options: ["Trop nice", "Aucune passion", "Mauvaise relation famille", "Profil Insta vide"] },
  { id: 21402, category: "relationships", text: "Le green flag underrated ?", options: ["Bonne relation avec ses parents", "Lit des livres", "Chante pas en public", "Aime ses ami(e)s d'enfance"] },
  { id: 21403, category: "relationships", text: "Le pire dating app fail ?", options: ["Bio cringe", "Photos floues", "Ghost après match", "First message inutile"] },
  { id: 21404, category: "relationships", text: "Le scénario de premier date qui foire d'avance ?", options: ["Café à 11h", "Cinéma sans mot dit", "Soirée 4 amis surprise", "Resto chez ses parents"] },
  { id: 21405, category: "relationships", text: "L'erreur fatale au début d'une relation ?", options: ["Stalker IG", "Présenter aux parents trop vite", "Texter trop souvent", "Annuler 3 plans d'affilée"] },
  { id: 21406, category: "relationships", text: "Le pire moment dans un couple ?", options: ["Premier silence post-dispute", "Croisée d'ex en public", "Désaccord financier", "Discussion enfants"] },
  { id: 21407, category: "relationships", text: "L'attente la plus toxique ?", options: ["Téléphone allumé 24/7", "Loyauté insta", "Plans tous les week-ends", "Validation publique"] },
  { id: 21408, category: "relationships", text: "Le langage d'amour le plus surcôté ?", options: ["Cadeaux", "Mots", "Touches", "Service"] },
  { id: 21409, category: "relationships", text: "Le pire timing pour un \"je t'aime\" ?", options: ["Avant le café", "Pendant le sport", "Après une dispute", "Devant la famille"] },
  { id: 21410, category: "relationships", text: "Le geste qui prouve tout ?", options: ["Réveiller en douceur", "Préparer un plat sans demander", "Couvrir avec une couette", "Faire le plein pour l'autre"] },
  { id: 21411, category: "relationships", text: "Le pire ex possible ?", options: ["Le manipulateur", "Le ghosteur", "Le clingy", "Le menteur compulsif"] },
  { id: 21412, category: "relationships", text: "L'origine la plus solide d'une relation ?", options: ["Amis d'enfance", "App de rencontre", "Coup de foudre boîte", "Collègues" ] },
  { id: 21413, category: "relationships", text: "Le pire aveu en couple ?", options: ["\"J'ai liké son insta\"", "\"J'ai dit oui à ses parents\"", "\"J'ai laissé mes ex sur Snap\"", "\"J'ai accepté un date avant nous\""] },
  { id: 21414, category: "relationships", text: "Le moment dad/mum check par excellence ?", options: ["Voiture rangée", "Frigo plein", "Linge plié", "Lit fait au carré"] },

  { id: 21501, category: "work", text: "La pire réunion possible ?", options: ["Brainstorm sans agenda", "Visio en pyjama", "Présentation surprise", "Feedback collectif"] },
  { id: 21502, category: "work", text: "L'archétype de collègue insupportable ?", options: ["Le donneur de leçons", "Le faux pote", "Le lèche-bottes", "Le silencieux qui juge"] },
  { id: 21503, category: "work", text: "L'excuse retard la plus crédible ?", options: ["Bus annulé", "Souci santé", "Téléphone H.S.", "Internet coupé"] },
  { id: 21504, category: "work", text: "Le truc à éviter en visio ?", options: ["Mic ouvert au mauvais moment", "Caméra ouverte sans pantalon", "Manger devant tout le monde", "Réveil tardif"] },
  { id: 21505, category: "work", text: "Le pire partner de TD ?", options: ["Le ghost qui répond pas", "Le control freak", "Le procrastinateur", "Le coach forcé"] },
  { id: 21506, category: "work", text: "La pire question d'entretien ?", options: ["\"Vos défauts ?\"", "\"Vous vous voyez où dans 5 ans ?\"", "\"Pourquoi nous ?\"", "\"Vendez-moi ce stylo\""] },
  { id: 21507, category: "work", text: "L'objet bureau qui sauve la journée ?", options: ["Mug XL", "Plante mascotte", "Casque ANC", "Snacks tiroir"] },
  { id: 21508, category: "work", text: "Le pire mail à recevoir ?", options: ["\"Faut qu'on parle\"", "\"Suite à votre demande\"", "\"Petit rappel\"", "\"Confidentiel\""] },
  { id: 21509, category: "work", text: "Le pire outil de boulot ?", options: ["Outlook", "SAP", "Microsoft Teams", "Confluence" ] },
  { id: 21510, category: "work", text: "Le pire moment d'une journée de boulot ?", options: ["Réunion 17h45", "Mail 23h", "Réunion lundi 9h", "Slack vendredi soir"] },
  { id: 21511, category: "work", text: "L'arme secrète pour briller au boulot ?", options: ["Ponctualité", "Petits déj offerts", "Slack proactif", "Visio caméra ON"] },

  { id: 21601, category: "travel", text: "Le pire compagnon de voyage ?", options: ["Le control freak", "Le toujours fatigué", "Le radin", "Le qui s'éloigne"] },
  { id: 21602, category: "travel", text: "Le pire imprévu en voyage ?", options: ["Bagage perdu", "Vol annulé", "Hôtel sale", "Voisin bruyant"] },
  { id: 21603, category: "travel", text: "Le souvenir qu'on rapporte sans assumer ?", options: ["Aimant frigo cliché", "Snowglobe", "T-shirt logo", "Magnet ville"] },
  { id: 21604, category: "travel", text: "Le pire lieu pour camper ?", options: ["Sous un pont", "Près d'une autoroute", "Au pied d'une montagne pluvieuse", "Sur une plage à marée"] },
  { id: 21605, category: "travel", text: "La pire compagnie aérienne low cost ?", options: ["Ryanair", "Wizzair", "Easyjet", "Volotea"] },
  { id: 21606, category: "travel", text: "Le pire transport en ville ?", options: ["Métro samedi soir", "Bus rush hour", "VLib en panne", "Trottinette louée H.S."] },
  { id: 21607, category: "travel", text: "Le meilleur souvenir voyage cliché ?", options: ["Coucher soleil plage", "Photo Tour Eiffel", "Selfie monument inscrit", "Carte postale envoyée"] },
  { id: 21608, category: "travel", text: "L'erreur classique de voyage ?", options: ["Oublier passeport", "Réserver mauvaise date", "Trop de bagages", "Oublier la prise"] },
  { id: 21609, category: "travel", text: "Le pire restaurant en voyage ?", options: ["Touristique central", "Caché obligatoire", "All-inclusive resort", "Buffet hôtel"] },
  { id: 21610, category: "travel", text: "Le pays surcôté ?", options: ["Bali", "Dubai", "Islande", "Maldives"] },
  { id: 21611, category: "travel", text: "Le pays sous-côté ?", options: ["Albanie", "Géorgie", "Slovénie", "Pologne"] },

  { id: 21701, category: "opinions", text: "L'opinion impopulaire la plus défendable ?", options: ["Pizza ananas valide", "Pas de pourboire en France", "Bain plus efficace que douche", "Lundi pas si pire"] },
  { id: 21702, category: "opinions", text: "Le débat qui ne finit jamais ?", options: ["Pain au chocolat / chocolatine", "Ananas pizza", "Toilettes ouvertes ou fermées", "Lait avant céréales"] },
  { id: 21703, category: "opinions", text: "L'inutilité du quotidien préférée ?", options: ["Petite cuillère café", "Oeuf coquetier", "Sticky note bureau", "Rouge à lèvres mate"] },
  { id: 21704, category: "opinions", text: "L'opinion qui te fait quitter une convo ?", options: ["Anti-vacc", "Plat froid > plat chaud", "Bouffe industrielle = bof", "Mer surcôtée"] },
  { id: 21705, category: "opinions", text: "Le pire conseil de famille ?", options: ["\"Crois en toi\"", "\"Lance ta startup\"", "\"Fais comme moi\"", "\"Suis ton coeur\""] },
  { id: 21706, category: "opinions", text: "Le truc qu'on devrait abolir ?", options: ["Heure d'été", "Pourboire calculé", "Files d'attente boîte", "Service en boucle"] },
  { id: 21707, category: "opinions", text: "L'erreur sociétale la plus assumée ?", options: ["Téléphone partout", "Réunions sans agenda", "Diplômes pour tout", "Dress code obligatoire"] },
  { id: 21708, category: "opinions", text: "Le pire signe astro à dater ?", options: ["Gémeaux", "Scorpion", "Capricorne", "Verseau"] },
  { id: 21709, category: "opinions", text: "Le truc qu'on garde pour soi ?", options: ["Goût pour la téléréalité", "Crush pop-star", "Playlist sad", "Compte Tinder"] },
  { id: 21710, category: "opinions", text: "Le pire choix de logement ?", options: ["Studio 12 m²", "Coloc 8 personnes", "RDC sur rue", "Dernier étage sans ascenseur"] },

  { id: 21801, category: "chaos", text: "Le pire pouvoir reçu sans demander ?", options: ["Lire pensées", "Voir tous les futurs", "Sentir les émotions", "Comprendre tous les langages"] },
  { id: 21802, category: "chaos", text: "Le pire job d'un super-héros ?", options: ["Sécurité métro", "Comptable secret", "Service client", "Ranger les courses"] },
  { id: 21803, category: "chaos", text: "Le pire objet dans un sac de voyage ?", options: ["Bouteille d'eau qui fuit", "Banane mûre", "Ananas piquant", "Chocolat fondu"] },
  { id: 21804, category: "chaos", text: "Le pire accessoire d'apocalypse ?", options: ["Trottinette électrique", "Chaussures à talons", "Sac à dos plage", "Casque RGB"] },
  { id: 21805, category: "chaos", text: "Le pire animal de compagnie post-apo ?", options: ["Furet", "Iguane", "Lapin nain", "Cochon vietnamien"] },
  { id: 21806, category: "chaos", text: "Le pire bruit comme réveil ?", options: ["Sirène pompier", "Aspirateur ancien", "Micro saturé", "Crécelle scout"] },
  { id: 21807, category: "chaos", text: "Le pire hobbie inutile à clamer ?", options: ["Collection bouchons", "Tricot extrême", "Théorie du complot", "ASMR amateur"] },
  { id: 21808, category: "chaos", text: "Le meilleur talent caché à révéler ?", options: ["Faire craquer ses doigts en rythme", "Imiter parfait son boss", "Plier un drap housse", "Faire un nœud de cravate" ] },

  { id: 21901, category: "rapid", text: "Le truc qu'on remet à demain à coup sûr ?", options: ["Faire la lessive", "Répondre aux mails", "Aller chez le doc", "Prendre RDV banque"] },
  { id: 21902, category: "rapid", text: "Le bruit le plus rassurant ?", options: ["Pluie sur fenêtre", "Café qui coule", "Téléphone qui vibre", "Feu de cheminée"] },
  { id: 21903, category: "rapid", text: "L'objet qu'on perd le plus ?", options: ["Clés", "Stylo", "Chargeur", "Carte de fidélité"] },
  { id: 21904, category: "rapid", text: "L'odeur qui te transporte ailleurs ?", options: ["Tarte aux pommes", "Mer", "Vieux livre", "Boulangerie"] },
  { id: 21905, category: "rapid", text: "La phrase qu'on dit trop souvent ?", options: ["\"Tranquille\"", "\"Wesh\"", "\"Ça va aller\"", "\"Genre\""] },
  { id: 21906, category: "rapid", text: "Le pire combo au lit ?", options: ["Couette froide", "Téléphone batterie 2%", "Bruits voisins", "Soif soudaine"] },
  { id: 21907, category: "rapid", text: "L'objet préféré pour relax ?", options: ["Doudou", "Plaid", "Coussin", "Bougie"] },
  { id: 21908, category: "rapid", text: "Le test ultime du quotidien ?", options: ["Faire son lit", "Vider lave-vaisselle", "Prendre douche", "Sortir poubelle"] },

  { id: 22001, category: "spicy", text: "Le pire timing pour un nude ?", options: ["En plein boulot", "Dîner familial", "Métro bondé", "Visio LinkedIn"] },
  { id: 22002, category: "spicy", text: "Le red flag dating le plus rouge ?", options: ["Photos avec ex floutées", "Bio uniquement emojis", "\"Pas de prise de tête\"", "Photo poisson pêché"] },
  { id: 22003, category: "spicy", text: "Le mensonge dating universel ?", options: ["Sur l'âge", "Sur la taille", "Sur la job", "Sur les hobbies"] },
  { id: 22004, category: "spicy", text: "Le pire moment pour un kiss ?", options: ["Premier rendez-vous court", "Devant les parents", "Après un débat", "Fin de soirée bourrée"] },
  { id: 22005, category: "spicy", text: "L'app la plus toxique du moment ?", options: ["Tinder", "Hinge", "Bumble", "Fruitz"] },
  { id: 22006, category: "spicy", text: "Le faux red flag qui se passe ?", options: ["\"Je préfère le chien à l'humain\"", "\"Je dors avec ma maman\"", "\"Pas trop d'amis\"", "\"J'aime trop ma routine\""] },
  { id: 22007, category: "spicy", text: "Le pire endroit pour craquer pour quelqu'un ?", options: ["Boulot", "Mariage cousin", "Salle de sport", "Soirée ex"] },
  { id: 22008, category: "spicy", text: "Le pire dossier qu'un ex peut sortir ?", options: ["Sextapes", "Captures d'écran", "Vidéo soirée", "Audios ivres"] },
  { id: 22009, category: "spicy", text: "Le pire kink à révéler à un date ?", options: ["Trop précis", "Trop bruyant", "Trop moral", "Trop logistique"] },
  { id: 22010, category: "spicy", text: "Le pire drama de couple visible en story ?", options: ["Story sans légende", "Repost menaçant", "Lyric sad", "Photo en larmes"] },
  { id: 22011, category: "spicy", text: "Le pire moment pour tenter le first move ?", options: ["Ascenseur lent", "Piscine collective", "Dans un cab Uber", "À une fête de boulot"] },
  { id: 22012, category: "spicy", text: "Le sujet à éviter en première soirée à la maison ?", options: ["Politique", "Ex passés", "Argent", "Santé mentale"] },
  { id: 22013, category: "spicy", text: "Le pire kink à découvrir à 4h du matin ?", options: ["Trop spécifique", "Trop dramatique", "Trop public", "Trop logistique"] },
  { id: 22014, category: "spicy", text: "Le truc qui finit toujours par sortir au troisième verre ?", options: ["Crush secret", "Histoires d'ex", "Drama amitié", "Compte Twitter caché"] },

  { id: 22101, category: "beauf", text: "L'apéro France profonde par excellence ?", options: ["Pastis + chips", "Rosé + saucisson", "Pression + cacahuètes", "Suze + olives"] },
  { id: 22102, category: "beauf", text: "Le pire moment de mariage ?", options: ["Animation Macarena", "Discours beauf", "Slow forcé", "Karaoké tonton"] },
  { id: 22103, category: "beauf", text: "Le plat de famille indéboulonnable ?", options: ["Cordon bleu poêlé", "Hachis parmentier", "Quiche lorraine", "Gratin dauphinois"] },
  { id: 22104, category: "beauf", text: "Le combo terrasse Paris cliché ?", options: ["Spritz + clope", "Rosé + amande", "Gin tonic + olive", "Heineken + cacahuète"] },
  { id: 22105, category: "beauf", text: "L'objet déco beauf assumé ?", options: ["Néon \"home sweet home\"", "Tableau cerf chasse", "Fontaine indoor", "Calendrier pin-up"] },
  { id: 22106, category: "beauf", text: "Le pire moment d'un BBQ ?", options: ["Saucisses cramées", "Pluie soudaine", "Dispute viande / végé", "Gaz épuisé"] },
  { id: 22107, category: "beauf", text: "Le pire moment d'un repas de famille ?", options: ["Le débat politique", "L'âge de l'adulte interrogé", "Le fameux \"alors les amours\"", "Les compliments douteux"] },
  { id: 22108, category: "beauf", text: "Le pire choix musical en voiture familiale ?", options: ["Chante France", "Best of Goldman", "Compilation Carrefour", "Variété 2003"] },
  { id: 22109, category: "beauf", text: "Le pire élément d'une terrasse jardin ?", options: ["Salon de jardin neuf laissé sale", "Piscine gonflable trouée", "Trampoline rouillé", "Hamac branche cassée"] },
  { id: 22110, category: "beauf", text: "Le pire achat impulsif de bricolage ?", options: ["Multitool 80 outils", "Aspirateur soufflant", "Tronçonneuse mini", "Imprimante 3D promo"] },
  { id: 22111, category: "beauf", text: "Le sport club le plus beauf ?", options: ["Pétanque", "Tennis municipal", "Football amateur dimanche", "Karting bourré"] },
  { id: 22112, category: "beauf", text: "La pire blague de tonton ?", options: ["Sur les belles-mères", "Sur les Belges", "Sur la routine", "Sur la météo \"chaud chaud\""] },
  { id: 22113, category: "beauf", text: "Le pire élément de salle des fêtes ?", options: ["Lumière néon", "Sono qui sature", "Sol collant", "Buffet réchauffé"] },
  { id: 22114, category: "beauf", text: "L'élément essentiel du camping français ?", options: ["Tireuse à bière", "Pétanque sur sol gravier", "Karaoké soir", "Apéro 5 mobile-homes"] },

  { id: 22201, category: "genz", text: "L'expression la plus surutilisée 2025 ?", options: ["Slay", "No cap", "Aura points", "Ohio behavior"] },
  { id: 22202, category: "genz", text: "Le main character moment ultime ?", options: ["Marche dans la pluie écouteurs", "Café terrasse en silence", "Train au coucher de soleil", "Concert en sweat oversize"] },
  { id: 22203, category: "genz", text: "Le pire \"ick\" universel ?", options: ["Court trop fort", "Tape sur la table en riant", "Manque de manières", "Posté trop d'IA"] },
  { id: 22204, category: "genz", text: "L'ère qu'on fait durer trop longtemps ?", options: ["Healing era", "Soft launch era", "Villain era", "Pilates era"] },
  { id: 22205, category: "genz", text: "Le brainrot le plus pollutif ?", options: ["Skibidi", "Hawk Tuah", "Edits Looksmaxxing", "Sigma male"] },
  { id: 22206, category: "genz", text: "L'opinion gen Z la plus partagée ?", options: ["LinkedIn cringe", "Marketing personnel obligatoire", "Boomers responsables", "Réveil 5h zéro merci"] },
  { id: 22207, category: "genz", text: "Le format de contenu qui cartonne en 2025 ?", options: ["POV ultra spécifique", "Storytime 9 parts", "Day in my life chaotique", "Voiceover cynique"] },
  { id: 22208, category: "genz", text: "L'app secrète qu'on ouvre en planque ?", options: ["BeReal", "Pinterest", "Goodreads", "Letterboxd"] },
  { id: 22209, category: "genz", text: "Le pire trauma TikTok ?", options: ["Algorithme qui change", "Shadow ban", "Trend qui meurt vite", "Audio retiré"] },
  { id: 22210, category: "genz", text: "L'erreur classique sur Insta ?", options: ["Hard launch trop tôt", "Soft launch confus", "Repost sans crédit", "Carrousel chaotique"] },
  { id: 22211, category: "genz", text: "Le terme préféré pour décrire son ex ?", options: ["NPC", "Side character", "Final boss", "Glitch"] },
  { id: 22212, category: "genz", text: "Le pire boomer move au boulot ?", options: ["Mail \"Cdt\"", "Réunion sans Doodle", "Imprime tout", "Refuse Slack"] },
  { id: 22213, category: "genz", text: "L'aesthetic qui revient pas ?", options: ["Y2K rave", "Cottagecore", "Indie sleaze 2009", "Soft girl 2014"] },
  { id: 22214, category: "genz", text: "Le truc le plus Gen Z avoué ?", options: ["Anxiété mail vocal", "Lecture seule des terms", "Adresse mail cringe primaire", "Nom Snapchat embarrassant"] },
];
