// 400+ dilemmes "Tu préfères ?" répartis en 7 catégories.
// Inspirés des classiques du genre (would-you-rather), reformulés en français.

export type Category =
  | "soft"
  | "hot"
  | "trash"
  | "insolite"
  | "ethique"
  | "couple"
  | "pop"
  | "gaming"
  | "internet"
  | "beauf"
  | "genz";

export interface CategoryMeta {
  id: Category;
  label: string;
  emoji: string;
  description: string;
  adult: boolean;
}

export const CATEGORIES: CategoryMeta[] = [
  { id: "soft",     label: "Classique",   emoji: "🟣", description: "Pour tout le monde, sans tabou.",        adult: false },
  { id: "hot",      label: "Hot",         emoji: "🔥", description: "Spicy, 18+. Réservé aux adultes.",        adult: true  },
  { id: "trash",    label: "Trash",       emoji: "💀", description: "Sombre, dérangeant, sans filtre.",        adult: true  },
  { id: "insolite", label: "Insolite",    emoji: "🤪", description: "Bizarre, drôle, complètement WTF.",       adult: false },
  { id: "ethique",  label: "Éthique",     emoji: "⚖️", description: "Dilemmes moraux qui font débattre.",      adult: false },
  { id: "couple",   label: "Couple",      emoji: "💑", description: "Spécial relations, amour, jalousie.",     adult: false },
  { id: "pop",      label: "Pop culture", emoji: "🎬", description: "Films, séries, jeux vidéo, super-héros.", adult: false },
  { id: "gaming",   label: "Gaming",      emoji: "🎮", description: "Skins, ragequit, lobbies toxiques.",       adult: false },
  { id: "internet", label: "Internet",    emoji: "📱", description: "TikTok, dramas et habitudes en ligne.",   adult: false },
  { id: "beauf",    label: "Beauf",       emoji: "🍻", description: "Apéro, BBQ et France profonde assumée.", adult: false },
  { id: "genz",     label: "Gen Z",       emoji: "🧠", description: "Brainrot, slang et chaos moderne.",        adult: false },
];

export interface Question {
  id: number;
  optionA: string;
  optionB: string;
  category: Category;
}

export const QUESTIONS: Question[] = [
  // ========================== SOFT (1-80) ==========================
  { id: 1,  category: "soft", optionA: "Être riche mais malheureux", optionB: "Être pauvre mais heureux" },
  { id: 2,  category: "soft", optionA: "Pouvoir voler", optionB: "Pouvoir devenir invisible" },
  { id: 3,  category: "soft", optionA: "Manger sucré toute sa vie", optionB: "Manger salé toute sa vie" },
  { id: 4,  category: "soft", optionA: "Perdre ses souvenirs", optionB: "N'avoir jamais de nouveaux souvenirs" },
  { id: 5,  category: "soft", optionA: "Savoir tout mais ne rien pouvoir changer", optionB: "Ne rien savoir mais tout pouvoir changer" },
  { id: 6,  category: "soft", optionA: "Vivre 200 ans en bonne santé", optionB: "Revivre sa vie actuelle 3 fois" },
  { id: 7,  category: "soft", optionA: "Pouvoir parler toutes les langues", optionB: "Pouvoir jouer de tous les instruments" },
  { id: 8,  category: "soft", optionA: "Avoir toujours chaud", optionB: "Avoir toujours froid" },
  { id: 9,  category: "soft", optionA: "Ne jamais dormir", optionB: "Dormir 20h par jour" },
  { id: 10, category: "soft", optionA: "Être célèbre mais détesté", optionB: "Être inconnu mais adoré" },
  { id: 11, category: "soft", optionA: "Pouvoir lire dans les pensées", optionB: "Voir le futur" },
  { id: 12, category: "soft", optionA: "Perdre son téléphone", optionB: "Perdre son portefeuille" },
  { id: 13, category: "soft", optionA: "Ne jamais ressentir la douleur", optionB: "Ne jamais ressentir la fatigue" },
  { id: 14, category: "soft", optionA: "Vivre sans musique", optionB: "Vivre sans films/séries" },
  { id: 15, category: "soft", optionA: "Avoir un robot domestique", optionB: "Avoir une voiture volante" },
  { id: 16, category: "soft", optionA: "Manger le même plat chaque jour", optionB: "Ne jamais remanger le même plat" },
  { id: 17, category: "soft", optionA: "Connaître l'heure de sa mort", optionB: "Connaître la cause de sa mort" },
  { id: 18, category: "soft", optionA: "Avoir un super pouvoir inutile", optionB: "N'avoir aucun super pouvoir" },
  { id: 19, category: "soft", optionA: "Voyager dans le passé sans pouvoir changer", optionB: "Voyager dans le futur sans pouvoir revenir" },
  { id: 20, category: "soft", optionA: "Être le plus intelligent du monde", optionB: "Être le plus charismatique du monde" },
  { id: 21, category: "soft", optionA: "Avoir une mémoire parfaite", optionB: "Pouvoir oublier ce que tu veux" },
  { id: 22, category: "soft", optionA: "Perdre le goût", optionB: "Perdre l'odorat" },
  { id: 23, category: "soft", optionA: "Parler en rimes tout le temps", optionB: "Chanter au lieu de parler" },
  { id: 24, category: "soft", optionA: "N'avoir qu'1 ami très proche", optionB: "Avoir 1000 amis superficiels" },
  { id: 25, category: "soft", optionA: "Être toujours en avance", optionB: "Être toujours en retard" },
  { id: 26, category: "soft", optionA: "Vivre seul sur une île déserte 10 ans", optionB: "Vivre dans une mégalopole bondée à vie" },
  { id: 27, category: "soft", optionA: "Pouvoir te téléporter n'importe où", optionB: "Pouvoir arrêter le temps" },
  { id: 28, category: "soft", optionA: "Voyager partout dans le monde sans maison", optionB: "Avoir une maison de rêve qui ne bouge pas" },
  { id: 29, category: "soft", optionA: "Toujours avoir froid aux pieds", optionB: "Toujours avoir les mains moites" },
  { id: 30, category: "soft", optionA: "Refaire ton lit à chaque fois que tu t'assois dessus", optionB: "Refaire tes lacets après chaque pas" },
  { id: 31, category: "soft", optionA: "Pouvoir respirer sous l'eau", optionB: "Pouvoir survivre dans l'espace" },
  { id: 32, category: "soft", optionA: "Avoir 5 enfants", optionB: "Ne jamais en avoir" },
  { id: 33, category: "soft", optionA: "Vivre dans une grotte tout confort", optionB: "Vivre dans un château hanté" },
  { id: 34, category: "soft", optionA: "Manger uniquement chaud", optionB: "Manger uniquement froid" },
  { id: 35, category: "soft", optionA: "Boire seulement de l'eau toute ta vie", optionB: "Manger seulement du pain toute ta vie" },
  { id: 36, category: "soft", optionA: "Avoir des super sens (vue, ouïe, odorat à fond)", optionB: "Avoir un super cerveau" },
  { id: 37, category: "soft", optionA: "Pouvoir parler aux animaux", optionB: "Pouvoir parler aux plantes" },
  { id: 38, category: "soft", optionA: "Ne plus jamais voir la mer", optionB: "Ne plus jamais voir la montagne" },
  { id: 39, category: "soft", optionA: "Être beau mais idiot", optionB: "Être moche mais brillant" },
  { id: 40, category: "soft", optionA: "Voyager dans le temps une seule fois", optionB: "Pouvoir te téléporter une fois par jour" },
  { id: 41, category: "soft", optionA: "Vivre sans internet", optionB: "Vivre sans voiture" },
  { id: 42, category: "soft", optionA: "Avoir 1 million d'euros tout de suite", optionB: "10 millions dans 10 ans" },
  { id: 43, category: "soft", optionA: "Pouvoir arrêter de vieillir à 30 ans", optionB: "Reprendre 10 ans de jeunesse maintenant" },
  { id: 44, category: "soft", optionA: "Chanter parfaitement", optionB: "Danser parfaitement" },
  { id: 45, category: "soft", optionA: "Tout savoir sur le passé de l'humanité", optionB: "Connaître ton futur exact" },
  { id: 46, category: "soft", optionA: "Découvrir une nouvelle galaxie", optionB: "Découvrir un trésor sous l'océan" },
  { id: 47, category: "soft", optionA: "Vivre 100 ans en parfaite santé", optionB: "Vivre 50 ans avec des super pouvoirs" },
  { id: 48, category: "soft", optionA: "Pouvoir voler à 30 km/h max", optionB: "Pouvoir courir à 100 km/h" },
  { id: 49, category: "soft", optionA: "Toujours porter le même vêtement", optionB: "Devoir changer de tenue toutes les 2h" },
  { id: 50, category: "soft", optionA: "N'avoir que 3 heures de jour par 24h", optionB: "N'avoir que 3 heures de nuit par 24h" },
  { id: 51, category: "soft", optionA: "Pouvoir réécrire un seul moment de ta vie", optionB: "Effacer un seul moment de ta vie" },
  { id: 52, category: "soft", optionA: "Vivre dans le passé (1800)", optionB: "Vivre dans le futur (2300)" },
  { id: 53, category: "soft", optionA: "Avoir une bibliothèque infinie", optionB: "Avoir une collection de jeux infinie" },
  { id: 54, category: "soft", optionA: "Tout savoir sur un seul sujet", optionB: "Avoir des bases dans tous les sujets" },
  { id: 55, category: "soft", optionA: "Découvrir un secret bouleversant", optionB: "Garder un secret toute sa vie" },
  { id: 56, category: "soft", optionA: "Avoir une queue d'animal", optionB: "Avoir des oreilles d'animal" },
  { id: 57, category: "soft", optionA: "Voyager sans bagages magiquement", optionB: "Avoir un jet privé gratuit à vie" },
  { id: 58, category: "soft", optionA: "Devenir un personnage de série", optionB: "Inviter un personnage dans la vraie vie" },
  { id: 59, category: "soft", optionA: "Devoir dire \"miaou\" à la fin de chaque phrase", optionB: "Tousser à chaque mot" },
  { id: 60, category: "soft", optionA: "Tout connaître en cuisine", optionB: "Tout connaître en bricolage" },
  { id: 61, category: "soft", optionA: "Conduire une F1", optionB: "Piloter un avion de chasse" },
  { id: 62, category: "soft", optionA: "Habiter sur un bateau", optionB: "Habiter dans une caravane" },
  { id: 63, category: "soft", optionA: "Apprendre instantanément un sport", optionB: "Apprendre instantanément un instrument" },
  { id: 64, category: "soft", optionA: "Ne plus jamais avoir mal aux dents", optionB: "Ne plus jamais avoir mal au crâne" },
  { id: 65, category: "soft", optionA: "Travailler dur 4 jours et avoir 3 jours off", optionB: "Travailler 6 jours peinards" },
  { id: 66, category: "soft", optionA: "Boire un café énorme le matin", optionB: "Faire une sieste de 2h l'après-midi" },
  { id: 67, category: "soft", optionA: "Toujours connaître la bonne réponse", optionB: "Toujours poser la bonne question" },
  { id: 68, category: "soft", optionA: "Vivre avec un ours apprivoisé", optionB: "Vivre avec un lion apprivoisé" },
  { id: 69, category: "soft", optionA: "Recevoir un compliment énorme par jour", optionB: "Faire pleurer de joie quelqu'un par semaine" },
  { id: 70, category: "soft", optionA: "Tout dire à voix haute pour toujours", optionB: "Ne plus jamais dire un mot" },
  { id: 71, category: "soft", optionA: "Avoir un superpouvoir contrôlable", optionB: "Avoir trois superpouvoirs aléatoires" },
  { id: 72, category: "soft", optionA: "Vivre dans un monde sans couleur", optionB: "Vivre dans un monde sans son" },
  { id: 73, category: "soft", optionA: "Connaître une seule langue mais parfaitement", optionB: "Baragouiner toutes les langues" },
  { id: 74, category: "soft", optionA: "Garder ton boulot actuel à vie", optionB: "Changer de métier tous les 2 ans" },
  { id: 75, category: "soft", optionA: "Boire du jus d'orange dans ton café", optionB: "Mettre du sel dans ton chocolat chaud" },
  { id: 76, category: "soft", optionA: "Tour du monde gratuit obligatoire 1 an", optionB: "Recevoir 100k€ et rester chez toi" },
  { id: 77, category: "soft", optionA: "Avoir 100 followers très fidèles", optionB: "Avoir 1 million de followers volatils" },
  { id: 78, category: "soft", optionA: "Vivre une vie courte mais légendaire", optionB: "Vivre une vie longue et tranquille" },
  { id: 79, category: "soft", optionA: "Tout réussir du premier coup", optionB: "Apprendre de tes échecs" },
  { id: 80, category: "soft", optionA: "Voir tes rêves dans la vraie vie", optionB: "Vivre la vraie vie comme un rêve" },

  // ========================== HOT (81-150) =========================
  { id: 81,  category: "hot", optionA: "Faire l'amour très souvent et rapidement", optionB: "Rarement mais longtemps" },
  { id: 82,  category: "hot", optionA: "Faire l'amour en plein jour fenêtres ouvertes", optionB: "La nuit dans le noir total" },
  { id: 83,  category: "hot", optionA: "Avoir un partenaire sublime mais nul au lit", optionB: "Pas top physiquement mais incroyable au lit" },
  { id: 84,  category: "hot", optionA: "Embrasser ton ex en public", optionB: "Embrasser un inconnu en privé" },
  { id: 85,  category: "hot", optionA: "Tout savoir sur la vie sexuelle de ton/ta meilleur(e) ami(e)", optionB: "Qu'iel sache tout sur la tienne" },
  { id: 86,  category: "hot", optionA: "Faire un strip-tease devant tes potes sobres", optionB: "Que ton crush voie tout ton historique de recherches" },
  { id: 87,  category: "hot", optionA: "Coucher avec une seule personne à vie", optionB: "N'avoir que des coups d'un soir" },
  { id: 88,  category: "hot", optionA: "Faire l'amour dans un lieu public", optionB: "Te filmer en train de le faire" },
  { id: 89,  category: "hot", optionA: "Pratiquer le sexe sans tabou avec un coup régulier", optionB: "Avoir un partenaire ultra-romantique mais sage" },
  { id: 90,  category: "hot", optionA: "Recevoir un message coquin par erreur de ton parent", optionB: "De ton patron" },
  { id: 91,  category: "hot", optionA: "Avoir un seul orgasme par mois mais incroyable", optionB: "Plein de petits sans intensité" },
  { id: 92,  category: "hot", optionA: "Tout faire au lit sans préliminaires", optionB: "Que des préliminaires sans rien de plus" },
  { id: 93,  category: "hot", optionA: "Coucher avec quelqu'un qui ressemble à ton/ta meilleur(e) ami(e)", optionB: "À ton/ta ex" },
  { id: 94,  category: "hot", optionA: "Lire un texto coquin de ton/ta crush devant tes parents", optionB: "L'envoyer par erreur à toute ta famille" },
  { id: 95,  category: "hot", optionA: "Coucher dans tous les pays du monde", optionB: "Avoir 100 fois la meilleure nuit de ta vie avec la même personne" },
  { id: 96,  category: "hot", optionA: "Tester un sextoy en public à l'insu des autres", optionB: "Avec tes potes au courant" },
  { id: 97,  category: "hot", optionA: "Que ton/ta ex revienne à fond", optionB: "Rencontrer une nouvelle flamme passionnée" },
  { id: 98,  category: "hot", optionA: "Sex tape qui leak avec une note 8/10", optionB: "Pas de sex tape mais réputation de mauvais coup" },
  { id: 99,  category: "hot", optionA: "Embrasser une célébrité une fois", optionB: "Avoir une nuit avec un inconnu sublime" },
  { id: 100, category: "hot", optionA: "Avoir un contrôle total sur ton excitation", optionB: "Pouvoir contrôler celle des autres" },
  { id: 101, category: "hot", optionA: "Que ton/ta partenaire fasse semblant à chaque fois", optionB: "Qu'iel ne fasse pas du tout d'effort" },
  { id: 102, category: "hot", optionA: "Découvrir un fétiche très bizarre de ton/ta partenaire", optionB: "Que le tien soit révélé sans ton accord" },
  { id: 103, category: "hot", optionA: "Faire l'amour en silence absolu", optionB: "Faire un bruit énorme à chaque fois" },
  { id: 104, category: "hot", optionA: "Être le meilleur coup de ta ville", optionB: "Avoir le plus gros cœur de ta ville" },
  { id: 105, category: "hot", optionA: "Avoir des rapports protégés à vie", optionB: "Une seule fois sans, et qui change ta vie" },
  { id: 106, category: "hot", optionA: "Coucher avec le boss de ton/ta partenaire", optionB: "Que ton/ta partenaire couche avec ton/ta ex" },
  { id: 107, category: "hot", optionA: "Faire un plan à 3 avec deux inconnus", optionB: "Avec deux personnes que tu connais bien" },
  { id: 108, category: "hot", optionA: "Que tes parents trouvent tes sextoys", optionB: "Tes recherches privées sur ton tel" },
  { id: 109, category: "hot", optionA: "N'avoir qu'une seule position pour la vie", optionB: "Toutes les positions mais sans missionnaire" },
  { id: 110, category: "hot", optionA: "Te masturber 3x par jour à vie", optionB: "Plus jamais" },
  { id: 111, category: "hot", optionA: "Faire un coup d'un soir avec ton/ta crush sans suite", optionB: "Te marier avec une personne random demain" },
  { id: 112, category: "hot", optionA: "Avoir un partenaire ultra jaloux", optionB: "Un partenaire trop ouvert" },
  { id: 113, category: "hot", optionA: "Que ta playlist sexe soit publique", optionB: "Que tes positions favorites le soient" },
  { id: 114, category: "hot", optionA: "Coucher avec quelqu'un de 20 ans plus âgé", optionB: "20 ans plus jeune (légalement majeur)" },
  { id: 115, category: "hot", optionA: "Recevoir tous les compliments physiques", optionB: "Tous les compliments intellectuels" },
  { id: 116, category: "hot", optionA: "Coucher avec ton coup de cœur sans jamais le revoir", optionB: "L'aimer sans jamais y toucher" },
  { id: 117, category: "hot", optionA: "Faire l'amour avec interruptions toutes les 5 min", optionB: "Sans pouvoir t'arrêter pendant 4h" },
  { id: 118, category: "hot", optionA: "Tout savoir des fantasmes de tes amis", optionB: "Devoir leur dévoiler tous les tiens" },
  { id: 119, category: "hot", optionA: "Faire un strip-tease pour ton/ta crush bourré(e)", optionB: "Sobre mais devant ses potes" },
  { id: 120, category: "hot", optionA: "Voir ton/ta partenaire au lit avec quelqu'un d'autre", optionB: "Qu'iel te voie le faire" },
  { id: 121, category: "hot", optionA: "N'avoir que des dates dans des fast-foods", optionB: "Que dans des restos étoilés froids" },
  { id: 122, category: "hot", optionA: "Te faire larguer par message", optionB: "Devant tout le monde" },
  { id: 123, category: "hot", optionA: "Une nuit avec ton/ta star préféré(e)", optionB: "Une vie tranquille mais aimée" },
  { id: 124, category: "hot", optionA: "Découvrir que ton/ta partenaire t'a déjà trompé(e)", optionB: "Le/la tromper toi sans qu'iel le sache jamais" },
  { id: 125, category: "hot", optionA: "Que ton/ta partenaire ait beaucoup d'expérience", optionB: "Très peu" },
  { id: 126, category: "hot", optionA: "Avoir un partenaire physiquement parfait mais ennuyeux", optionB: "Drôle mais lambda physiquement" },
  { id: 127, category: "hot", optionA: "Avouer ton fantasme le plus chelou à ta famille", optionB: "À tes collègues" },
  { id: 128, category: "hot", optionA: "Faire un sondage public sur ta vie sexuelle", optionB: "Sur ton compte en banque" },
  { id: 129, category: "hot", optionA: "Te marier avec quelqu'un que tu n'aimes pas pour 1 milliard", optionB: "Vivre seul et fauché" },
  { id: 130, category: "hot", optionA: "Coucher avec une seule personne ULTRA douée", optionB: "100 personnes correctes" },
  { id: 131, category: "hot", optionA: "Apprendre que tes parents ont un kink chelou", optionB: "Que ta grand-mère était escort dans sa jeunesse" },
  { id: 132, category: "hot", optionA: "Sexto en public sans pouvoir te cacher", optionB: "En privé mais leak après" },
  { id: 133, category: "hot", optionA: "Avoir un coup de foudre par mois", optionB: "Un grand amour rare et fou" },
  { id: 134, category: "hot", optionA: "Tomber amoureux de quelqu'un d'autre que ton/ta partenaire", optionB: "Que ton/ta partenaire tombe amoureux d'un(e) autre" },
  { id: 135, category: "hot", optionA: "Que ton crush découvre tes fanfics secrètes", optionB: "Tes vidéos de toi qui chante mal" },
  { id: 136, category: "hot", optionA: "Aimer 100 % pour le physique", optionB: "100 % pour la personnalité" },
  { id: 137, category: "hot", optionA: "Subir une dry spell de 5 ans", optionB: "Une décennie ultra chaude puis plus rien" },
  { id: 138, category: "hot", optionA: "Faire l'amour avec quelqu'un qui pue mais qui te plaît à fond", optionB: "Hyper propre mais zéro attraction" },
  { id: 139, category: "hot", optionA: "Avoir 10 ex toxiques", optionB: "1 seul ex qui t'a brisé(e)" },
  { id: 140, category: "hot", optionA: "Être tagué dans un post embarrassant à vie", optionB: "Devoir poster une story embarrassante par jour" },
  { id: 141, category: "hot", optionA: "Coucher avec un fantôme", optionB: "Un alien" },
  { id: 142, category: "hot", optionA: "Avoir un partenaire célèbre et harcelé", optionB: "Devenir célèbre toi-même et harcelé(e)" },
  { id: 143, category: "hot", optionA: "Que ton vibrateur sonne en plein rdv famille", optionB: "Que ton appli de dating notifie ta mère" },
  { id: 144, category: "hot", optionA: "Découvrir un secret hot sur ton ex", optionB: "Garder ton ex secret toute ta vie" },
  { id: 145, category: "hot", optionA: "Te tatouer le prénom de ton crush actuel", optionB: "Te tatouer un dick pic" },
  { id: 146, category: "hot", optionA: "Ne plus jamais faire l'amour mais avoir tout le reste", optionB: "N'avoir que le sexe et plus aucun lien" },
  { id: 147, category: "hot", optionA: "Avoir un partenaire 10x plus expérimenté", optionB: "10x moins" },
  { id: 148, category: "hot", optionA: "Faire l'amour dans un musée fermé", optionB: "Dans un cimetière de nuit" },
  { id: 149, category: "hot", optionA: "Recevoir des nudes par erreur de ta belle-mère", optionB: "Lui en envoyer par erreur" },
  { id: 150, category: "hot", optionA: "Devoir narrer ta vie sexuelle à voix haute", optionB: "Que tes pensées privées soient diffusées en public" },

  // ========================= TRASH (151-210) =======================
  { id: 151, category: "trash", optionA: "Manger un cafard vivant", optionB: "Boire un verre d'eau de toilette public" },
  { id: 152, category: "trash", optionA: "Découvrir un cadavre dans ta cave", optionB: "Dans ton lit" },
  { id: 153, category: "trash", optionA: "Devoir tuer un chien errant", optionB: "Tuer 100 araignées à la main" },
  { id: 154, category: "trash", optionA: "Lécher la rampe d'un métro parisien", optionB: "Boire l'eau d'un caniveau" },
  { id: 155, category: "trash", optionA: "Découvrir que tu es adopté", optionB: "Que tes enfants ne sont pas tes enfants biologiques" },
  { id: 156, category: "trash", optionA: "Vivre 10 ans en prison innocent", optionB: "Tuer accidentellement quelqu'un et vivre libre" },
  { id: 157, category: "trash", optionA: "Manger un steak de chien", optionB: "Un steak humain" },
  { id: 158, category: "trash", optionA: "Boire 1 litre de pus", optionB: "Manger 1 kg de matière fécale animale" },
  { id: 159, category: "trash", optionA: "Te faire arracher tous les ongles", optionB: "Te faire arracher toutes les dents" },
  { id: 160, category: "trash", optionA: "Voir ton crush mourir devant toi", optionB: "Mourir toi-même mais ton crush ne te connaît pas" },
  { id: 161, category: "trash", optionA: "Apprendre que ton père est un meurtrier", optionB: "Que ta mère t'a abandonné(e) volontairement" },
  { id: 162, category: "trash", optionA: "Découvrir un nid de rats sous ton lit", optionB: "Une caméra dans ta chambre depuis 1 an" },
  { id: 163, category: "trash", optionA: "Tuer pour défendre ta famille", optionB: "Laisser ta famille mourir pour ne pas tuer" },
  { id: 164, category: "trash", optionA: "Te faire tatouer une insulte sur le front", optionB: "Te faire amputer un doigt" },
  { id: 165, category: "trash", optionA: "Manger un yaourt périmé de 6 mois", optionB: "Boire un litre de lait caillé" },
  { id: 166, category: "trash", optionA: "Vivre avec une douleur chronique 8/10", optionB: "Avec une dépression sévère" },
  { id: 167, category: "trash", optionA: "Voir ton enfant mourir", optionB: "Mourir devant ton enfant" },
  { id: 168, category: "trash", optionA: "Devenir paralysé du cou jusqu'aux pieds", optionB: "Perdre la vue ET l'ouïe" },
  { id: 169, category: "trash", optionA: "Manger ton vomi", optionB: "Manger celui d'un inconnu" },
  { id: 170, category: "trash", optionA: "Apprendre que ton/ta partenaire est un tueur en série", optionB: "Un escroc qui t'a tout pris" },
  { id: 171, category: "trash", optionA: "Te réveiller dans un cercueil enterré", optionB: "Dans une morgue" },
  { id: 172, category: "trash", optionA: "Subir une opération sans anesthésie", optionB: "Être brûlé vif pendant 5 secondes" },
  { id: 173, category: "trash", optionA: "Voir tout ton historique internet projeté en public", optionB: "Tes pensées des 24 dernières heures diffusées" },
  { id: 174, category: "trash", optionA: "Prendre une douche de sang", optionB: "Une douche d'urine" },
  { id: 175, category: "trash", optionA: "Découvrir que tu es un clone", optionB: "Que tu es un personnage de simulation" },
  { id: 176, category: "trash", optionA: "Tuer 1 enfant pour sauver 100 inconnus", optionB: "Laisser 100 inconnus mourir" },
  { id: 177, category: "trash", optionA: "Manger un placenta cru", optionB: "Boire du sang humain frais" },
  { id: 178, category: "trash", optionA: "Avoir une lèpre limitée à un bras", optionB: "Une infection qui ronge ton visage" },
  { id: 179, category: "trash", optionA: "Vivre 1 an dans une prison turque", optionB: "5 ans dans un couvent isolé" },
  { id: 180, category: "trash", optionA: "Apprendre que ta vie est un Truman Show", optionB: "Que rien n'a jamais existé" },
  { id: 181, category: "trash", optionA: "Manger un ver de terre vivant", optionB: "Avaler un cafard vivant" },
  { id: 182, category: "trash", optionA: "Devoir tuer ton meilleur ami pour survivre", optionB: "Mourir pour le sauver" },
  { id: 183, category: "trash", optionA: "Boire l'eau d'un aquarium pourri", optionB: "Manger 10 vers de terre" },
  { id: 184, category: "trash", optionA: "Apprendre que ton chien est ton père réincarné", optionB: "Ta grand-mère réincarnée" },
  { id: 185, category: "trash", optionA: "Voir un suicide en direct sans pouvoir agir", optionB: "Devoir l'empêcher physiquement" },
  { id: 186, category: "trash", optionA: "Découvrir le corps d'un proche", optionB: "Apprendre sa mort par téléphone seul" },
  { id: 187, category: "trash", optionA: "Devenir psychopathe sans le savoir", optionB: "Le savoir mais lutter chaque jour" },
  { id: 188, category: "trash", optionA: "Vivre dans une maison hantée vraiment méchante", optionB: "Sans amis, isolé total à vie" },
  { id: 189, category: "trash", optionA: "Te faire arracher les yeux", optionB: "Te faire couper la langue" },
  { id: 190, category: "trash", optionA: "Apprendre que tu as un cancer en stade 4", optionB: "Qu'un de tes parents l'a" },
  { id: 191, category: "trash", optionA: "Tuer ton ennemi juré sans conséquence", optionB: "Pardonner publiquement sans rien obtenir" },
  { id: 192, category: "trash", optionA: "Devoir torturer quelqu'un une fois", optionB: "Être torturé toi une fois" },
  { id: 193, category: "trash", optionA: "Te réveiller couvert de sang sans savoir d'où", optionB: "Te réveiller dans un endroit inconnu sans mémoire" },
  { id: 194, category: "trash", optionA: "Vivre une vie sans amour", optionB: "Une vie d'amours toxiques répétés" },
  { id: 195, category: "trash", optionA: "Te faire enterrer vivant 1h", optionB: "Brûler la main pendant 30 secondes" },
  { id: 196, category: "trash", optionA: "Découvrir un crâne humain dans ton jardin", optionB: "Une tombe dans ta cave" },
  { id: 197, category: "trash", optionA: "Mâcher du verre pilé", optionB: "Boire du verre liquide brûlant" },
  { id: 198, category: "trash", optionA: "Apprendre que ton/ta meilleur(e) ami(e) a couché avec ton/ta partenaire", optionB: "Avec ton parent" },
  { id: 199, category: "trash", optionA: "Te faire mordre par un chien enragé", optionB: "Par 100 araignées" },
  { id: 200, category: "trash", optionA: "Vivre dans un monde sans soleil", optionB: "Sans pluie" },
  { id: 201, category: "trash", optionA: "Te faire écraser dans un ascenseur 24h", optionB: "Coincer en avion 48h" },
  { id: 202, category: "trash", optionA: "Voir tes proches t'oublier", optionB: "Les oublier toi" },
  { id: 203, category: "trash", optionA: "Avoir un cauchemar qui se réalise", optionB: "Un rêve génial qui ne se réalisera jamais" },
  { id: 204, category: "trash", optionA: "Pisser du sang à vie", optionB: "Cracher du sang chaque matin" },
  { id: 205, category: "trash", optionA: "Manger un poisson rouge vivant", optionB: "Manger un hamster vivant" },
  { id: 206, category: "trash", optionA: "Tomber dans une fosse septique", optionB: "Tomber dans un nid de serpents non venimeux" },
  { id: 207, category: "trash", optionA: "Vomir à chaque câlin", optionB: "Pleurer du sang à chaque rire" },
  { id: 208, category: "trash", optionA: "Tuer ton animal de compagnie pour sauver un inconnu", optionB: "Sacrifier l'inconnu" },
  { id: 209, category: "trash", optionA: "Avoir des asticots dans une plaie ouverte 1 mois", optionB: "Une infection à la moelle 1 an" },
  { id: 210, category: "trash", optionA: "Manger des yeux d'animal cru", optionB: "Manger un cerveau cru" },

  // ========================= INSOLITE (211-270) ====================
  { id: 211, category: "insolite", optionA: "Avoir des pieds à la place des mains", optionB: "Des mains à la place des pieds" },
  { id: 212, category: "insolite", optionA: "Roter à chaque \"merci\"", optionB: "Péter à chaque rire" },
  { id: 213, category: "insolite", optionA: "Avoir la tête à l'envers en permanence", optionB: "Marcher uniquement à reculons" },
  { id: 214, category: "insolite", optionA: "Cracher des paillettes", optionB: "Pleurer du miel" },
  { id: 215, category: "insolite", optionA: "Avoir une queue de licorne", optionB: "Des ailes de chauve-souris" },
  { id: 216, category: "insolite", optionA: "Saigner du nez à chaque mensonge", optionB: "Bafouiller à chaque vérité" },
  { id: 217, category: "insolite", optionA: "Sentir le fromage en permanence", optionB: "Le poisson cru en permanence" },
  { id: 218, category: "insolite", optionA: "Te transformer en chat la nuit", optionB: "En grenouille en cas d'émotion forte" },
  { id: 219, category: "insolite", optionA: "Bouger uniquement en sautillant", optionB: "Uniquement en rampant" },
  { id: 220, category: "insolite", optionA: "Avoir 3 yeux", optionB: "4 oreilles" },
  { id: 221, category: "insolite", optionA: "Être miniaturisé à 5 cm 1 jour par mois", optionB: "Géant 3 m une semaine par an" },
  { id: 222, category: "insolite", optionA: "Avoir un nez de Pinocchio", optionB: "Un long cou de girafe" },
  { id: 223, category: "insolite", optionA: "Devenir un nain de jardin la nuit", optionB: "Un mannequin de vitrine le jour" },
  { id: 224, category: "insolite", optionA: "Cheveux qui poussent à 1 m/jour", optionB: "Ongles à 10 cm/jour" },
  { id: 225, category: "insolite", optionA: "Cracher du feu une fois par jour", optionB: "Geler tout en touchant" },
  { id: 226, category: "insolite", optionA: "Pondre un œuf par mois", optionB: "Muer comme un serpent une fois par an" },
  { id: 227, category: "insolite", optionA: "Avoir des bras tentacules", optionB: "Des jambes ressorts" },
  { id: 228, category: "insolite", optionA: "Tout entendre 10x plus fort", optionB: "Tout voir avec un délai de 3 secondes" },
  { id: 229, category: "insolite", optionA: "Devoir parler avec des effets sonores Tex Avery", optionB: "Comme un robot" },
  { id: 230, category: "insolite", optionA: "Avoir un parfum naturel d'oignon", optionB: "De pet" },
  { id: 231, category: "insolite", optionA: "Devenir invisible quand tu pleures", optionB: "Voler quand tu rigoles" },
  { id: 232, category: "insolite", optionA: "Avoir une tête de poisson", optionB: "Un corps de poulpe" },
  { id: 233, category: "insolite", optionA: "Boire ton café par les yeux", optionB: "Manger par tes oreilles" },
  { id: 234, category: "insolite", optionA: "Dents qui repoussent chaque mois", optionB: "Cheveux qui changent de couleur chaque jour" },
  { id: 235, category: "insolite", optionA: "Devenir réellement hypnotisable", optionB: "Pouvoir hypnotiser sans le contrôler" },
  { id: 236, category: "insolite", optionA: "Pondre une perle quand tu rigoles", optionB: "Cracher une larme dorée quand tu pleures" },
  { id: 237, category: "insolite", optionA: "Peau qui change de couleur selon ton humeur", optionB: "Peau qui devient transparente sous stress" },
  { id: 238, category: "insolite", optionA: "Avoir 3 estomacs", optionB: "2 cœurs" },
  { id: 239, category: "insolite", optionA: "Être en mode caméléon", optionB: "En mode fluo permanent" },
  { id: 240, category: "insolite", optionA: "Te transformer en pizza si tu en manges", optionB: "En licorne si tu mens" },
  { id: 241, category: "insolite", optionA: "Pouvoir parler à ton reflet", optionB: "À ton ombre" },
  { id: 242, category: "insolite", optionA: "Avoir une voix de Mickey", optionB: "Une voix de Dark Vador" },
  { id: 243, category: "insolite", optionA: "Avoir un super odorat de chien", optionB: "Une vue d'aigle" },
  { id: 244, category: "insolite", optionA: "Recevoir des notifications dans la tête", optionB: "Avoir un GPS interne" },
  { id: 245, category: "insolite", optionA: "Pouvoir éternuer des chips", optionB: "Pleurer du chocolat" },
  { id: 246, category: "insolite", optionA: "Être doué pour parler aux fantômes", optionB: "Aux extraterrestres" },
  { id: 247, category: "insolite", optionA: "Te dupliquer mais sans contrôle", optionB: "Être à 2 endroits par téléportation contrôlée" },
  { id: 248, category: "insolite", optionA: "Manger seulement avec une cuillère minuscule", optionB: "Avec des baguettes de 1 m" },
  { id: 249, category: "insolite", optionA: "Avoir un assistant invisible chiant", optionB: "Un coach personnel ultra strict" },
  { id: 250, category: "insolite", optionA: "Vivre sous l'eau 1 an", optionB: "Dans l'espace 1 an" },
  { id: 251, category: "insolite", optionA: "Toujours être suivi d'un nuage de pluie", optionB: "D'un essaim de papillons" },
  { id: 252, category: "insolite", optionA: "Recevoir un cadeau bizarre par jour", optionB: "Donner un objet bizarre tous les jours" },
  { id: 253, category: "insolite", optionA: "Avoir une oreille qui bouge toute seule", optionB: "Un orteil indépendant" },
  { id: 254, category: "insolite", optionA: "Voir le monde en cartoon", optionB: "En noir et blanc" },
  { id: 255, category: "insolite", optionA: "Tous tes cheveux blanchissent en une nuit", optionB: "Devenir totalement chauve" },
  { id: 256, category: "insolite", optionA: "Avoir un perroquet qui répète tes pensées", optionB: "Un chat qui te juge à voix haute" },
  { id: 257, category: "insolite", optionA: "Manger seulement avec tes pieds", optionB: "Boire en aspirant par le nez" },
  { id: 258, category: "insolite", optionA: "Tousser des bulles", optionB: "Éternuer des étincelles" },
  { id: 259, category: "insolite", optionA: "Mesurer 30 cm de plus", optionB: "30 cm de moins" },
  { id: 260, category: "insolite", optionA: "Avoir un alter ego officiel", optionB: "Une marionnette qui parle pour toi" },
  { id: 261, category: "insolite", optionA: "Devenir vert en buvant de l'eau", optionB: "Bleu en mangeant" },
  { id: 262, category: "insolite", optionA: "Toujours porter un costume de banane", optionB: "Une combinaison de plongée" },
  { id: 263, category: "insolite", optionA: "Recevoir une chanson improvisée à chaque rencontre", optionB: "Un slam à chaque fin de phrase" },
  { id: 264, category: "insolite", optionA: "Pouvoir transformer l'eau en jus", optionB: "La nourriture en cendre" },
  { id: 265, category: "insolite", optionA: "Avoir une moustache permanente quel que soit ton genre", optionB: "Plus de pilosité partout" },
  { id: 266, category: "insolite", optionA: "Apparaître dans tous les selfies des inconnus", optionB: "Disparaître de toutes tes propres photos" },
  { id: 267, category: "insolite", optionA: "Avoir un zoom oculaire", optionB: "Une vision nocturne d'animal" },
  { id: 268, category: "insolite", optionA: "Léviter à 10 cm en permanence", optionB: "Marcher sur les murs" },
  { id: 269, category: "insolite", optionA: "Avoir un mode pause de 1 seconde", optionB: "Un mode rewind 5 secondes" },
  { id: 270, category: "insolite", optionA: "Prédire la météo à 100 %", optionB: "Prédire les bouchons à 100 %" },

  // ========================= ETHIQUE (271-320) =====================
  { id: 271, category: "ethique", optionA: "Voler les riches pour donner aux pauvres", optionB: "Tout laisser tel quel" },
  { id: 272, category: "ethique", optionA: "Sauver 1 inconnu par jour mais perdre la mémoire", optionB: "Mémoire intacte mais ne sauver personne" },
  { id: 273, category: "ethique", optionA: "Mentir pour sauver une vie", optionB: "Dire la vérité quoi qu'il arrive" },
  { id: 274, category: "ethique", optionA: "Tuer un dictateur de tes mains", optionB: "Le laisser vivre et faire 10 000 morts" },
  { id: 275, category: "ethique", optionA: "Sauver ton enfant", optionB: "Sauver 5 inconnus" },
  { id: 276, category: "ethique", optionA: "Donner tout ton argent aux pauvres", optionB: "Le garder pour ta famille" },
  { id: 277, category: "ethique", optionA: "Trahir un ami pour sauver 100 vies", optionB: "Ne rien dire et laisser mourir" },
  { id: 278, category: "ethique", optionA: "Mettre un secret au grand jour", optionB: "Le garder pour préserver la paix" },
  { id: 279, category: "ethique", optionA: "Travailler dans une boîte non éthique pour 200 k€", optionB: "Bosser éthique au SMIC" },
  { id: 280, category: "ethique", optionA: "Refuser de témoigner pour sauver un coupable proche", optionB: "Témoigner et le trahir" },
  { id: 281, category: "ethique", optionA: "Sauver un humain inconnu", optionB: "Sauver 10 chiens" },
  { id: 282, category: "ethique", optionA: "Forcer un don d'organe pour sauver ton enfant", optionB: "Le laisser mourir" },
  { id: 283, category: "ethique", optionA: "Faire la morale à un ami toxique", optionB: "Te taire pour ne pas le perdre" },
  { id: 284, category: "ethique", optionA: "Sauver ton père", optionB: "Sauver le président" },
  { id: 285, category: "ethique", optionA: "Aider un ennemi en danger", optionB: "Le laisser souffrir" },
  { id: 286, category: "ethique", optionA: "Manger du foie gras quotidien", optionB: "Du veau élevé en cage" },
  { id: 287, category: "ethique", optionA: "Pirater un site pour démasquer une arnaque", optionB: "Laisser faire" },
  { id: 288, category: "ethique", optionA: "Te taire face à une injustice par sécurité", optionB: "Parler et risquer ta carrière" },
  { id: 289, category: "ethique", optionA: "Décider d'arrêter les machines pour un proche", optionB: "Le laisser vivre comateux 20 ans" },
  { id: 290, category: "ethique", optionA: "Avorter en cas de viol", optionB: "Garder l'enfant" },
  { id: 291, category: "ethique", optionA: "Devenir lanceur d'alerte au prix de ta liberté", optionB: "Garder le silence et être tranquille" },
  { id: 292, category: "ethique", optionA: "Couper la jambe d'un proche pour le sauver", optionB: "Le laisser mourir intact" },
  { id: 293, category: "ethique", optionA: "Sauver une œuvre d'art unique de l'histoire", optionB: "Sauver un inconnu" },
  { id: 294, category: "ethique", optionA: "Effacer ta dette par fraude", optionB: "Bosser 20 ans pour la rembourser" },
  { id: 295, category: "ethique", optionA: "Sauver un enfant", optionB: "Sauver ton parent âgé" },
  { id: 296, category: "ethique", optionA: "Trahir ton pays par conviction", optionB: "Te conformer" },
  { id: 297, category: "ethique", optionA: "Mentir à ton enfant sur sa vraie origine", optionB: "Lui dire la vérité douloureuse" },
  { id: 298, category: "ethique", optionA: "Adopter un enfant en danger", optionB: "Donner l'argent à une asso pour sauver 10 enfants" },
  { id: 299, category: "ethique", optionA: "Sauver un milliardaire qui finance la recherche", optionB: "Sauver 5 SDF" },
  { id: 300, category: "ethique", optionA: "Cacher la honte d'un proche aux dépens d'un inconnu", optionB: "Faire éclater la vérité" },
  { id: 301, category: "ethique", optionA: "Vivre une vie altruiste mais malheureuse", optionB: "Égoïste mais épanouie" },
  { id: 302, category: "ethique", optionA: "Refuser un boulot d'armement à 500 k€/an", optionB: "Accepter" },
  { id: 303, category: "ethique", optionA: "Saboter un projet immoral", optionB: "Le laisser réussir" },
  { id: 304, category: "ethique", optionA: "Choisir l'euthanasie pour un proche en accord", optionB: "Lutter contre vents et marées" },
  { id: 305, category: "ethique", optionA: "Trahir ta meilleure amie pour la vérité", optionB: "La couvrir" },
  { id: 306, category: "ethique", optionA: "Donner tes économies pour un don d'organe", optionB: "Garder pour ta retraite" },
  { id: 307, category: "ethique", optionA: "Refuser une greffe pour qu'elle aille à un enfant", optionB: "La prendre" },
  { id: 308, category: "ethique", optionA: "Cacher une preuve qui sauverait un inconnu mais condamnerait un proche", optionB: "Faire le contraire" },
  { id: 309, category: "ethique", optionA: "Être juré pour condamner un coupable de ta famille", optionB: "Refuser et se récuser" },
  { id: 310, category: "ethique", optionA: "Faire signer un contrat manipulé pour ton bien", optionB: "Renoncer" },
  { id: 311, category: "ethique", optionA: "Aider un migrant clandestin", optionB: "Le dénoncer (selon la loi)" },
  { id: 312, category: "ethique", optionA: "Subir une injustice silencieux", optionB: "Hurler et risquer la prison" },
  { id: 313, category: "ethique", optionA: "Voler de la nourriture pour ton enfant qui meurt de faim", optionB: "Le laisser à son sort" },
  { id: 314, category: "ethique", optionA: "Lyncher publiquement un agresseur", optionB: "Pardonner publiquement" },
  { id: 315, category: "ethique", optionA: "Désobéir aux ordres dans un job", optionB: "Obéir et faire du mal" },
  { id: 316, category: "ethique", optionA: "Élever ton enfant en lui laissant choisir son genre", optionB: "Lui imposer un genre" },
  { id: 317, category: "ethique", optionA: "Refuser une formation imposée injuste", optionB: "Accepter et garder ton job" },
  { id: 318, category: "ethique", optionA: "Diffuser une preuve volée pour la justice", optionB: "Respecter la loi" },
  { id: 319, category: "ethique", optionA: "Saboter une élection pour un meilleur candidat", optionB: "Laisser perdre" },
  { id: 320, category: "ethique", optionA: "Élever des enfants athées", optionB: "Religieux pratiquants" },

  // ========================= COUPLE (321-370) ======================
  { id: 321, category: "couple", optionA: "Découvrir que ton/ta partenaire t'a trompé une fois", optionB: "Plusieurs fois en émotionnel sans coucher" },
  { id: 322, category: "couple", optionA: "Que ton/ta partenaire vibe sur tes potes", optionB: "Sur ton/ta meilleur(e) ami(e)" },
  { id: 323, category: "couple", optionA: "Vivre un amour intense 5 ans", optionB: "Une relation tranquille 50 ans" },
  { id: 324, category: "couple", optionA: "Avoir un mariage de rêve à 100 k€", optionB: "Voyager 10 ans avec ton/ta partenaire" },
  { id: 325, category: "couple", optionA: "Découvrir le passé sentimental complet de ton/ta partenaire", optionB: "Garder le mystère" },
  { id: 326, category: "couple", optionA: "Te marier avec ton premier amour", optionB: "Avec une nouvelle rencontre passionnante" },
  { id: 327, category: "couple", optionA: "Que ton/ta partenaire passe une nuit blanche avec son ex", optionB: "Avec un parfait inconnu" },
  { id: 328, category: "couple", optionA: "Embrasser quelqu'un par accident sans rien dire", optionB: "Tout avouer" },
  { id: 329, category: "couple", optionA: "Que ton/ta partenaire t'embrasse devant ses parents", optionB: "Devant tes parents" },
  { id: 330, category: "couple", optionA: "Vivre en couple sans dispute", optionB: "Avec disputes mais réconciliations passionnées" },
  { id: 331, category: "couple", optionA: "Apprendre que ton/ta partenaire a un enfant caché", optionB: "Une famille parallèle" },
  { id: 332, category: "couple", optionA: "Avoir une relation à distance pendant 5 ans", optionB: "Une rupture maintenant" },
  { id: 333, category: "couple", optionA: "Faire une pause de 6 mois sans contact", optionB: "Rompre direct" },
  { id: 334, category: "couple", optionA: "Que ton/ta partenaire choisisse ses parents au lieu de toi", optionB: "Te choisisse au lieu d'eux" },
  { id: 335, category: "couple", optionA: "Vivre avec ton/ta partenaire H24", optionB: "Habiter séparément à vie" },
  { id: 336, category: "couple", optionA: "Te marier sans amour pour la sécurité", optionB: "Vivre seul amoureux" },
  { id: 337, category: "couple", optionA: "Aimer quelqu'un qui ne t'aime pas", optionB: "Être aimé(e) par quelqu'un que tu n'aimes pas" },
  { id: 338, category: "couple", optionA: "Tomber amoureux pendant un mariage déjà programmé", optionB: "Y renoncer juste avant" },
  { id: 339, category: "couple", optionA: "Avoir une relation polyamoureuse", optionB: "Strictement monogame" },
  { id: 340, category: "couple", optionA: "Vivre avec un fantôme du passé qui revient", optionB: "Avancer définitivement sans regard arrière" },
  { id: 341, category: "couple", optionA: "Sacrifier ta carrière pour ton couple", optionB: "Ton couple pour ta carrière" },
  { id: 342, category: "couple", optionA: "Découvrir un journal intime de ton/ta partenaire", optionB: "Lui montrer le tien en intégralité" },
  { id: 343, category: "couple", optionA: "Pardonner une trahison une seule fois", optionB: "Ne jamais pardonner quoi qu'il arrive" },
  { id: 344, category: "couple", optionA: "Qu'iel kiffe physiquement quelqu'un d'autre sans agir", optionB: "Qu'iel agisse sans en parler" },
  { id: 345, category: "couple", optionA: "Coup de foudre avec quelqu'un déjà en couple", optionB: "Avec un inconnu loin et inaccessible" },
  { id: 346, category: "couple", optionA: "Faire l'amour 1 fois par mois mais profond", optionB: "Souvent mais sans connexion émotionnelle" },
  { id: 347, category: "couple", optionA: "Te marier à 20 ans pour la vie", optionB: "À 60 ans pour quelques années" },
  { id: 348, category: "couple", optionA: "Quitter quelqu'un que tu aimes", optionB: "Rester avec quelqu'un que tu n'aimes plus" },
  { id: 349, category: "couple", optionA: "Que ton/ta partenaire ne change jamais", optionB: "Qu'iel évolue radicalement" },
  { id: 350, category: "couple", optionA: "Apprendre que ton/ta partenaire ne veut plus d'enfants", optionB: "Qu'iel en veut soudain 5" },
  { id: 351, category: "couple", optionA: "Avoir un coup d'un soir mémorable", optionB: "Une histoire sans cul mais profonde" },
  { id: 352, category: "couple", optionA: "Découvrir le crush secret de ton/ta partenaire", optionB: "Lui révéler le tien" },
  { id: 353, category: "couple", optionA: "Vivre dans la maison familiale de tes beaux-parents", optionB: "Sans logement à toi" },
  { id: 354, category: "couple", optionA: "Que ton/ta partenaire apprenne ton plus gros fantasme", optionB: "Que tu apprennes le sien" },
  { id: 355, category: "couple", optionA: "Te marier avec quelqu'un d'introverti", optionB: "D'extraverti exubérant" },
  { id: 356, category: "couple", optionA: "Apprendre que ton/ta partenaire a menti sur son âge", optionB: "Sur son métier" },
  { id: 357, category: "couple", optionA: "Avoir une relation pleine de cadeaux luxueux", optionB: "Pleine d'attentions sans aucun cadeau" },
  { id: 358, category: "couple", optionA: "Aimer quelqu'un qui s'éloigne", optionB: "Qui s'accroche trop" },
  { id: 359, category: "couple", optionA: "Que ton/ta partenaire fasse une crise de jalousie monstre", optionB: "Une crise d'indifférence totale" },
  { id: 360, category: "couple", optionA: "Faire une demande publique gigantesque", optionB: "Très intime, juste à deux" },
  { id: 361, category: "couple", optionA: "Aller voir un coach matrimonial à deux", optionB: "Y aller chacun seul" },
  { id: 362, category: "couple", optionA: "Avouer un fantasme à ton/ta partenaire qui te juge", optionB: "Le garder pour toi à vie" },
  { id: 363, category: "couple", optionA: "Que ton/ta partenaire ait une amitié intime forte avec quelqu'un d'autre", optionB: "N'ait aucun(e) ami(e)" },
  { id: 364, category: "couple", optionA: "Apprendre la mort de ton ex", optionB: "De ton crush actuel" },
  { id: 365, category: "couple", optionA: "Tomber amoureux de la meilleure amie de ton/ta partenaire", optionB: "Du frère / de la sœur" },
  { id: 366, category: "couple", optionA: "Te marier rapidement après 6 mois", optionB: "Attendre 7 ans pour être sûr(e)" },
  { id: 367, category: "couple", optionA: "Découvrir que ta première fois était filmée", optionB: "Que tes premiers baisers l'étaient" },
  { id: 368, category: "couple", optionA: "Que ton/ta partenaire ait un crush insta sur quelqu'un", optionB: "Sur ton boss" },
  { id: 369, category: "couple", optionA: "Recevoir une lettre d'amour 10 ans après", optionB: "Envoyer une lettre 10 ans trop tard" },
  { id: 370, category: "couple", optionA: "Te faire larguer le jour de ton anniversaire", optionB: "Le jour de Noël" },

  // ========================= POP CULTURE (371-400) =================
  { id: 371, category: "pop", optionA: "Vivre 1 jour dans Harry Potter", optionB: "Dans Le Seigneur des Anneaux" },
  { id: 372, category: "pop", optionA: "Être un personnage de Game of Thrones", optionB: "De Breaking Bad" },
  { id: 373, category: "pop", optionA: "Vivre dans Mario Kart", optionB: "Dans GTA" },
  { id: 374, category: "pop", optionA: "Avoir le pouvoir de Spider-Man", optionB: "De Wonder Woman" },
  { id: 375, category: "pop", optionA: "Combattre Thanos avec un gant", optionB: "Voldemort sans baguette" },
  { id: 376, category: "pop", optionA: "Devenir un Pokémon", optionB: "Devenir un dresseur" },
  { id: 377, category: "pop", optionA: "Vivre dans Stranger Things", optionB: "Dans The Last of Us" },
  { id: 378, category: "pop", optionA: "Avoir Iron Man comme père", optionB: "Joker comme oncle" },
  { id: 379, category: "pop", optionA: "Mourir comme dans Final Destination", optionB: "Comme dans Saw" },
  { id: 380, category: "pop", optionA: "Vivre dans Squid Game", optionB: "Dans Hunger Games" },
  { id: 381, category: "pop", optionA: "Avoir un dragon de GoT", optionB: "Un patronus de Harry Potter" },
  { id: 382, category: "pop", optionA: "Sortir avec Hermione", optionB: "Avec Eleven" },
  { id: 383, category: "pop", optionA: "Boire un verre avec Tony Stark", optionB: "Avec Capitaine Jack Sparrow" },
  { id: 384, category: "pop", optionA: "Faire un duel avec Goku", optionB: "Avec Naruto" },
  { id: 385, category: "pop", optionA: "Vivre 1 an dans Westworld", optionB: "Dans Black Mirror" },
  { id: 386, category: "pop", optionA: "Être un Avenger", optionB: "Un X-Men" },
  { id: 387, category: "pop", optionA: "Posséder la Death Star", optionB: "La baguette de sureau" },
  { id: 388, category: "pop", optionA: "Combattre un xénomorphe", optionB: "Un Predator" },
  { id: 389, category: "pop", optionA: "Avoir Batman comme mentor", optionB: "Iron Man" },
  { id: 390, category: "pop", optionA: "Vivre dans Friends", optionB: "Dans How I Met Your Mother" },
  { id: 391, category: "pop", optionA: "Affronter Sauron", optionB: "Le Roi Lion adulte" },
  { id: 392, category: "pop", optionA: "Visiter Hogwarts", optionB: "Visiter Naboo" },
  { id: 393, category: "pop", optionA: "Devenir un Sith", optionB: "Un Jedi" },
  { id: 394, category: "pop", optionA: "Avoir KITT", optionB: "La DeLorean" },
  { id: 395, category: "pop", optionA: "Te battre avec Bruce Lee", optionB: "Avec Chuck Norris" },
  { id: 396, category: "pop", optionA: "Mourir comme un personnage Marvel", optionB: "Un personnage DC" },
  { id: 397, category: "pop", optionA: "Vivre 1 saison dans Lost", optionB: "Dans The Walking Dead" },
  { id: 398, category: "pop", optionA: "Avoir Pikachu comme animal", optionB: "Avoir Stitch" },
  { id: 399, category: "pop", optionA: "Échanger une vie avec ton acteur préféré", optionB: "Avec ton chanteur préféré" },
  { id: 400, category: "pop", optionA: "Visiter le métavers de Ready Player One", optionB: "La Matrice de Matrix" },

  // ========================== GAMING (401-450) =====================
  { id: 401, category: "gaming", optionA: "Jouer en mode hardcore sans sauvegarde", optionB: "Subir un crash juste avant la save" },
  { id: 402, category: "gaming", optionA: "Faire équipe avec un AFK", optionB: "Avec un micro ouvert qui mange ses chips" },
  { id: 403, category: "gaming", optionA: "Avoir le ping de 500", optionB: "Tomber sur un smurf chaque ranked" },
  { id: 404, category: "gaming", optionA: "Perdre tous tes skins légendaires", optionB: "Recommencer ton compte de zéro" },
  { id: 405, category: "gaming", optionA: "Que tes parents lisent ton chat in-game", optionB: "Que ta crush voie ton stat tracker" },
  { id: 406, category: "gaming", optionA: "Camper toute la partie pour gagner", optionB: "Rush sans réfléchir et finir 0/15" },
  { id: 407, category: "gaming", optionA: "Avoir un teammate Tryhard zéro fun", optionB: "Un teammate fun mais nul" },
  { id: 408, category: "gaming", optionA: "Te taper un ban 1 jour pour rien", optionB: "Tomber sur un cheater en finale" },
  { id: 409, category: "gaming", optionA: "Perdre 30 LP par lose", optionB: "Gagner que 8 LP par win" },
  { id: 410, category: "gaming", optionA: "Jouer avec un clavier collant", optionB: "Une souris qui double-clique" },
  { id: 411, category: "gaming", optionA: "Finir le jeu sans aucune side quest", optionB: "Y passer 200h et oublier le scénario principal" },
  { id: 412, category: "gaming", optionA: "Manger pendant la game et lag", optionB: "Avoir faim mais carry l'équipe" },
  { id: 413, category: "gaming", optionA: "Perdre une finale sur un disconnect", optionB: "Sur un teamkill" },
  { id: 414, category: "gaming", optionA: "Speedrun un jeu en 4h", optionB: "Le platine en 200h" },
  { id: 415, category: "gaming", optionA: "Jouer avec un casque qui grésille", optionB: "Sans son du tout" },
  { id: 416, category: "gaming", optionA: "Que ta ranked soit visible publiquement", optionB: "Que ton historique de jeu solo soit révélé" },
  { id: 417, category: "gaming", optionA: "Gagner un tournoi en triche", optionB: "Finir top 3 honnêtement" },
  { id: 418, category: "gaming", optionA: "Avoir des skins mais peakable Bronze", optionB: "Ranked Diamant en skin défaut" },
  { id: 419, category: "gaming", optionA: "Casser ton clavier de rage", optionB: "Crier dans le micro et te faire report" },
  { id: 420, category: "gaming", optionA: "Jouer 10h non-stop sans pause", optionB: "1h par jour sans rater une seule" },
  { id: 421, category: "gaming", optionA: "Spoiler la fin d'un jeu story-driven", optionB: "Te faire spoiler un boss caché" },
  { id: 422, category: "gaming", optionA: "Ne plus jamais jouer en multi", optionB: "Plus jamais en solo" },
  { id: 423, category: "gaming", optionA: "Perdre toutes tes saves Pokémon d'enfance", optionB: "Tes screenshots Steam complets" },
  { id: 424, category: "gaming", optionA: "Avoir un stream avec 0 viewer", optionB: "Avec un troll qui spam ta vie privée" },
  { id: 425, category: "gaming", optionA: "Te faire ouvrir Discord par ta mère", optionB: "Par ta crush juste après une rage" },
  { id: 426, category: "gaming", optionA: "Que ton gaming setup brûle", optionB: "Que ton compte Steam soit hack" },
  { id: 427, category: "gaming", optionA: "Tilt 5 games d'affilée", optionB: "Win 5 games mais avec un carry chiant" },
  { id: 428, category: "gaming", optionA: "Avoir un ami qui spoile chaque jeu", optionB: "Un ami qui critique chaque jeu que t'aimes" },
  { id: 429, category: "gaming", optionA: "Perdre la finale après être en lead 3-0", optionB: "Win sur un comeback chaotique" },
  { id: 430, category: "gaming", optionA: "Jouer compétitif 20h/semaine en silence", optionB: "Casual 4h en stream avec public" },
  { id: 431, category: "gaming", optionA: "Que ton main soit nerf à mort", optionB: "Que tu doives apprendre un nouveau perso" },
  { id: 432, category: "gaming", optionA: "Ouvrir un loot mythique en stream", optionB: "Le drop tout seul et personne ne te croit" },
  { id: 433, category: "gaming", optionA: "Avoir un boss qui te ban sur Twitch", optionB: "Un boss qui te suit et te juge" },
  { id: 434, category: "gaming", optionA: "Tomber amoureux d'un PNJ", optionB: "Romance un coéquipier random en MMO" },
  { id: 435, category: "gaming", optionA: "Que la patch note ruine ton perso", optionB: "Que ta map préférée soit retirée" },
  { id: 436, category: "gaming", optionA: "Perdre sur un kick parental", optionB: "Sur une coupure de courant" },
  { id: 437, category: "gaming", optionA: "Te faire pwn par un kid de 12 ans", optionB: "Par ton propre frère qui n'a jamais joué" },
  { id: 438, category: "gaming", optionA: "Que tes parents te coupent le wifi en finale", optionB: "Qu'ils mettent l'aspirateur en stream" },
  { id: 439, category: "gaming", optionA: "Acheter un season pass que tu n'utilises pas", optionB: "Skip un jeu GOTY pour économiser" },
  { id: 440, category: "gaming", optionA: "Lire un guide complet avant de jouer", optionB: "Découvrir tout en blind run" },
  { id: 441, category: "gaming", optionA: "Avoir 5 amis qui jouent à un jeu sans toi", optionB: "Forcer tes amis à jouer un jeu qu'ils détestent" },
  { id: 442, category: "gaming", optionA: "Battre Malenia au premier essai", optionB: "Battre Sephiroth en mode normal" },
  { id: 443, category: "gaming", optionA: "Casual qui carry les Diamants", optionB: "Diamant qui se fait carry par un Bronze" },
  { id: 444, category: "gaming", optionA: "Subir le pire matchmaking de ta vie", optionB: "Le meilleur mais sur un patch broken" },
  { id: 445, category: "gaming", optionA: "Perdre un tournoi LAN en ratant un click", optionB: "Le perdre car tu as oublié ta souris" },
  { id: 446, category: "gaming", optionA: "Que ton PC freeze à chaque clutch", optionB: "Que ton chat saute sur ton clavier" },
  { id: 447, category: "gaming", optionA: "Que ton VOD review révèle un fail énorme", optionB: "Que tes mate retiennent ce fail à vie" },
  { id: 448, category: "gaming", optionA: "Spammer le chat after a kill", optionB: "Ne jamais répondre dans le chat" },
  { id: 449, category: "gaming", optionA: "Jouer un jeu PvP injouable solo", optionB: "Solo grind un MMO mort" },
  { id: 450, category: "gaming", optionA: "Avoir un coach mais zéro motivation", optionB: "Beaucoup de motivation mais zéro talent" },

  // ========================= INTERNET (451-500) ====================
  { id: 451, category: "internet", optionA: "Que tes brouillons Twitter soient publiés", optionB: "Que ton historique YouTube soit public" },
  { id: 452, category: "internet", optionA: "Devenir viral pour une vidéo gênante", optionB: "Pour une opinion mal formulée" },
  { id: 453, category: "internet", optionA: "Te faire screen et ratio par tes potes", optionB: "Par 2 millions d'inconnus" },
  { id: 454, category: "internet", optionA: "Que ton compte close friends fuite", optionB: "Que tes DMs avec ta crush leak" },
  { id: 455, category: "internet", optionA: "Suivre seulement ta famille", optionB: "Que ta famille ne te suive pas" },
  { id: 456, category: "internet", optionA: "Perdre tes abonnés et recommencer", optionB: "Garder tes abonnés mais brûler ta réputation" },
  { id: 457, category: "internet", optionA: "Te faire rate-limiter sur tous tes apps", optionB: "Avoir 0 notification pendant 1 mois" },
  { id: 458, category: "internet", optionA: "Que ton For You Page soit projeté à un mariage", optionB: "Sur l'écran d'un Apple Store" },
  { id: 459, category: "internet", optionA: "Devoir poster une story par jour 1 an", optionB: "Te faire bann 1 mois sans prévenir" },
  { id: 460, category: "internet", optionA: "Que ton ex like ta photo de 2014", optionB: "Que ton boss like ton selfie miroir" },
  { id: 461, category: "internet", optionA: "Que ton historique TikTok devienne public", optionB: "Tes recherches Google des 7 derniers jours" },
  { id: 462, category: "internet", optionA: "Perdre tous les follows mutuals", optionB: "Tous les commentaires de tes posts" },
  { id: 463, category: "internet", optionA: "Recevoir 1000 likes mais 50 commentaires haine", optionB: "10 likes mais que des compliments" },
  { id: 464, category: "internet", optionA: "Te faire shadowban sans prévenir", optionB: "Voir tes vues divisées par 100" },
  { id: 465, category: "internet", optionA: "Vivre sans Spotify", optionB: "Sans Netflix" },
  { id: 466, category: "internet", optionA: "Perdre TikTok", optionB: "Perdre Instagram" },
  { id: 467, category: "internet", optionA: "Que ton Spotify Wrapped trahisse tes guilty pleasures", optionB: "Que ton historique Netflix soit projeté à ta famille" },
  { id: 468, category: "internet", optionA: "Activer ta caméra sur un appel surprise", optionB: "Ton micro pendant que tu chantes seul" },
  { id: 469, category: "internet", optionA: "Te faire taguer dans une story moche", optionB: "Te faire untag par tes meilleurs amis" },
  { id: 470, category: "internet", optionA: "Devenir éphémèrement très connu sur Twitter", optionB: "Petit creator stable sur YouTube" },
  { id: 471, category: "internet", optionA: "Que ton vocal de 8 minutes soit leaked", optionB: "Que tes captures d'écran de DMs leakent" },
  { id: 472, category: "internet", optionA: "Avoir un troll personnel qui te suit partout", optionB: "Un fan ultra obsessionnel" },
  { id: 473, category: "internet", optionA: "Devoir publier 10 selfies par jour", optionB: "Ne plus jamais montrer ton visage" },
  { id: 474, category: "internet", optionA: "Que ton compte secondaire soit révélé", optionB: "Que ton compte principal soit hack" },
  { id: 475, category: "internet", optionA: "Recevoir un DM gênant de ton patron", optionB: "Envoyer un meme cringe par erreur à un client" },
  { id: 476, category: "internet", optionA: "Avoir des notifs muted pendant 1 an", optionB: "Recevoir 200 notifs par jour" },
  { id: 477, category: "internet", optionA: "Vivre sans dark mode", optionB: "Sans correcteur orthographique" },
  { id: 478, category: "internet", optionA: "Stalker ton crush 3h par jour", optionB: "Te faire stalker sans rien savoir" },
  { id: 479, category: "internet", optionA: "Faire une story sondage qui flop", optionB: "Une story sondage qui révèle un avis embarrassant" },
  { id: 480, category: "internet", optionA: "Que ta liste d'abonnements soit révélée", optionB: "Que ton historique de likes des 5 dernières années le soit" },
  { id: 481, category: "internet", optionA: "Devoir lire un commentaire haine par jour à voix haute", optionB: "Un compliment cringe à voix haute" },
  { id: 482, category: "internet", optionA: "Avoir une app non-stop qui leak ta loc", optionB: "Une app qui poste tes screenshots" },
  { id: 483, category: "internet", optionA: "Te faire rage-quit par un groupe WhatsApp", optionB: "Être ajouté de force dans 10 groupes random" },
  { id: 484, category: "internet", optionA: "Devoir documenter chaque repas en story", optionB: "Plus jamais poster de bouffe" },
  { id: 485, category: "internet", optionA: "Que ta meuf voie tes likes Instagram", optionB: "Tes liked tweets de 2017" },
  { id: 486, category: "internet", optionA: "Travailler avec un manager TikTok cringe", optionB: "Un manager LinkedIn ultra rigide" },
  { id: 487, category: "internet", optionA: "Subir un piratage de ton iCloud", optionB: "Perdre ton compte Insta sans backup" },
  { id: 488, category: "internet", optionA: "Que ton smartphone refuse de charger", optionB: "Qu'il fonctionne mais que la 4G soit toujours à 1 barre" },
  { id: 489, category: "internet", optionA: "Lire les CGU avant chaque app", optionB: "Cliquer accepter les yeux fermés à vie" },
  { id: 490, category: "internet", optionA: "Que ta brossanger Google ouvre tous tes onglets perso", optionB: "Que ta mère lise ton incognito" },
  { id: 491, category: "internet", optionA: "Subir une coupure d'internet 1 semaine", optionB: "Avoir internet mais à 56k" },
  { id: 492, category: "internet", optionA: "Que ton patron te suive sur LinkedIn", optionB: "Sur Insta avec un compte privé" },
  { id: 493, category: "internet", optionA: "Reposter un meme en croyant qu'il est nouveau", optionB: "Manquer un meme et le découvrir 2 ans après" },
  { id: 494, category: "internet", optionA: "Faire une faute énorme dans un tweet à 50k likes", optionB: "Supprimer un tweet qui aurait fait 100k likes" },
  { id: 495, category: "internet", optionA: "Avoir 10 onglets ouverts en permanence", optionB: "Ouvrir un nouveau tab pour chaque truc" },
  { id: 496, category: "internet", optionA: "Que ta TL soit 100 % brainrot", optionB: "100 % news politique" },
  { id: 497, category: "internet", optionA: "Que ta playlist de chant sous la douche fuite", optionB: "Que ton historique d'achats Amazon soit projeté" },
  { id: 498, category: "internet", optionA: "Perdre 1000 abonnés en une nuit", optionB: "Tomber dans le purgatoire de l'algo 6 mois" },
  { id: 499, category: "internet", optionA: "Tomber dans le piège d'un fake giveaway", optionB: "D'un faux mail SAV très bien fait" },
  { id: 500, category: "internet", optionA: "Que ton Replika t'envoie des messages bizarres", optionB: "Que ChatGPT te ghoste pour 2 jours" },

  // ========================== BEAUF (501-550) ======================
  { id: 501, category: "beauf", optionA: "Boire du rosé tiède au camping", optionB: "Du Ricard sans glaçon en plein cagnard" },
  { id: 502, category: "beauf", optionA: "Apéro saucisson-pastis 4h non-stop", optionB: "BBQ sous la pluie battante" },
  { id: 503, category: "beauf", optionA: "Aller au Leclerc en jogging-claquettes", optionB: "Au Carrefour en marcel troué" },
  { id: 504, category: "beauf", optionA: "Un voisin qui tond le dimanche à 8h", optionB: "Un voisin qui fait karaoké à 3h" },
  { id: 505, category: "beauf", optionA: "Tomber dans un débat politique au repas de famille", optionB: "Un débat covid avec ton tonton" },
  { id: 506, category: "beauf", optionA: "Dire \"oh ben ça\" toutes les 3 phrases", optionB: "Finir chaque phrase par \"hein\"" },
  { id: 507, category: "beauf", optionA: "Acheter une voiture customisée Pioneer", optionB: "Une 206 tunée avec aileron" },
  { id: 508, category: "beauf", optionA: "Mettre des chaussettes dans des sandales", optionB: "Un short cargo avec chemisette à motifs" },
  { id: 509, category: "beauf", optionA: "Avoir un tonton qui fume au repas", optionB: "Une tata qui critique tous tes choix de vie" },
  { id: 510, category: "beauf", optionA: "Camping de 15 jours en Bretagne sous la pluie", optionB: "Croisière low-cost avec animation karaoké" },
  { id: 511, category: "beauf", optionA: "Manger une andouillette sans regarder", optionB: "Un saucisson sec entier en 5 minutes" },
  { id: 512, category: "beauf", optionA: "Te marier en plein BBQ familial", optionB: "Sous une bâche dans le jardin de tes parents" },
  { id: 513, category: "beauf", optionA: "Avoir un chien yorkshire qui jappe", optionB: "Un chat persan grognon" },
  { id: 514, category: "beauf", optionA: "Aller en boîte avec ton père", optionB: "Inviter ta mère au paintball" },
  { id: 515, category: "beauf", optionA: "Faire un repas de famille sans wifi", optionB: "Avec ton oncle qui parle complot non-stop" },
  { id: 516, category: "beauf", optionA: "Te baigner en slip kangourou à la plage", optionB: "Avec un caleçon cycliste fluo" },
  { id: 517, category: "beauf", optionA: "Manger du flamby au fromage en dessert", optionB: "Une mousse au chocolat industrielle réchauffée" },
  { id: 518, category: "beauf", optionA: "Faire un karaoké forcé Goldman", optionB: "Un karaoké forcé Florent Pagny" },
  { id: 519, category: "beauf", optionA: "Décorer ta voiture avec un autocollant Bébé à bord", optionB: "Avec un sticker Calvin qui pisse" },
  { id: 520, category: "beauf", optionA: "Subir un repas Tupperware party", optionB: "Une vente à domicile bougies" },
  { id: 521, category: "beauf", optionA: "Faire un tour du Leclerc en kart enfant", optionB: "Voler un caddie pour le ramener chez toi" },
  { id: 522, category: "beauf", optionA: "Boire ton café avec une cuillère qui tape", optionB: "Mâcher la bouche ouverte à table" },
  { id: 523, category: "beauf", optionA: "Avoir un beau-frère qui parle voitures non-stop", optionB: "Une belle-sœur qui parle MLM en boucle" },
  { id: 524, category: "beauf", optionA: "Aller à un mariage en jogging assumé", optionB: "À un enterrement en short hawaïen" },
  { id: 525, category: "beauf", optionA: "Manger les chips à plein son", optionB: "Boire ta soupe en faisant slurp" },
  { id: 526, category: "beauf", optionA: "Vivre dans un lotissement où tout le monde se connaît", optionB: "Dans un immeuble avec voisin chasse d'eau bruyante" },
  { id: 527, category: "beauf", optionA: "Faire un voyage en Espagne all-inclusive", optionB: "Un séjour Disneyland avec 3 enfants criants" },
  { id: 528, category: "beauf", optionA: "Subir un débat \"de mon temps\" au repas", optionB: "Un \"vous les jeunes\" à chaque phrase" },
  { id: 529, category: "beauf", optionA: "Avoir un papy qui rote et dit \"voilà voilà\"", optionB: "Une mamie qui te demande si tu as un copain à chaque seconde" },
  { id: 530, category: "beauf", optionA: "Manger une fondue savoyarde en plein juillet", optionB: "Une raclette en pleine canicule" },
  { id: 531, category: "beauf", optionA: "Faire une partie de pétanque à 4 sous tension", optionB: "Une belote à 4 où les 3 autres trichent" },
  { id: 532, category: "beauf", optionA: "Avoir un radar de cuisine \"Bon appétit !\"", optionB: "Un \"Bonne digestion !\" forcé" },
  { id: 533, category: "beauf", optionA: "Que ton tonton t'invite à pêcher 6h en silence", optionB: "Te traîne au tuning festival" },
  { id: 534, category: "beauf", optionA: "Te coiffer en banane gel des années 90", optionB: "Mettre une queue de cheval rasta" },
  { id: 535, category: "beauf", optionA: "Mettre tes pieds sur la table chez ta belle-mère", optionB: "Roter à table chez ton patron" },
  { id: 536, category: "beauf", optionA: "Aller en vacances dans un mobil-home en Camargue", optionB: "Dans un gîte sans wifi en Lozère" },
  { id: 537, category: "beauf", optionA: "Que tes parents fassent une danse TikTok à un mariage", optionB: "Qu'ils fassent un Madison forcé" },
  { id: 538, category: "beauf", optionA: "Manger du kebab en costume", optionB: "Du jambon-beurre en robe de soirée" },
  { id: 539, category: "beauf", optionA: "Avoir un cousin qui parle valeur de la voiture en boucle", optionB: "Un cousin qui te montre ses NFT" },
  { id: 540, category: "beauf", optionA: "Subir un débat Coca vs Pepsi pendant tout le repas", optionB: "Un débat steak-frites vs entrecôte-purée" },
  { id: 541, category: "beauf", optionA: "Avoir une grand-mère qui te dit \"il faut manger\" toutes les 5 min", optionB: "Un grand-père qui t'appelle \"mon p'tit père\" à 32 ans" },
  { id: 542, category: "beauf", optionA: "Voir tes parents danser sur Dragostea Din Tei", optionB: "Sur Aïe aïe aïe de Carlos" },
  { id: 543, category: "beauf", optionA: "Te taper un BBQ avec saucisses cramées dehors", optionB: "Un repas de fin d'année cantine entreprise" },
  { id: 544, category: "beauf", optionA: "Avoir une chemisette à fleurs imposée", optionB: "Un t-shirt souvenir de Bali à vie" },
  { id: 545, category: "beauf", optionA: "Subir un \"alors quand est-ce que tu nous fais des petits\"", optionB: "Un \"tu travailles dans quoi déjà ?\" à chaque rencontre" },
  { id: 546, category: "beauf", optionA: "Te tatouer un tribal des années 2000", optionB: "Un dauphin sur la cheville" },
  { id: 547, category: "beauf", optionA: "Mettre une compilation Émile et Images en boucle", optionB: "Une compilation Bal d'été 2002" },
  { id: 548, category: "beauf", optionA: "Avoir un enfant prénommé Kévin", optionB: "Un enfant prénommé Brandon" },
  { id: 549, category: "beauf", optionA: "Subir un repas avec ta tante qui parle astrologie", optionB: "Un oncle qui t'explique la crypto qu'il maîtrise pas" },
  { id: 550, category: "beauf", optionA: "Que ta voiture sente le sapin neuf 2 ans", optionB: "Que ton appart sente le pot-au-feu 24/7" },

  // =========================== GENZ (551-600) ======================
  { id: 551, category: "genz", optionA: "Vivre sans le mot \"slay\"", optionB: "Sans \"no cap\"" },
  { id: 552, category: "genz", optionA: "Que ton crush dise \"ratio\" à ton ic", optionB: "Te dise \"L\" à voix haute en public" },
  { id: 553, category: "genz", optionA: "Avoir un brain rot permanent type \"skibidi\"", optionB: "Comprendre toutes les références dictionary 2050" },
  { id: 554, category: "genz", optionA: "Que ta mère découvre le meaning de \"based\"", optionB: "Qu'elle dise \"on fleek\" en public" },
  { id: 555, category: "genz", optionA: "Devoir parler en abréviations Twitter à vie", optionB: "Devoir parler comme un boomer" },
  { id: 556, category: "genz", optionA: "Faire un POV en visio professionnelle", optionB: "Te filmer en train de pleurer pour le contenu" },
  { id: 557, category: "genz", optionA: "Vibe checker tes parents", optionB: "Vibe checker ton boss" },
  { id: 558, category: "genz", optionA: "Que ton aura soit -1000 toute la semaine", optionB: "+1000 mais pour 30 secondes" },
  { id: 559, category: "genz", optionA: "Que ta crush voie ton For You Page brainrot", optionB: "Voie ta playlist secrète sad lo-fi" },
  { id: 560, category: "genz", optionA: "Avoir un main character moment dans le métro", optionB: "Un side character moment toute ta vie" },
  { id: 561, category: "genz", optionA: "Te faire ghoster pour un meilleur rizz", optionB: "Te faire repérer pour ton ohio comportement" },
  { id: 562, category: "genz", optionA: "Avoir le rizz d'un boomer", optionB: "Le swag d'un préado en 2008" },
  { id: 563, category: "genz", optionA: "Vivre dans un univers Roblox forever", optionB: "Dans un univers Minecraft sans craft" },
  { id: 564, category: "genz", optionA: "Que tout le monde dise \"this you ?\" sur tes vieilles photos", optionB: "Que tes screenshots soient ratio chaque jour" },
  { id: 565, category: "genz", optionA: "Que ta playlist soit nuked par l'algo", optionB: "Recevoir une lyric exposée d'un vieux son cringe" },
  { id: 566, category: "genz", optionA: "Avoir un BeReal raté chaque jour", optionB: "Ne jamais voir le notif arriver" },
  { id: 567, category: "genz", optionA: "Que ton aura cosmique soit 0 selon TikTok", optionB: "Que ton aura soit calculée par ta crush" },
  { id: 568, category: "genz", optionA: "Voir ton screenshot screenshoter par ta crush", optionB: "Te faire snapchat ouvert juste pour vérifier ton score" },
  { id: 569, category: "genz", optionA: "Avoir une réputation \"red flag\" sur TikTok", optionB: "Une réputation \"icks\" sur Reddit" },
  { id: 570, category: "genz", optionA: "Que tout le monde te dise \"sigma\" en blague", optionB: "Te dire \"NPC\" sérieusement" },
  { id: 571, category: "genz", optionA: "Avoir un crush parasocial sur un streamer", optionB: "Tomber amoureux d'un personnage IA" },
  { id: 572, category: "genz", optionA: "Devenir villain origin story de ton groupe", optionB: "Le main character qui ruine tout" },
  { id: 573, category: "genz", optionA: "Que ton therapy era dure 5 ans", optionB: "Que ta hot girl walk soit filmée chaque jour" },
  { id: 574, category: "genz", optionA: "Avoir un ick pour chaque crush", optionB: "Donner des icks à tous tes crushs" },
  { id: 575, category: "genz", optionA: "Que ton mood board soit critiqué publiquement", optionB: "Que ton vision board soit photographié" },
  { id: 576, category: "genz", optionA: "Devoir vivre comme une cottagecore girl", optionB: "Comme une dark academia boy" },
  { id: 577, category: "genz", optionA: "Avoir une era \"je m'en occupe pas\" de 6 mois", optionB: "Une era \"je dis oui à tout\" de 6 mois" },
  { id: 578, category: "genz", optionA: "Que ton pod préféré arrête sans prévenir", optionB: "Que ton stream préféré tombe en sub-only" },
  { id: 579, category: "genz", optionA: "Vivre avec le bruit Hawk Tuah dans la tête", optionB: "Avec Skibidi Toilet en boucle" },
  { id: 580, category: "genz", optionA: "Te faire dire que tu es \"très 2018\"", optionB: "Très \"core\" sans précision" },
  { id: 581, category: "genz", optionA: "Avoir un faceclaim qui te ressemble pas", optionB: "Que tes amis soient persuadés que tu ressembles à un perso ennuyeux" },
  { id: 582, category: "genz", optionA: "Que ton main soit nerf à mort dans la vraie vie", optionB: "Que ton perso préféré devienne meta" },
  { id: 583, category: "genz", optionA: "Subir un POV TikTok de ta vie", optionB: "Filmer ton POV de tous les jours" },
  { id: 584, category: "genz", optionA: "Avoir un crush qui dit \"erm acshually\" à chaque phrase", optionB: "Un crush qui dit \"sus\" en 2025" },
  { id: 585, category: "genz", optionA: "Que ton quotidien soit la suite logique de la BoJack era", optionB: "Une suite de Euphoria sans budget" },
  { id: 586, category: "genz", optionA: "Te faire taguer dans une story \"don't ick me out\"", optionB: "Dans une story \"this is my villain era\"" },
  { id: 587, category: "genz", optionA: "Recevoir une lettre d'insultes en gen alpha slang", optionB: "Une lettre d'amour en boomer fr" },
  { id: 588, category: "genz", optionA: "Avoir une crush qui te demande ton MBTI au premier date", optionB: "Ton signe astro et ton ascendant en 30 secondes" },
  { id: 589, category: "genz", optionA: "Devoir poster un GRWM par jour", optionB: "Un Get Unready With Me sans filtre" },
  { id: 590, category: "genz", optionA: "Devenir un TikTok dance trend cringe", optionB: "Un mème Twitter daté" },
  { id: 591, category: "genz", optionA: "Avoir un therapy speak sur tes potes", optionB: "Que ta thérapeute découvre ton FYP" },
  { id: 592, category: "genz", optionA: "Que ton ex se mette en mode \"healing era\"", optionB: "Qu'iel devienne un \"toxic king\" / \"toxic queen\" assumé" },
  { id: 593, category: "genz", optionA: "Que ton TikTok soit pour toi entièrement Dark Mode chaos", optionB: "Entièrement edits sad cinéma" },
  { id: 594, category: "genz", optionA: "Avoir un amour platonique sur un VTuber", optionB: "Sur un personnage de visual novel" },
  { id: 595, category: "genz", optionA: "Devoir crier \"slay queen\" à un repas pro", optionB: "Faire un \"yas king\" à ton boss" },
  { id: 596, category: "genz", optionA: "Vivre une relation entièrement à coups d'audios trends", optionB: "À coups de mèmes échangés sans contexte" },
  { id: 597, category: "genz", optionA: "Avoir un beau-père qui te dit \"on a pas la même mood\"", optionB: "Une belle-mère qui parle aura points" },
  { id: 598, category: "genz", optionA: "Apprendre que ta crush stalk tes archives Insta 2017", optionB: "Que ton boss connaît ton compte Stan" },
  { id: 599, category: "genz", optionA: "Que tes amis te disent \"touch grass\" tous les jours", optionB: "Te disent \"log off\" pour t'aider" },
  { id: 600, category: "genz", optionA: "Vivre dans une ère \"healing\" sans fin", optionB: "Dans une ère \"villain origin\" sans répit" },
];
