// 400+ dilemmes "Tu préfères ?" répartis en 7 catégories.
// Inspirés des classiques du genre (would-you-rather), reformulés en français.

export type Category =
  | "soft"
  | "hot"
  | "trash"
  | "insolite"
  | "ethique"
  | "couple"
  | "pop";

export interface CategoryMeta {
  id: Category;
  label: string;
  emoji: string;
  description: string;
  adult: boolean;
}

export const CATEGORIES: CategoryMeta[] = [
  { id: "soft",     label: "Classique",   emoji: "🟣", description: "Pour tout le monde, sans tabou.",        adult: false },
  { id: "hot",      label: "Hot",         emoji: "🔥", description: "Spicy, 18+. Réservé aux adultes.",        adult: true  },
  { id: "trash",    label: "Trash",       emoji: "💀", description: "Sombre, dérangeant, sans filtre.",        adult: true  },
  { id: "insolite", label: "Insolite",    emoji: "🤪", description: "Bizarre, drôle, complètement WTF.",       adult: false },
  { id: "ethique",  label: "Éthique",     emoji: "⚖️", description: "Dilemmes moraux qui font débattre.",      adult: false },
  { id: "couple",   label: "Couple",      emoji: "💑", description: "Spécial relations, amour, jalousie.",     adult: false },
  { id: "pop",      label: "Pop culture", emoji: "🎬", description: "Films, séries, jeux vidéo, super-héros.", adult: false },
];

export interface Question {
  id: number;
  optionA: string;
  optionB: string;
  category: Category;
}

export const QUESTIONS: Question[] = [
  // ========================== SOFT (1-80) ==========================
  { id: 1,  category: "soft", optionA: "Être riche mais malheureux", optionB: "Être pauvre mais heureux" },
  { id: 2,  category: "soft", optionA: "Pouvoir voler", optionB: "Pouvoir devenir invisible" },
  { id: 3,  category: "soft", optionA: "Manger sucré toute sa vie", optionB: "Manger salé toute sa vie" },
  { id: 4,  category: "soft", optionA: "Perdre ses souvenirs", optionB: "N'avoir jamais de nouveaux souvenirs" },
  { id: 5,  category: "soft", optionA: "Savoir tout mais ne rien pouvoir changer", optionB: "Ne rien savoir mais tout pouvoir changer" },
  { id: 6,  category: "soft", optionA: "Vivre 200 ans en bonne santé", optionB: "Revivre sa vie actuelle 3 fois" },
  { id: 7,  category: "soft", optionA: "Pouvoir parler toutes les langues", optionB: "Pouvoir jouer de tous les instruments" },
  { id: 8,  category: "soft", optionA: "Avoir toujours chaud", optionB: "Avoir toujours froid" },
  { id: 9,  category: "soft", optionA: "Ne jamais dormir", optionB: "Dormir 20h par jour" },
  { id: 10, category: "soft", optionA: "Être célèbre mais détesté", optionB: "Être inconnu mais adoré" },
  { id: 11, category: "soft", optionA: "Pouvoir lire dans les pensées", optionB: "Voir le futur" },
  { id: 12, category: "soft", optionA: "Perdre son téléphone", optionB: "Perdre son portefeuille" },
  { id: 13, category: "soft", optionA: "Ne jamais ressentir la douleur", optionB: "Ne jamais ressentir la fatigue" },
  { id: 14, category: "soft", optionA: "Vivre sans musique", optionB: "Vivre sans films/séries" },
  { id: 15, category: "soft", optionA: "Avoir un robot domestique", optionB: "Avoir une voiture volante" },
  { id: 16, category: "soft", optionA: "Manger le même plat chaque jour", optionB: "Ne jamais remanger le même plat" },
  { id: 17, category: "soft", optionA: "Connaître l'heure de sa mort", optionB: "Connaître la cause de sa mort" },
  { id: 18, category: "soft", optionA: "Avoir un super pouvoir inutile", optionB: "N'avoir aucun super pouvoir" },
  { id: 19, category: "soft", optionA: "Voyager dans le passé sans pouvoir changer", optionB: "Voyager dans le futur sans pouvoir revenir" },
  { id: 20, category: "soft", optionA: "Être le plus intelligent du monde", optionB: "Être le plus charismatique du monde" },
  { id: 21, category: "soft", optionA: "Avoir une mémoire parfaite", optionB: "Pouvoir oublier ce que tu veux" },
  { id: 22, category: "soft", optionA: "Perdre le goût", optionB: "Perdre l'odorat" },
  { id: 23, category: "soft", optionA: "Parler en rimes tout le temps", optionB: "Chanter au lieu de parler" },
  { id: 24, category: "soft", optionA: "N'avoir qu'1 ami très proche", optionB: "Avoir 1000 amis superficiels" },
  { id: 25, category: "soft", optionA: "Être toujours en avance", optionB: "Être toujours en retard" },
  { id: 26, category: "soft", optionA: "Vivre seul sur une île déserte 10 ans", optionB: "Vivre dans une mégalopole bondée à vie" },
  { id: 27, category: "soft", optionA: "Pouvoir te téléporter n'importe où", optionB: "Pouvoir arrêter le temps" },
  { id: 28, category: "soft", optionA: "Voyager partout dans le monde sans maison", optionB: "Avoir une maison de rêve qui ne bouge pas" },
  { id: 29, category: "soft", optionA: "Toujours avoir froid aux pieds", optionB: "Toujours avoir les mains moites" },
  { id: 30, category: "soft", optionA: "Refaire ton lit à chaque fois que tu t'assois dessus", optionB: "Refaire tes lacets après chaque pas" },
  { id: 31, category: "soft", optionA: "Pouvoir respirer sous l'eau", optionB: "Pouvoir survivre dans l'espace" },
  { id: 32, category: "soft", optionA: "Avoir 5 enfants", optionB: "Ne jamais en avoir" },
  { id: 33, category: "soft", optionA: "Vivre dans une grotte tout confort", optionB: "Vivre dans un château hanté" },
  { id: 34, category: "soft", optionA: "Manger uniquement chaud", optionB: "Manger uniquement froid" },
  { id: 35, category: "soft", optionA: "Boire seulement de l'eau toute ta vie", optionB: "Manger seulement du pain toute ta vie" },
  { id: 36, category: "soft", optionA: "Avoir des super sens (vue, ouïe, odorat à fond)", optionB: "Avoir un super cerveau" },
  { id: 37, category: "soft", optionA: "Pouvoir parler aux animaux", optionB: "Pouvoir parler aux plantes" },
  { id: 38, category: "soft", optionA: "Ne plus jamais voir la mer", optionB: "Ne plus jamais voir la montagne" },
  { id: 39, category: "soft", optionA: "Être beau mais idiot", optionB: "Être moche mais brillant" },
  { id: 40, category: "soft", optionA: "Voyager dans le temps une seule fois", optionB: "Pouvoir te téléporter une fois par jour" },
  { id: 41, category: "soft", optionA: "Vivre sans internet", optionB: "Vivre sans voiture" },
  { id: 42, category: "soft", optionA: "Avoir 1 million d'euros tout de suite", optionB: "10 millions dans 10 ans" },
  { id: 43, category: "soft", optionA: "Pouvoir arrêter de vieillir à 30 ans", optionB: "Reprendre 10 ans de jeunesse maintenant" },
  { id: 44, category: "soft", optionA: "Chanter parfaitement", optionB: "Danser parfaitement" },
  { id: 45, category: "soft", optionA: "Tout savoir sur le passé de l'humanité", optionB: "Connaître ton futur exact" },
  { id: 46, category: "soft", optionA: "Découvrir une nouvelle galaxie", optionB: "Découvrir un trésor sous l'océan" },
  { id: 47, category: "soft", optionA: "Vivre 100 ans en parfaite santé", optionB: "Vivre 50 ans avec des super pouvoirs" },
  { id: 48, category: "soft", optionA: "Pouvoir voler à 30 km/h max", optionB: "Pouvoir courir à 100 km/h" },
  { id: 49, category: "soft", optionA: "Toujours porter le même vêtement", optionB: "Devoir changer de tenue toutes les 2h" },
  { id: 50, category: "soft", optionA: "N'avoir que 3 heures de jour par 24h", optionB: "N'avoir que 3 heures de nuit par 24h" },
  { id: 51, category: "soft", optionA: "Pouvoir réécrire un seul moment de ta vie", optionB: "Effacer un seul moment de ta vie" },
  { id: 52, category: "soft", optionA: "Vivre dans le passé (1800)", optionB: "Vivre dans le futur (2300)" },
  { id: 53, category: "soft", optionA: "Avoir une bibliothèque infinie", optionB: "Avoir une collection de jeux infinie" },
  { id: 54, category: "soft", optionA: "Tout savoir sur un seul sujet", optionB: "Avoir des bases dans tous les sujets" },
  { id: 55, category: "soft", optionA: "Découvrir un secret bouleversant", optionB: "Garder un secret toute sa vie" },
  { id: 56, category: "soft", optionA: "Avoir une queue d'animal", optionB: "Avoir des oreilles d'animal" },
  { id: 57, category: "soft", optionA: "Voyager sans bagages magiquement", optionB: "Avoir un jet privé gratuit à vie" },
  { id: 58, category: "soft", optionA: "Devenir un personnage de série", optionB: "Inviter un personnage dans la vraie vie" },
  { id: 59, category: "soft", optionA: "Devoir dire \"miaou\" à la fin de chaque phrase", optionB: "Tousser à chaque mot" },
  { id: 60, category: "soft", optionA: "Tout connaître en cuisine", optionB: "Tout connaître en bricolage" },
  { id: 61, category: "soft", optionA: "Conduire une F1", optionB: "Piloter un avion de chasse" },
  { id: 62, category: "soft", optionA: "Habiter sur un bateau", optionB: "Habiter dans une caravane" },
  { id: 63, category: "soft", optionA: "Apprendre instantanément un sport", optionB: "Apprendre instantanément un instrument" },
  { id: 64, category: "soft", optionA: "Ne plus jamais avoir mal aux dents", optionB: "Ne plus jamais avoir mal au crâne" },
  { id: 65, category: "soft", optionA: "Travailler dur 4 jours et avoir 3 jours off", optionB: "Travailler 6 jours peinards" },
  { id: 66, category: "soft", optionA: "Boire un café énorme le matin", optionB: "Faire une sieste de 2h l'après-midi" },
  { id: 67, category: "soft", optionA: "Toujours connaître la bonne réponse", optionB: "Toujours poser la bonne question" },
  { id: 68, category: "soft", optionA: "Vivre avec un ours apprivoisé", optionB: "Vivre avec un lion apprivoisé" },
  { id: 69, category: "soft", optionA: "Recevoir un compliment énorme par jour", optionB: "Faire pleurer de joie quelqu'un par semaine" },
  { id: 70, category: "soft", optionA: "Tout dire à voix haute pour toujours", optionB: "Ne plus jamais dire un mot" },
  { id: 71, category: "soft", optionA: "Avoir un superpouvoir contrôlable", optionB: "Avoir trois superpouvoirs aléatoires" },
  { id: 72, category: "soft", optionA: "Vivre dans un monde sans couleur", optionB: "Vivre dans un monde sans son" },
  { id: 73, category: "soft", optionA: "Connaître une seule langue mais parfaitement", optionB: "Baragouiner toutes les langues" },
  { id: 74, category: "soft", optionA: "Garder ton boulot actuel à vie", optionB: "Changer de métier tous les 2 ans" },
  { id: 75, category: "soft", optionA: "Boire du jus d'orange dans ton café", optionB: "Mettre du sel dans ton chocolat chaud" },
  { id: 76, category: "soft", optionA: "Tour du monde gratuit obligatoire 1 an", optionB: "Recevoir 100k€ et rester chez toi" },
  { id: 77, category: "soft", optionA: "Avoir 100 followers très fidèles", optionB: "Avoir 1 million de followers volatils" },
  { id: 78, category: "soft", optionA: "Vivre une vie courte mais légendaire", optionB: "Vivre une vie longue et tranquille" },
  { id: 79, category: "soft", optionA: "Tout réussir du premier coup", optionB: "Apprendre de tes échecs" },
  { id: 80, category: "soft", optionA: "Voir tes rêves dans la vraie vie", optionB: "Vivre la vraie vie comme un rêve" },

  // ========================== HOT (81-150) =========================
  { id: 81,  category: "hot", optionA: "Faire l'amour très souvent et rapidement", optionB: "Rarement mais longtemps" },
  { id: 82,  category: "hot", optionA: "Faire l'amour en plein jour fenêtres ouvertes", optionB: "La nuit dans le noir total" },
  { id: 83,  category: "hot", optionA: "Avoir un partenaire sublime mais nul au lit", optionB: "Pas top physiquement mais incroyable au lit" },
  { id: 84,  category: "hot", optionA: "Embrasser ton ex en public", optionB: "Embrasser un inconnu en privé" },
  { id: 85,  category: "hot", optionA: "Tout savoir sur la vie sexuelle de ton/ta meilleur(e) ami(e)", optionB: "Qu'iel sache tout sur la tienne" },
  { id: 86,  category: "hot", optionA: "Faire un strip-tease devant tes potes sobres", optionB: "Que ton crush voie tout ton historique de recherches" },
  { id: 87,  category: "hot", optionA: "Coucher avec une seule personne à vie", optionB: "N'avoir que des coups d'un soir" },
  { id: 88,  category: "hot", optionA: "Faire l'amour dans un lieu public", optionB: "Te filmer en train de le faire" },
  { id: 89,  category: "hot", optionA: "Pratiquer le sexe sans tabou avec un coup régulier", optionB: "Avoir un partenaire ultra-romantique mais sage" },
  { id: 90,  category: "hot", optionA: "Recevoir un message coquin par erreur de ton parent", optionB: "De ton patron" },
  { id: 91,  category: "hot", optionA: "Avoir un seul orgasme par mois mais incroyable", optionB: "Plein de petits sans intensité" },
  { id: 92,  category: "hot", optionA: "Tout faire au lit sans préliminaires", optionB: "Que des préliminaires sans rien de plus" },
  { id: 93,  category: "hot", optionA: "Coucher avec quelqu'un qui ressemble à ton/ta meilleur(e) ami(e)", optionB: "À ton/ta ex" },
  { id: 94,  category: "hot", optionA: "Lire un texto coquin de ton/ta crush devant tes parents", optionB: "L'envoyer par erreur à toute ta famille" },
  { id: 95,  category: "hot", optionA: "Coucher dans tous les pays du monde", optionB: "Avoir 100 fois la meilleure nuit de ta vie avec la même personne" },
  { id: 96,  category: "hot", optionA: "Tester un sextoy en public à l'insu des autres", optionB: "Avec tes potes au courant" },
  { id: 97,  category: "hot", optionA: "Que ton/ta ex revienne à fond", optionB: "Rencontrer une nouvelle flamme passionnée" },
  { id: 98,  category: "hot", optionA: "Sex tape qui leak avec une note 8/10", optionB: "Pas de sex tape mais réputation de mauvais coup" },
  { id: 99,  category: "hot", optionA: "Embrasser une célébrité une fois", optionB: "Avoir une nuit avec un inconnu sublime" },
  { id: 100, category: "hot", optionA: "Avoir un contrôle total sur ton excitation", optionB: "Pouvoir contrôler celle des autres" },
  { id: 101, category: "hot", optionA: "Que ton/ta partenaire fasse semblant à chaque fois", optionB: "Qu'iel ne fasse pas du tout d'effort" },
  { id: 102, category: "hot", optionA: "Découvrir un fétiche très bizarre de ton/ta partenaire", optionB: "Que le tien soit révélé sans ton accord" },
  { id: 103, category: "hot", optionA: "Faire l'amour en silence absolu", optionB: "Faire un bruit énorme à chaque fois" },
  { id: 104, category: "hot", optionA: "Être le meilleur coup de ta ville", optionB: "Avoir le plus gros cœur de ta ville" },
  { id: 105, category: "hot", optionA: "Avoir des rapports protégés à vie", optionB: "Une seule fois sans, et qui change ta vie" },
  { id: 106, category: "hot", optionA: "Coucher avec le boss de ton/ta partenaire", optionB: "Que ton/ta partenaire couche avec ton/ta ex" },
  { id: 107, category: "hot", optionA: "Faire un plan à 3 avec deux inconnus", optionB: "Avec deux personnes que tu connais bien" },
  { id: 108, category: "hot", optionA: "Que tes parents trouvent tes sextoys", optionB: "Tes recherches privées sur ton tel" },
  { id: 109, category: "hot", optionA: "N'avoir qu'une seule position pour la vie", optionB: "Toutes les positions mais sans missionnaire" },
  { id: 110, category: "hot", optionA: "Te masturber 3x par jour à vie", optionB: "Plus jamais" },
  { id: 111, category: "hot", optionA: "Faire un coup d'un soir avec ton/ta crush sans suite", optionB: "Te marier avec une personne random demain" },
  { id: 112, category: "hot", optionA: "Avoir un partenaire ultra jaloux", optionB: "Un partenaire trop ouvert" },
  { id: 113, category: "hot", optionA: "Que ta playlist sexe soit publique", optionB: "Que tes positions favorites le soient" },
  { id: 114, category: "hot", optionA: "Coucher avec quelqu'un de 20 ans plus âgé", optionB: "20 ans plus jeune (légalement majeur)" },
  { id: 115, category: "hot", optionA: "Recevoir tous les compliments physiques", optionB: "Tous les compliments intellectuels" },
  { id: 116, category: "hot", optionA: "Coucher avec ton coup de cœur sans jamais le revoir", optionB: "L'aimer sans jamais y toucher" },
  { id: 117, category: "hot", optionA: "Faire l'amour avec interruptions toutes les 5 min", optionB: "Sans pouvoir t'arrêter pendant 4h" },
  { id: 118, category: "hot", optionA: "Tout savoir des fantasmes de tes amis", optionB: "Devoir leur dévoiler tous les tiens" },
  { id: 119, category: "hot", optionA: "Faire un strip-tease pour ton/ta crush bourré(e)", optionB: "Sobre mais devant ses potes" },
  { id: 120, category: "hot", optionA: "Voir ton/ta partenaire au lit avec quelqu'un d'autre", optionB: "Qu'iel te voie le faire" },
  { id: 121, category: "hot", optionA: "N'avoir que des dates dans des fast-foods", optionB: "Que dans des restos étoilés froids" },
  { id: 122, category: "hot", optionA: "Te faire larguer par message", optionB: "Devant tout le monde" },
  { id: 123, category: "hot", optionA: "Une nuit avec ton/ta star préféré(e)", optionB: "Une vie tranquille mais aimée" },
  { id: 124, category: "hot", optionA: "Découvrir que ton/ta partenaire t'a déjà trompé(e)", optionB: "Le/la tromper toi sans qu'iel le sache jamais" },
  { id: 125, category: "hot", optionA: "Que ton/ta partenaire ait beaucoup d'expérience", optionB: "Très peu" },
  { id: 126, category: "hot", optionA: "Avoir un partenaire physiquement parfait mais ennuyeux", optionB: "Drôle mais lambda physiquement" },
  { id: 127, category: "hot", optionA: "Avouer ton fantasme le plus chelou à ta famille", optionB: "À tes collègues" },
  { id: 128, category: "hot", optionA: "Faire un sondage public sur ta vie sexuelle", optionB: "Sur ton compte en banque" },
  { id: 129, category: "hot", optionA: "Te marier avec quelqu'un que tu n'aimes pas pour 1 milliard", optionB: "Vivre seul et fauché" },
  { id: 130, category: "hot", optionA: "Coucher avec une seule personne ULTRA douée", optionB: "100 personnes correctes" },
  { id: 131, category: "hot", optionA: "Apprendre que tes parents ont un kink chelou", optionB: "Que ta grand-mère était escort dans sa jeunesse" },
  { id: 132, category: "hot", optionA: "Sexto en public sans pouvoir te cacher", optionB: "En privé mais leak après" },
  { id: 133, category: "hot", optionA: "Avoir un coup de foudre par mois", optionB: "Un grand amour rare et fou" },
  { id: 134, category: "hot", optionA: "Tomber amoureux de quelqu'un d'autre que ton/ta partenaire", optionB: "Que ton/ta partenaire tombe amoureux d'un(e) autre" },
  { id: 135, category: "hot", optionA: "Que ton crush découvre tes fanfics secrètes", optionB: "Tes vidéos de toi qui chante mal" },
  { id: 136, category: "hot", optionA: "Aimer 100 % pour le physique", optionB: "100 % pour la personnalité" },
  { id: 137, category: "hot", optionA: "Subir une dry spell de 5 ans", optionB: "Une décennie ultra chaude puis plus rien" },
  { id: 138, category: "hot", optionA: "Faire l'amour avec quelqu'un qui pue mais qui te plaît à fond", optionB: "Hyper propre mais zéro attraction" },
  { id: 139, category: "hot", optionA: "Avoir 10 ex toxiques", optionB: "1 seul ex qui t'a brisé(e)" },
  { id: 140, category: "hot", optionA: "Être tagué dans un post embarrassant à vie", optionB: "Devoir poster une story embarrassante par jour" },
  { id: 141, category: "hot", optionA: "Coucher avec un fantôme", optionB: "Un alien" },
  { id: 142, category: "hot", optionA: "Avoir un partenaire célèbre et harcelé", optionB: "Devenir célèbre toi-même et harcelé(e)" },
  { id: 143, category: "hot", optionA: "Que ton vibrateur sonne en plein rdv famille", optionB: "Que ton appli de dating notifie ta mère" },
  { id: 144, category: "hot", optionA: "Découvrir un secret hot sur ton ex", optionB: "Garder ton ex secret toute ta vie" },
  { id: 145, category: "hot", optionA: "Te tatouer le prénom de ton crush actuel", optionB: "Te tatouer un dick pic" },
  { id: 146, category: "hot", optionA: "Ne plus jamais faire l'amour mais avoir tout le reste", optionB: "N'avoir que le sexe et plus aucun lien" },
  { id: 147, category: "hot", optionA: "Avoir un partenaire 10x plus expérimenté", optionB: "10x moins" },
  { id: 148, category: "hot", optionA: "Faire l'amour dans un musée fermé", optionB: "Dans un cimetière de nuit" },
  { id: 149, category: "hot", optionA: "Recevoir des nudes par erreur de ta belle-mère", optionB: "Lui en envoyer par erreur" },
  { id: 150, category: "hot", optionA: "Devoir narrer ta vie sexuelle à voix haute", optionB: "Que tes pensées privées soient diffusées en public" },

  // ========================= TRASH (151-210) =======================
  { id: 151, category: "trash", optionA: "Manger un cafard vivant", optionB: "Boire un verre d'eau de toilette public" },
  { id: 152, category: "trash", optionA: "Découvrir un cadavre dans ta cave", optionB: "Dans ton lit" },
  { id: 153, category: "trash", optionA: "Devoir tuer un chien errant", optionB: "Tuer 100 araignées à la main" },
  { id: 154, category: "trash", optionA: "Lécher la rampe d'un métro parisien", optionB: "Boire l'eau d'un caniveau" },
  { id: 155, category: "trash", optionA: "Découvrir que tu es adopté", optionB: "Que tes enfants ne sont pas tes enfants biologiques" },
  { id: 156, category: "trash", optionA: "Vivre 10 ans en prison innocent", optionB: "Tuer accidentellement quelqu'un et vivre libre" },
  { id: 157, category: "trash", optionA: "Manger un steak de chien", optionB: "Un steak humain" },
  { id: 158, category: "trash", optionA: "Boire 1 litre de pus", optionB: "Manger 1 kg de matière fécale animale" },
  { id: 159, category: "trash", optionA: "Te faire arracher tous les ongles", optionB: "Te faire arracher toutes les dents" },
  { id: 160, category: "trash", optionA: "Voir ton crush mourir devant toi", optionB: "Mourir toi-même mais ton crush ne te connaît pas" },
  { id: 161, category: "trash", optionA: "Apprendre que ton père est un meurtrier", optionB: "Que ta mère t'a abandonné(e) volontairement" },
  { id: 162, category: "trash", optionA: "Découvrir un nid de rats sous ton lit", optionB: "Une caméra dans ta chambre depuis 1 an" },
  { id: 163, category: "trash", optionA: "Tuer pour défendre ta famille", optionB: "Laisser ta famille mourir pour ne pas tuer" },
  { id: 164, category: "trash", optionA: "Te faire tatouer une insulte sur le front", optionB: "Te faire amputer un doigt" },
  { id: 165, category: "trash", optionA: "Manger un yaourt périmé de 6 mois", optionB: "Boire un litre de lait caillé" },
  { id: 166, category: "trash", optionA: "Vivre avec une douleur chronique 8/10", optionB: "Avec une dépression sévère" },
  { id: 167, category: "trash", optionA: "Voir ton enfant mourir", optionB: "Mourir devant ton enfant" },
  { id: 168, category: "trash", optionA: "Devenir paralysé du cou jusqu'aux pieds", optionB: "Perdre la vue ET l'ouïe" },
  { id: 169, category: "trash", optionA: "Manger ton vomi", optionB: "Manger celui d'un inconnu" },
  { id: 170, category: "trash", optionA: "Apprendre que ton/ta partenaire est un tueur en série", optionB: "Un escroc qui t'a tout pris" },
  { id: 171, category: "trash", optionA: "Te réveiller dans un cercueil enterré", optionB: "Dans une morgue" },
  { id: 172, category: "trash", optionA: "Subir une opération sans anesthésie", optionB: "Être brûlé vif pendant 5 secondes" },
  { id: 173, category: "trash", optionA: "Voir tout ton historique internet projeté en public", optionB: "Tes pensées des 24 dernières heures diffusées" },
  { id: 174, category: "trash", optionA: "Prendre une douche de sang", optionB: "Une douche d'urine" },
  { id: 175, category: "trash", optionA: "Découvrir que tu es un clone", optionB: "Que tu es un personnage de simulation" },
  { id: 176, category: "trash", optionA: "Tuer 1 enfant pour sauver 100 inconnus", optionB: "Laisser 100 inconnus mourir" },
  { id: 177, category: "trash", optionA: "Manger un placenta cru", optionB: "Boire du sang humain frais" },
  { id: 178, category: "trash", optionA: "Avoir une lèpre limitée à un bras", optionB: "Une infection qui ronge ton visage" },
  { id: 179, category: "trash", optionA: "Vivre 1 an dans une prison turque", optionB: "5 ans dans un couvent isolé" },
  { id: 180, category: "trash", optionA: "Apprendre que ta vie est un Truman Show", optionB: "Que rien n'a jamais existé" },
  { id: 181, category: "trash", optionA: "Manger un ver de terre vivant", optionB: "Avaler un cafard vivant" },
  { id: 182, category: "trash", optionA: "Devoir tuer ton meilleur ami pour survivre", optionB: "Mourir pour le sauver" },
  { id: 183, category: "trash", optionA: "Boire l'eau d'un aquarium pourri", optionB: "Manger 10 vers de terre" },
  { id: 184, category: "trash", optionA: "Apprendre que ton chien est ton père réincarné", optionB: "Ta grand-mère réincarnée" },
  { id: 185, category: "trash", optionA: "Voir un suicide en direct sans pouvoir agir", optionB: "Devoir l'empêcher physiquement" },
  { id: 186, category: "trash", optionA: "Découvrir le corps d'un proche", optionB: "Apprendre sa mort par téléphone seul" },
  { id: 187, category: "trash", optionA: "Devenir psychopathe sans le savoir", optionB: "Le savoir mais lutter chaque jour" },
  { id: 188, category: "trash", optionA: "Vivre dans une maison hantée vraiment méchante", optionB: "Sans amis, isolé total à vie" },
  { id: 189, category: "trash", optionA: "Te faire arracher les yeux", optionB: "Te faire couper la langue" },
  { id: 190, category: "trash", optionA: "Apprendre que tu as un cancer en stade 4", optionB: "Qu'un de tes parents l'a" },
  { id: 191, category: "trash", optionA: "Tuer ton ennemi juré sans conséquence", optionB: "Pardonner publiquement sans rien obtenir" },
  { id: 192, category: "trash", optionA: "Devoir torturer quelqu'un une fois", optionB: "Être torturé toi une fois" },
  { id: 193, category: "trash", optionA: "Te réveiller couvert de sang sans savoir d'où", optionB: "Te réveiller dans un endroit inconnu sans mémoire" },
  { id: 194, category: "trash", optionA: "Vivre une vie sans amour", optionB: "Une vie d'amours toxiques répétés" },
  { id: 195, category: "trash", optionA: "Te faire enterrer vivant 1h", optionB: "Brûler la main pendant 30 secondes" },
  { id: 196, category: "trash", optionA: "Découvrir un crâne humain dans ton jardin", optionB: "Une tombe dans ta cave" },
  { id: 197, category: "trash", optionA: "Mâcher du verre pilé", optionB: "Boire du verre liquide brûlant" },
  { id: 198, category: "trash", optionA: "Apprendre que ton/ta meilleur(e) ami(e) a couché avec ton/ta partenaire", optionB: "Avec ton parent" },
  { id: 199, category: "trash", optionA: "Te faire mordre par un chien enragé", optionB: "Par 100 araignées" },
  { id: 200, category: "trash", optionA: "Vivre dans un monde sans soleil", optionB: "Sans pluie" },
  { id: 201, category: "trash", optionA: "Te faire écraser dans un ascenseur 24h", optionB: "Coincer en avion 48h" },
  { id: 202, category: "trash", optionA: "Voir tes proches t'oublier", optionB: "Les oublier toi" },
  { id: 203, category: "trash", optionA: "Avoir un cauchemar qui se réalise", optionB: "Un rêve génial qui ne se réalisera jamais" },
  { id: 204, category: "trash", optionA: "Pisser du sang à vie", optionB: "Cracher du sang chaque matin" },
  { id: 205, category: "trash", optionA: "Manger un poisson rouge vivant", optionB: "Manger un hamster vivant" },
  { id: 206, category: "trash", optionA: "Tomber dans une fosse septique", optionB: "Tomber dans un nid de serpents non venimeux" },
  { id: 207, category: "trash", optionA: "Vomir à chaque câlin", optionB: "Pleurer du sang à chaque rire" },
  { id: 208, category: "trash", optionA: "Tuer ton animal de compagnie pour sauver un inconnu", optionB: "Sacrifier l'inconnu" },
  { id: 209, category: "trash", optionA: "Avoir des asticots dans une plaie ouverte 1 mois", optionB: "Une infection à la moelle 1 an" },
  { id: 210, category: "trash", optionA: "Manger des yeux d'animal cru", optionB: "Manger un cerveau cru" },

  // ========================= INSOLITE (211-270) ====================
  { id: 211, category: "insolite", optionA: "Avoir des pieds à la place des mains", optionB: "Des mains à la place des pieds" },
  { id: 212, category: "insolite", optionA: "Roter à chaque \"merci\"", optionB: "Péter à chaque rire" },
  { id: 213, category: "insolite", optionA: "Avoir la tête à l'envers en permanence", optionB: "Marcher uniquement à reculons" },
  { id: 214, category: "insolite", optionA: "Cracher des paillettes", optionB: "Pleurer du miel" },
  { id: 215, category: "insolite", optionA: "Avoir une queue de licorne", optionB: "Des ailes de chauve-souris" },
  { id: 216, category: "insolite", optionA: "Saigner du nez à chaque mensonge", optionB: "Bafouiller à chaque vérité" },
  { id: 217, category: "insolite", optionA: "Sentir le fromage en permanence", optionB: "Le poisson cru en permanence" },
  { id: 218, category: "insolite", optionA: "Te transformer en chat la nuit", optionB: "En grenouille en cas d'émotion forte" },
  { id: 219, category: "insolite", optionA: "Bouger uniquement en sautillant", optionB: "Uniquement en rampant" },
  { id: 220, category: "insolite", optionA: "Avoir 3 yeux", optionB: "4 oreilles" },
  { id: 221, category: "insolite", optionA: "Être miniaturisé à 5 cm 1 jour par mois", optionB: "Géant 3 m une semaine par an" },
  { id: 222, category: "insolite", optionA: "Avoir un nez de Pinocchio", optionB: "Un long cou de girafe" },
  { id: 223, category: "insolite", optionA: "Devenir un nain de jardin la nuit", optionB: "Un mannequin de vitrine le jour" },
  { id: 224, category: "insolite", optionA: "Cheveux qui poussent à 1 m/jour", optionB: "Ongles à 10 cm/jour" },
  { id: 225, category: "insolite", optionA: "Cracher du feu une fois par jour", optionB: "Geler tout en touchant" },
  { id: 226, category: "insolite", optionA: "Pondre un œuf par mois", optionB: "Muer comme un serpent une fois par an" },
  { id: 227, category: "insolite", optionA: "Avoir des bras tentacules", optionB: "Des jambes ressorts" },
  { id: 228, category: "insolite", optionA: "Tout entendre 10x plus fort", optionB: "Tout voir avec un délai de 3 secondes" },
  { id: 229, category: "insolite", optionA: "Devoir parler avec des effets sonores Tex Avery", optionB: "Comme un robot" },
  { id: 230, category: "insolite", optionA: "Avoir un parfum naturel d'oignon", optionB: "De pet" },
  { id: 231, category: "insolite", optionA: "Devenir invisible quand tu pleures", optionB: "Voler quand tu rigoles" },
  { id: 232, category: "insolite", optionA: "Avoir une tête de poisson", optionB: "Un corps de poulpe" },
  { id: 233, category: "insolite", optionA: "Boire ton café par les yeux", optionB: "Manger par tes oreilles" },
  { id: 234, category: "insolite", optionA: "Dents qui repoussent chaque mois", optionB: "Cheveux qui changent de couleur chaque jour" },
  { id: 235, category: "insolite", optionA: "Devenir réellement hypnotisable", optionB: "Pouvoir hypnotiser sans le contrôler" },
  { id: 236, category: "insolite", optionA: "Pondre une perle quand tu rigoles", optionB: "Cracher une larme dorée quand tu pleures" },
  { id: 237, category: "insolite", optionA: "Peau qui change de couleur selon ton humeur", optionB: "Peau qui devient transparente sous stress" },
  { id: 238, category: "insolite", optionA: "Avoir 3 estomacs", optionB: "2 cœurs" },
  { id: 239, category: "insolite", optionA: "Être en mode caméléon", optionB: "En mode fluo permanent" },
  { id: 240, category: "insolite", optionA: "Te transformer en pizza si tu en manges", optionB: "En licorne si tu mens" },
  { id: 241, category: "insolite", optionA: "Pouvoir parler à ton reflet", optionB: "À ton ombre" },
  { id: 242, category: "insolite", optionA: "Avoir une voix de Mickey", optionB: "Une voix de Dark Vador" },
  { id: 243, category: "insolite", optionA: "Avoir un super odorat de chien", optionB: "Une vue d'aigle" },
  { id: 244, category: "insolite", optionA: "Recevoir des notifications dans la tête", optionB: "Avoir un GPS interne" },
  { id: 245, category: "insolite", optionA: "Pouvoir éternuer des chips", optionB: "Pleurer du chocolat" },
  { id: 246, category: "insolite", optionA: "Être doué pour parler aux fantômes", optionB: "Aux extraterrestres" },
  { id: 247, category: "insolite", optionA: "Te dupliquer mais sans contrôle", optionB: "Être à 2 endroits par téléportation contrôlée" },
  { id: 248, category: "insolite", optionA: "Manger seulement avec une cuillère minuscule", optionB: "Avec des baguettes de 1 m" },
  { id: 249, category: "insolite", optionA: "Avoir un assistant invisible chiant", optionB: "Un coach personnel ultra strict" },
  { id: 250, category: "insolite", optionA: "Vivre sous l'eau 1 an", optionB: "Dans l'espace 1 an" },
  { id: 251, category: "insolite", optionA: "Toujours être suivi d'un nuage de pluie", optionB: "D'un essaim de papillons" },
  { id: 252, category: "insolite", optionA: "Recevoir un cadeau bizarre par jour", optionB: "Donner un objet bizarre tous les jours" },
  { id: 253, category: "insolite", optionA: "Avoir une oreille qui bouge toute seule", optionB: "Un orteil indépendant" },
  { id: 254, category: "insolite", optionA: "Voir le monde en cartoon", optionB: "En noir et blanc" },
  { id: 255, category: "insolite", optionA: "Tous tes cheveux blanchissent en une nuit", optionB: "Devenir totalement chauve" },
  { id: 256, category: "insolite", optionA: "Avoir un perroquet qui répète tes pensées", optionB: "Un chat qui te juge à voix haute" },
  { id: 257, category: "insolite", optionA: "Manger seulement avec tes pieds", optionB: "Boire en aspirant par le nez" },
  { id: 258, category: "insolite", optionA: "Tousser des bulles", optionB: "Éternuer des étincelles" },
  { id: 259, category: "insolite", optionA: "Mesurer 30 cm de plus", optionB: "30 cm de moins" },
  { id: 260, category: "insolite", optionA: "Avoir un alter ego officiel", optionB: "Une marionnette qui parle pour toi" },
  { id: 261, category: "insolite", optionA: "Devenir vert en buvant de l'eau", optionB: "Bleu en mangeant" },
  { id: 262, category: "insolite", optionA: "Toujours porter un costume de banane", optionB: "Une combinaison de plongée" },
  { id: 263, category: "insolite", optionA: "Recevoir une chanson improvisée à chaque rencontre", optionB: "Un slam à chaque fin de phrase" },
  { id: 264, category: "insolite", optionA: "Pouvoir transformer l'eau en jus", optionB: "La nourriture en cendre" },
  { id: 265, category: "insolite", optionA: "Avoir une moustache permanente quel que soit ton genre", optionB: "Plus de pilosité partout" },
  { id: 266, category: "insolite", optionA: "Apparaître dans tous les selfies des inconnus", optionB: "Disparaître de toutes tes propres photos" },
  { id: 267, category: "insolite", optionA: "Avoir un zoom oculaire", optionB: "Une vision nocturne d'animal" },
  { id: 268, category: "insolite", optionA: "Léviter à 10 cm en permanence", optionB: "Marcher sur les murs" },
  { id: 269, category: "insolite", optionA: "Avoir un mode pause de 1 seconde", optionB: "Un mode rewind 5 secondes" },
  { id: 270, category: "insolite", optionA: "Prédire la météo à 100 %", optionB: "Prédire les bouchons à 100 %" },

  // ========================= ETHIQUE (271-320) =====================
  { id: 271, category: "ethique", optionA: "Voler les riches pour donner aux pauvres", optionB: "Tout laisser tel quel" },
  { id: 272, category: "ethique", optionA: "Sauver 1 inconnu par jour mais perdre la mémoire", optionB: "Mémoire intacte mais ne sauver personne" },
  { id: 273, category: "ethique", optionA: "Mentir pour sauver une vie", optionB: "Dire la vérité quoi qu'il arrive" },
  { id: 274, category: "ethique", optionA: "Tuer un dictateur de tes mains", optionB: "Le laisser vivre et faire 10 000 morts" },
  { id: 275, category: "ethique", optionA: "Sauver ton enfant", optionB: "Sauver 5 inconnus" },
  { id: 276, category: "ethique", optionA: "Donner tout ton argent aux pauvres", optionB: "Le garder pour ta famille" },
  { id: 277, category: "ethique", optionA: "Trahir un ami pour sauver 100 vies", optionB: "Ne rien dire et laisser mourir" },
  { id: 278, category: "ethique", optionA: "Mettre un secret au grand jour", optionB: "Le garder pour préserver la paix" },
  { id: 279, category: "ethique", optionA: "Travailler dans une boîte non éthique pour 200 k€", optionB: "Bosser éthique au SMIC" },
  { id: 280, category: "ethique", optionA: "Refuser de témoigner pour sauver un coupable proche", optionB: "Témoigner et le trahir" },
  { id: 281, category: "ethique", optionA: "Sauver un humain inconnu", optionB: "Sauver 10 chiens" },
  { id: 282, category: "ethique", optionA: "Forcer un don d'organe pour sauver ton enfant", optionB: "Le laisser mourir" },
  { id: 283, category: "ethique", optionA: "Faire la morale à un ami toxique", optionB: "Te taire pour ne pas le perdre" },
  { id: 284, category: "ethique", optionA: "Sauver ton père", optionB: "Sauver le président" },
  { id: 285, category: "ethique", optionA: "Aider un ennemi en danger", optionB: "Le laisser souffrir" },
  { id: 286, category: "ethique", optionA: "Manger du foie gras quotidien", optionB: "Du veau élevé en cage" },
  { id: 287, category: "ethique", optionA: "Pirater un site pour démasquer une arnaque", optionB: "Laisser faire" },
  { id: 288, category: "ethique", optionA: "Te taire face à une injustice par sécurité", optionB: "Parler et risquer ta carrière" },
  { id: 289, category: "ethique", optionA: "Décider d'arrêter les machines pour un proche", optionB: "Le laisser vivre comateux 20 ans" },
  { id: 290, category: "ethique", optionA: "Avorter en cas de viol", optionB: "Garder l'enfant" },
  { id: 291, category: "ethique", optionA: "Devenir lanceur d'alerte au prix de ta liberté", optionB: "Garder le silence et être tranquille" },
  { id: 292, category: "ethique", optionA: "Couper la jambe d'un proche pour le sauver", optionB: "Le laisser mourir intact" },
  { id: 293, category: "ethique", optionA: "Sauver une œuvre d'art unique de l'histoire", optionB: "Sauver un inconnu" },
  { id: 294, category: "ethique", optionA: "Effacer ta dette par fraude", optionB: "Bosser 20 ans pour la rembourser" },
  { id: 295, category: "ethique", optionA: "Sauver un enfant", optionB: "Sauver ton parent âgé" },
  { id: 296, category: "ethique", optionA: "Trahir ton pays par conviction", optionB: "Te conformer" },
  { id: 297, category: "ethique", optionA: "Mentir à ton enfant sur sa vraie origine", optionB: "Lui dire la vérité douloureuse" },
  { id: 298, category: "ethique", optionA: "Adopter un enfant en danger", optionB: "Donner l'argent à une asso pour sauver 10 enfants" },
  { id: 299, category: "ethique", optionA: "Sauver un milliardaire qui finance la recherche", optionB: "Sauver 5 SDF" },
  { id: 300, category: "ethique", optionA: "Cacher la honte d'un proche aux dépens d'un inconnu", optionB: "Faire éclater la vérité" },
  { id: 301, category: "ethique", optionA: "Vivre une vie altruiste mais malheureuse", optionB: "Égoïste mais épanouie" },
  { id: 302, category: "ethique", optionA: "Refuser un boulot d'armement à 500 k€/an", optionB: "Accepter" },
  { id: 303, category: "ethique", optionA: "Saboter un projet immoral", optionB: "Le laisser réussir" },
  { id: 304, category: "ethique", optionA: "Choisir l'euthanasie pour un proche en accord", optionB: "Lutter contre vents et marées" },
  { id: 305, category: "ethique", optionA: "Trahir ta meilleure amie pour la vérité", optionB: "La couvrir" },
  { id: 306, category: "ethique", optionA: "Donner tes économies pour un don d'organe", optionB: "Garder pour ta retraite" },
  { id: 307, category: "ethique", optionA: "Refuser une greffe pour qu'elle aille à un enfant", optionB: "La prendre" },
  { id: 308, category: "ethique", optionA: "Cacher une preuve qui sauverait un inconnu mais condamnerait un proche", optionB: "Faire le contraire" },
  { id: 309, category: "ethique", optionA: "Être juré pour condamner un coupable de ta famille", optionB: "Refuser et se récuser" },
  { id: 310, category: "ethique", optionA: "Faire signer un contrat manipulé pour ton bien", optionB: "Renoncer" },
  { id: 311, category: "ethique", optionA: "Aider un migrant clandestin", optionB: "Le dénoncer (selon la loi)" },
  { id: 312, category: "ethique", optionA: "Subir une injustice silencieux", optionB: "Hurler et risquer la prison" },
  { id: 313, category: "ethique", optionA: "Voler de la nourriture pour ton enfant qui meurt de faim", optionB: "Le laisser à son sort" },
  { id: 314, category: "ethique", optionA: "Lyncher publiquement un agresseur", optionB: "Pardonner publiquement" },
  { id: 315, category: "ethique", optionA: "Désobéir aux ordres dans un job", optionB: "Obéir et faire du mal" },
  { id: 316, category: "ethique", optionA: "Élever ton enfant en lui laissant choisir son genre", optionB: "Lui imposer un genre" },
  { id: 317, category: "ethique", optionA: "Refuser une formation imposée injuste", optionB: "Accepter et garder ton job" },
  { id: 318, category: "ethique", optionA: "Diffuser une preuve volée pour la justice", optionB: "Respecter la loi" },
  { id: 319, category: "ethique", optionA: "Saboter une élection pour un meilleur candidat", optionB: "Laisser perdre" },
  { id: 320, category: "ethique", optionA: "Élever des enfants athées", optionB: "Religieux pratiquants" },

  // ========================= COUPLE (321-370) ======================
  { id: 321, category: "couple", optionA: "Découvrir que ton/ta partenaire t'a trompé une fois", optionB: "Plusieurs fois en émotionnel sans coucher" },
  { id: 322, category: "couple", optionA: "Que ton/ta partenaire vibe sur tes potes", optionB: "Sur ton/ta meilleur(e) ami(e)" },
  { id: 323, category: "couple", optionA: "Vivre un amour intense 5 ans", optionB: "Une relation tranquille 50 ans" },
  { id: 324, category: "couple", optionA: "Avoir un mariage de rêve à 100 k€", optionB: "Voyager 10 ans avec ton/ta partenaire" },
  { id: 325, category: "couple", optionA: "Découvrir le passé sentimental complet de ton/ta partenaire", optionB: "Garder le mystère" },
  { id: 326, category: "couple", optionA: "Te marier avec ton premier amour", optionB: "Avec une nouvelle rencontre passionnante" },
  { id: 327, category: "couple", optionA: "Que ton/ta partenaire passe une nuit blanche avec son ex", optionB: "Avec un parfait inconnu" },
  { id: 328, category: "couple", optionA: "Embrasser quelqu'un par accident sans rien dire", optionB: "Tout avouer" },
  { id: 329, category: "couple", optionA: "Que ton/ta partenaire t'embrasse devant ses parents", optionB: "Devant tes parents" },
  { id: 330, category: "couple", optionA: "Vivre en couple sans dispute", optionB: "Avec disputes mais réconciliations passionnées" },
  { id: 331, category: "couple", optionA: "Apprendre que ton/ta partenaire a un enfant caché", optionB: "Une famille parallèle" },
  { id: 332, category: "couple", optionA: "Avoir une relation à distance pendant 5 ans", optionB: "Une rupture maintenant" },
  { id: 333, category: "couple", optionA: "Faire une pause de 6 mois sans contact", optionB: "Rompre direct" },
  { id: 334, category: "couple", optionA: "Que ton/ta partenaire choisisse ses parents au lieu de toi", optionB: "Te choisisse au lieu d'eux" },
  { id: 335, category: "couple", optionA: "Vivre avec ton/ta partenaire H24", optionB: "Habiter séparément à vie" },
  { id: 336, category: "couple", optionA: "Te marier sans amour pour la sécurité", optionB: "Vivre seul amoureux" },
  { id: 337, category: "couple", optionA: "Aimer quelqu'un qui ne t'aime pas", optionB: "Être aimé(e) par quelqu'un que tu n'aimes pas" },
  { id: 338, category: "couple", optionA: "Tomber amoureux pendant un mariage déjà programmé", optionB: "Y renoncer juste avant" },
  { id: 339, category: "couple", optionA: "Avoir une relation polyamoureuse", optionB: "Strictement monogame" },
  { id: 340, category: "couple", optionA: "Vivre avec un fantôme du passé qui revient", optionB: "Avancer définitivement sans regard arrière" },
  { id: 341, category: "couple", optionA: "Sacrifier ta carrière pour ton couple", optionB: "Ton couple pour ta carrière" },
  { id: 342, category: "couple", optionA: "Découvrir un journal intime de ton/ta partenaire", optionB: "Lui montrer le tien en intégralité" },
  { id: 343, category: "couple", optionA: "Pardonner une trahison une seule fois", optionB: "Ne jamais pardonner quoi qu'il arrive" },
  { id: 344, category: "couple", optionA: "Qu'iel kiffe physiquement quelqu'un d'autre sans agir", optionB: "Qu'iel agisse sans en parler" },
  { id: 345, category: "couple", optionA: "Coup de foudre avec quelqu'un déjà en couple", optionB: "Avec un inconnu loin et inaccessible" },
  { id: 346, category: "couple", optionA: "Faire l'amour 1 fois par mois mais profond", optionB: "Souvent mais sans connexion émotionnelle" },
  { id: 347, category: "couple", optionA: "Te marier à 20 ans pour la vie", optionB: "À 60 ans pour quelques années" },
  { id: 348, category: "couple", optionA: "Quitter quelqu'un que tu aimes", optionB: "Rester avec quelqu'un que tu n'aimes plus" },
  { id: 349, category: "couple", optionA: "Que ton/ta partenaire ne change jamais", optionB: "Qu'iel évolue radicalement" },
  { id: 350, category: "couple", optionA: "Apprendre que ton/ta partenaire ne veut plus d'enfants", optionB: "Qu'iel en veut soudain 5" },
  { id: 351, category: "couple", optionA: "Avoir un coup d'un soir mémorable", optionB: "Une histoire sans cul mais profonde" },
  { id: 352, category: "couple", optionA: "Découvrir le crush secret de ton/ta partenaire", optionB: "Lui révéler le tien" },
  { id: 353, category: "couple", optionA: "Vivre dans la maison familiale de tes beaux-parents", optionB: "Sans logement à toi" },
  { id: 354, category: "couple", optionA: "Que ton/ta partenaire apprenne ton plus gros fantasme", optionB: "Que tu apprennes le sien" },
  { id: 355, category: "couple", optionA: "Te marier avec quelqu'un d'introverti", optionB: "D'extraverti exubérant" },
  { id: 356, category: "couple", optionA: "Apprendre que ton/ta partenaire a menti sur son âge", optionB: "Sur son métier" },
  { id: 357, category: "couple", optionA: "Avoir une relation pleine de cadeaux luxueux", optionB: "Pleine d'attentions sans aucun cadeau" },
  { id: 358, category: "couple", optionA: "Aimer quelqu'un qui s'éloigne", optionB: "Qui s'accroche trop" },
  { id: 359, category: "couple", optionA: "Que ton/ta partenaire fasse une crise de jalousie monstre", optionB: "Une crise d'indifférence totale" },
  { id: 360, category: "couple", optionA: "Faire une demande publique gigantesque", optionB: "Très intime, juste à deux" },
  { id: 361, category: "couple", optionA: "Aller voir un coach matrimonial à deux", optionB: "Y aller chacun seul" },
  { id: 362, category: "couple", optionA: "Avouer un fantasme à ton/ta partenaire qui te juge", optionB: "Le garder pour toi à vie" },
  { id: 363, category: "couple", optionA: "Que ton/ta partenaire ait une amitié intime forte avec quelqu'un d'autre", optionB: "N'ait aucun(e) ami(e)" },
  { id: 364, category: "couple", optionA: "Apprendre la mort de ton ex", optionB: "De ton crush actuel" },
  { id: 365, category: "couple", optionA: "Tomber amoureux de la meilleure amie de ton/ta partenaire", optionB: "Du frère / de la sœur" },
  { id: 366, category: "couple", optionA: "Te marier rapidement après 6 mois", optionB: "Attendre 7 ans pour être sûr(e)" },
  { id: 367, category: "couple", optionA: "Découvrir que ta première fois était filmée", optionB: "Que tes premiers baisers l'étaient" },
  { id: 368, category: "couple", optionA: "Que ton/ta partenaire ait un crush insta sur quelqu'un", optionB: "Sur ton boss" },
  { id: 369, category: "couple", optionA: "Recevoir une lettre d'amour 10 ans après", optionB: "Envoyer une lettre 10 ans trop tard" },
  { id: 370, category: "couple", optionA: "Te faire larguer le jour de ton anniversaire", optionB: "Le jour de Noël" },

  // ========================= POP CULTURE (371-400) =================
  { id: 371, category: "pop", optionA: "Vivre 1 jour dans Harry Potter", optionB: "Dans Le Seigneur des Anneaux" },
  { id: 372, category: "pop", optionA: "Être un personnage de Game of Thrones", optionB: "De Breaking Bad" },
  { id: 373, category: "pop", optionA: "Vivre dans Mario Kart", optionB: "Dans GTA" },
  { id: 374, category: "pop", optionA: "Avoir le pouvoir de Spider-Man", optionB: "De Wonder Woman" },
  { id: 375, category: "pop", optionA: "Combattre Thanos avec un gant", optionB: "Voldemort sans baguette" },
  { id: 376, category: "pop", optionA: "Devenir un Pokémon", optionB: "Devenir un dresseur" },
  { id: 377, category: "pop", optionA: "Vivre dans Stranger Things", optionB: "Dans The Last of Us" },
  { id: 378, category: "pop", optionA: "Avoir Iron Man comme père", optionB: "Joker comme oncle" },
  { id: 379, category: "pop", optionA: "Mourir comme dans Final Destination", optionB: "Comme dans Saw" },
  { id: 380, category: "pop", optionA: "Vivre dans Squid Game", optionB: "Dans Hunger Games" },
  { id: 381, category: "pop", optionA: "Avoir un dragon de GoT", optionB: "Un patronus de Harry Potter" },
  { id: 382, category: "pop", optionA: "Sortir avec Hermione", optionB: "Avec Eleven" },
  { id: 383, category: "pop", optionA: "Boire un verre avec Tony Stark", optionB: "Avec Capitaine Jack Sparrow" },
  { id: 384, category: "pop", optionA: "Faire un duel avec Goku", optionB: "Avec Naruto" },
  { id: 385, category: "pop", optionA: "Vivre 1 an dans Westworld", optionB: "Dans Black Mirror" },
  { id: 386, category: "pop", optionA: "Être un Avenger", optionB: "Un X-Men" },
  { id: 387, category: "pop", optionA: "Posséder la Death Star", optionB: "La baguette de sureau" },
  { id: 388, category: "pop", optionA: "Combattre un xénomorphe", optionB: "Un Predator" },
  { id: 389, category: "pop", optionA: "Avoir Batman comme mentor", optionB: "Iron Man" },
  { id: 390, category: "pop", optionA: "Vivre dans Friends", optionB: "Dans How I Met Your Mother" },
  { id: 391, category: "pop", optionA: "Affronter Sauron", optionB: "Le Roi Lion adulte" },
  { id: 392, category: "pop", optionA: "Visiter Hogwarts", optionB: "Visiter Naboo" },
  { id: 393, category: "pop", optionA: "Devenir un Sith", optionB: "Un Jedi" },
  { id: 394, category: "pop", optionA: "Avoir KITT", optionB: "La DeLorean" },
  { id: 395, category: "pop", optionA: "Te battre avec Bruce Lee", optionB: "Avec Chuck Norris" },
  { id: 396, category: "pop", optionA: "Mourir comme un personnage Marvel", optionB: "Un personnage DC" },
  { id: 397, category: "pop", optionA: "Vivre 1 saison dans Lost", optionB: "Dans The Walking Dead" },
  { id: 398, category: "pop", optionA: "Avoir Pikachu comme animal", optionB: "Avoir Stitch" },
  { id: 399, category: "pop", optionA: "Échanger une vie avec ton acteur préféré", optionB: "Avec ton chanteur préféré" },
  { id: 400, category: "pop", optionA: "Visiter le métavers de Ready Player One", optionB: "La Matrice de Matrix" },
];
